//<auto-generated/>
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using TFX.Core.Controllers;
using TFX.Core.Services;
using System;
using TFX.Core.Model;
using Microsoft.AspNetCore.Http;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using TFX.Core.Data;
using Tootega.Core.CEP.Services;
using Tootega.Core.CEP.Services.Rules;

namespace Tootega.Core.CEP.Services
{
    [Route("UF")]
    [ApiController]
    public class UFController : XController
    {
        public abstract class BaseINFUFControllerRule : XControllerINFRule<UFController>
        {
            public BaseINFUFControllerRule(UFController pController)
                :base(pController)
            {
            }
        }

        public UFController(IUFService pService)
        {
            Service = pService;
            _Rule = new INFUFControllerRule(this);
        }

        internal readonly IUFService Service;
        private readonly INFUFControllerRule _Rule;

        [HttpPost("Search")]
        [ProducesResponseType(typeof(UFDataSet), StatusCodes.Status200OK)]
        [ProducesResponseType(typeof(XEndPointMessage), StatusCodes.Status404NotFound)]
        public IActionResult Execute()
        {
            try
            {
                var dst = Service.Execute();
                return Ok(dst);
            }
            catch (Exception pEx)
            {
                return StatusCode(404, XEndPointMessage.Erro(pEx));
            }  
        }
    }
}