//<auto-generated/>
using System;
using System.Linq;
using System.Runtime.InteropServices;
using System.Collections.Generic;
using Newtonsoft.Json;
using TFX.Core.Model.Cache;
using TFX.Core.Model.Data;
using TFX.Core.Model.DIC.SVC;
using TFX.Core.Model.DIC.ORM;
using TFX.Core.Model.DIC.Types;
using TFX.Core.Model.Interfaces;
using TFX.Core.Model.Services;
using TFX.Core.Reflections;
using TFX.Core.Objects;
#if !OnlyDef
using TFX.Core.Service.Job;
using TFX.Core.Service.SVC;
#endif
using TFX.Core.Model.DIC.FRM;
using TFX.Core.Model.DIC.APP;
using TFX.Core.Model.DIC.RPT;
using Projecao.Core.ERP.DB;
using Projecao.Core.PET.DB;

namespace Projecao.Core.PET.Tutor
{
    [XDASESource(@"D:\Tootega\Source\TFX20\Modules\Projecao.Core.PET\Projecao.Core.PET.csproj", @"D:\Tootega\Source\TFX20\Modules\Projecao.Core.PET\Tutor\Animal.dssvc")]
    [XRegister(typeof(AnimalSVC), sCID)]
    public class AnimalSVC : XSVCModel
    {
        #region AnimalFilterFRM

        [XRegister(typeof(AnimalFilterFRM), sCID)]
        public class AnimalFilterFRM : XFRMModel
        {
            public const String sCID = "4F717469-591F-42D7-8411-FB5C9A2926DB";
            public static new readonly Guid gCID = new Guid(sCID);
            static AnimalFilterFRM()
            {
                gCID = new Guid(sCID);
            }
            public AnimalFilterFRM()
            {
                ID = gCID;
                Name = "AnimalFilter";
                Title = "";
                MinRows = 2;
                ConfigCID = new Guid("00000000-0000-0000-0000-000000000000");
                ConfigPKFilter = false;
                ReferenceScripts = new String[] { "TFX.Core.Service.js", "Projecao.Core.CEP.js", "Projecao.Core.ERP.js", "Projecao.Core.IMC.js", "Projecao.Core.ISE.js", "Projecao.Core.PET.js" };
                Rect = new XRect(20, 20, 965, 678);
                Style = XFRMStyle.Normal;
                ActionContext = XActionContext.All;
                AddItem(Nome);
                Nome.ForceRW = true;
                Nome.CanInsert = true;
                Nome.CanUpdate = true;
                Nome.RowCount = 2;
                Nome.ColCount = 32;
                Nome.RowCountSmall = 2;
                Nome.ColCountSmall = 32;
                Nome.IsHidden = false;
                Nome.IsHiddenSmall = false;
                Nome.AdditionalTitle = "";
                Nome.Icon = "";
                Nome.Location = 1;
                Nome.EditorCID = new Guid("F5982E79-BA45-40FB-85E1-9F2C8B90B6EF");
                Nome.Operator = XOperator.Like;
                Nome.ShowSpin = false;
                Nome.HotkeyChar = "";
                Nome.JustifyHeight = false;
                Nome.AllowEmpty = true;
                Nome.FontColor = "#000000";
                Nome.FontStyle = XFontStyle.Normal;
                Nome.ShowFooter = false;
                Nome.ViewSAM = new Guid("00000000-0000-0000-0000-000000000000");
                Nome.Order = 1;
                Nome.Scale = -1;
                Nome.Length = -1;
                Nome.SearchAction = XSearchAction.Default;
                Nome.TypeID = XString.CID;
                Nome.AdditionalFieldsID = new Guid[] {  };
                Nome.AdditionalDataFieldsID = new Guid[] {  };
                Nome.TargetFilterFieldID = new Guid[] {  };
                Nome.SourceFilterFieldID = new Guid[] {  };
                Nome.TargetDisplayFieldID = new Guid[] {  };
                Nome.SourceDisplayFieldID = new Guid[] {  };
                Nome.AutoLoad = false;
                Nome.FilterInative = true;
                Nome.IsAnswer = false;
                Nome.AllowMultiSelect = false;
            }
            public XFRMField Nome = new XFRMField(new Guid("C52E536A-E7FF-4B48-B5FE-E997859177F2"), "Nome", "Nome", XString.CID, 2, 32, false, gCID, null, new Guid("E585E902-3B9F-4555-A9DB-400BB537DC0F")); // String;
            public static class Fields
            {
                public static XFieldInfo Nome = new XFieldInfo(new Guid("C52E536A-E7FF-4B48-B5FE-E997859177F2"), "Nome", "Nome", typeof(String), false, "");
            }
        }

        #endregion AnimalFilterFRM

        public const String sCID = "0AF54CE8-D142-4BC6-AC86-03FB95EBC282";
        public static Guid gCID = new Guid(sCID);
        public static XSVCReference PETxPorte_PETxPorteID_PETxAnimal_PETxPorteID; // PETxPorte.PETxPorteID --> PETxAnimal.PETxPorteID
        public static XSVCReference PETxAnimalTutor_PETxAnimalID_PETxAnimal_PETxAnimalID; // PETxAnimalTutor.PETxAnimalID --> PETxAnimal.PETxAnimalID
        public static XSVCReference PETxRaca_PETxRacaID_PETxAnimal_PETxRacaID; // PETxRaca.PETxRacaID --> PETxAnimal.PETxRacaID
        public static XSVCReference ERPxGenero_ERPxGeneroID_PETxAnimal_ERPxSexoID; // ERPxGenero.ERPxGeneroID --> PETxAnimal.ERPxSexoID
        public static XSVCReference PETxFamilia_PETxFamiliaID_PETxRaca_PETxFamiliaID; // PETxFamilia.PETxFamiliaID --> PETxRaca.PETxFamiliaID
        public static XSVCReference PETxPelagem_PETxPelagemID_PETxAnimal_PETxPelagemID; // PETxPelagem.PETxPelagemID --> PETxAnimal.PETxPelagemID

        #region xERPxGenero 
        public class xERPxGenero : XSVCTable
        {

            public static Guid gCID => new Guid("0777BAC3-19CC-4BF6-9BDD-8DEDF8FF2A11");

            public xERPxGenero()
            {
                Name = "ERPxGenero";
                Alias = "ERPxGenero";
                ID = gCID;
                ParentID =  global::Projecao.Core.ERP.DB.ERPx.ERPxGenero.gCID;

                Items.Add(Genero, Genero.ID);
                Genero.Owner = this;
                Genero.OwnerID = ID;
                Genero.TableName = Name;
                Genero.Alias = "Genero";
                Items.Add(ERPxGeneroID, ERPxGeneroID.ID);
                ERPxGeneroID.Owner = this;
                ERPxGeneroID.OwnerID = ID;
                ERPxGeneroID.TableName = Name;
                Items.Add(Invisivel, Invisivel.ID);
                Invisivel.Owner = this;
                Invisivel.OwnerID = ID;
                Invisivel.TableName = Name;
                Items.Add(Designacao, Designacao.ID);
                Designacao.Owner = this;
                Designacao.OwnerID = ID;
                Designacao.TableName = Name;
                Designacao.Alias = "Designacao";
            }

            public static XORMFaceField Genero = new XORMFaceField(global::Projecao.Core.ERP.DB.ERPx.ERPxGenero.Genero, new Guid("DA11545F-F06D-4B21-A3FE-959E307CFDE5"), "Genero", "Gênero");
            public static XORMPKField ERPxGeneroID = new XORMPKField(global::Projecao.Core.ERP.DB.ERPx.ERPxGenero.ERPxGeneroID, new Guid("912DF4D3-F0E9-4578-9B43-EF782879EC3E"), "ERPxGeneroID", "Gênero");
            public static XORMField Invisivel = new XORMField(global::Projecao.Core.ERP.DB.ERPx.ERPxGenero.Invisivel, new Guid("8387D9B6-6C65-4C94-AE03-62285A5A93FD"), "Invisivel", "Invisível");
            public static XORMField Designacao = new XORMField(global::Projecao.Core.ERP.DB.ERPx.ERPxGenero.Designacao, new Guid("BFB1B8C2-F0EA-457A-9777-73020BE58592"), "Designacao", "Designação");
        }
        #endregion xERPxGenero 


        #region xPETxAnimal 
        public class xPETxAnimal : XSVCTable
        {

            public static Guid gCID => new Guid("157A9565-8300-4A29-A006-3CB32E72D334");

            public xPETxAnimal()
            {
                Name = "PETxAnimal";
                Alias = "PETxAnimal";
                ID = gCID;
                ParentID =  global::Projecao.Core.PET.DB.PETx.PETxAnimal.gCID;

                Items.Add(PETxAnimalID, PETxAnimalID.ID);
                PETxAnimalID.Owner = this;
                PETxAnimalID.OwnerID = ID;
                PETxAnimalID.TableName = Name;
                PETxAnimalID.Alias = "PETxAnimalID";
                Items.Add(ERPxSexoID, ERPxSexoID.ID);
                ERPxSexoID.Owner = this;
                ERPxSexoID.OwnerID = ID;
                ERPxSexoID.TableName = Name;
                ERPxSexoID.Alias = "ERPxSexoID";
                Items.Add(PETxRacaID, PETxRacaID.ID);
                PETxRacaID.Owner = this;
                PETxRacaID.OwnerID = ID;
                PETxRacaID.TableName = Name;
                PETxRacaID.Alias = "PETxRacaID";
                Items.Add(PETxPelagemID, PETxPelagemID.ID);
                PETxPelagemID.Owner = this;
                PETxPelagemID.OwnerID = ID;
                PETxPelagemID.TableName = Name;
                PETxPelagemID.Alias = "PETxPelagemID";
                Items.Add(SYSxEstadoID, SYSxEstadoID.ID);
                SYSxEstadoID.Owner = this;
                SYSxEstadoID.OwnerID = ID;
                SYSxEstadoID.TableName = Name;
                SYSxEstadoID.Alias = "SYSxEstadoID";
                Items.Add(Nascimento, Nascimento.ID);
                Nascimento.Owner = this;
                Nascimento.OwnerID = ID;
                Nascimento.TableName = Name;
                Nascimento.Alias = "Nascimento";
                Items.Add(Nome, Nome.ID);
                Nome.Owner = this;
                Nome.OwnerID = ID;
                Nome.TableName = Name;
                Nome.Alias = "Nome";
                Items.Add(PETxPorteID, PETxPorteID.ID);
                PETxPorteID.Owner = this;
                PETxPorteID.OwnerID = ID;
                PETxPorteID.TableName = Name;
                PETxPorteID.Alias = "PETxPorteID";
                Items.Add(Observacao, Observacao.ID);
                Observacao.Owner = this;
                Observacao.OwnerID = ID;
                Observacao.TableName = Name;
                Observacao.Alias = "Observacao";
                Items.Add(Cor, Cor.ID);
                Cor.Owner = this;
                Cor.OwnerID = ID;
                Cor.TableName = Name;
                Cor.Alias = "Cor";
            }

            public static XORMFaceField PETxAnimalID = new XORMFaceField(global::Projecao.Core.PET.DB.PETx.PETxAnimal.PETxAnimalID, new Guid("26650CF8-D4F2-4339-9939-54D2A9A4019A"), "PETxAnimalID", "PET");
            public static XORMFKField ERPxSexoID = new XORMFKField(global::Projecao.Core.PET.DB.PETx.PETxAnimal.ERPxSexoID, new Guid("47F4A86F-1BB7-49BC-9500-0DAF21DA9603"), "ERPxSexoID", "Sexo");
            public static XORMFKField PETxRacaID = new XORMFKField(global::Projecao.Core.PET.DB.PETx.PETxAnimal.PETxRacaID, new Guid("47496CFD-5A2A-4E76-9022-C957A8C8DC29"), "PETxRacaID", "Raça");
            public static XORMFKField PETxPelagemID = new XORMFKField(global::Projecao.Core.PET.DB.PETx.PETxAnimal.PETxPelagemID, new Guid("BB38E131-0C4D-45A5-9886-1F1BB1960269"), "PETxPelagemID", "Pelagem");
            public static XORMStateField SYSxEstadoID = new XORMStateField(global::Projecao.Core.PET.DB.PETx.PETxAnimal.SYSxEstadoID, new Guid("A487D97B-0672-4F88-9568-DA6EC119CFF0"), "SYSxEstadoID", "Estado");
            public static XORMDateTimeField Nascimento = new XORMDateTimeField(global::Projecao.Core.PET.DB.PETx.PETxAnimal.Nascimento, new Guid("40FB4AFD-9346-482B-93F5-8A59028D6987"), "Nascimento", "Nascimento");
            public static XORMField Nome = new XORMField(global::Projecao.Core.PET.DB.PETx.PETxAnimal.Nome, new Guid("E585E902-3B9F-4555-A9DB-400BB537DC0F"), "Nome", "Nome");
            public static XORMFKField PETxPorteID = new XORMFKField(global::Projecao.Core.PET.DB.PETx.PETxAnimal.PETxPorteID, new Guid("583693FF-3723-49EF-89B3-E807B56A6C27"), "PETxPorteID", "Porte");
            public static XORMField Observacao = new XORMField(global::Projecao.Core.PET.DB.PETx.PETxAnimal.Observacao, new Guid("C9D8F5C6-4253-46A5-BD65-245167AA643A"), "Observacao", "Observação");
            public static XORMField Cor = new XORMField(global::Projecao.Core.PET.DB.PETx.PETxAnimal.Cor, new Guid("C197B820-01B2-435B-BFF5-894B01E55E82"), "Cor", "Cor");
        }
        #endregion xPETxAnimal 


        #region xPETxPorte 
        public class xPETxPorte : XSVCTable
        {

            public static Guid gCID => new Guid("16118FA9-ED92-43FB-BFB7-2FD58C29029F");

            public xPETxPorte()
            {
                Name = "PETxPorte";
                Alias = "PETxPorte";
                ID = gCID;
                ParentID =  global::Projecao.Core.PET.DB.PETx.PETxPorte.gCID;

                Items.Add(Porte, Porte.ID);
                Porte.Owner = this;
                Porte.OwnerID = ID;
                Porte.TableName = Name;
                Porte.Alias = "Porte";
                Items.Add(PETxPorteID, PETxPorteID.ID);
                PETxPorteID.Owner = this;
                PETxPorteID.OwnerID = ID;
                PETxPorteID.TableName = Name;
            }

            public static XORMFaceField Porte = new XORMFaceField(global::Projecao.Core.PET.DB.PETx.PETxPorte.Porte, new Guid("EA55AF93-CF83-4330-BB73-53DACF95D238"), "Porte", "Porte");
            public static XORMPKField PETxPorteID = new XORMPKField(global::Projecao.Core.PET.DB.PETx.PETxPorte.PETxPorteID, new Guid("71A0FFA3-0450-4CDE-91F8-076F0EEC8B20"), "PETxPorteID", "Porte");
        }
        #endregion xPETxPorte 


        #region xPETxRaca 
        public class xPETxRaca : XSVCTable
        {

            public static Guid gCID => new Guid("23261C67-26BD-4C0D-B8DC-EB11BA60ACC3");

            public xPETxRaca()
            {
                Name = "PETxRaca";
                Alias = "PETxRaca";
                ID = gCID;
                ParentID =  global::Projecao.Core.PET.DB.PETx.PETxRaca.gCID;

                Items.Add(PETxRacaID, PETxRacaID.ID);
                PETxRacaID.Owner = this;
                PETxRacaID.OwnerID = ID;
                PETxRacaID.TableName = Name;
                Items.Add(PETxFamiliaID, PETxFamiliaID.ID);
                PETxFamiliaID.Owner = this;
                PETxFamiliaID.OwnerID = ID;
                PETxFamiliaID.TableName = Name;
                Items.Add(Raca, Raca.ID);
                Raca.Owner = this;
                Raca.OwnerID = ID;
                Raca.TableName = Name;
                Raca.Alias = "Raca";
            }

            public static XORMPKField PETxRacaID = new XORMPKField(global::Projecao.Core.PET.DB.PETx.PETxRaca.PETxRacaID, new Guid("BAE4F6B8-9434-4663-A0BE-AF12F962EE9A"), "PETxRacaID", "Raça");
            public static XORMFKField PETxFamiliaID = new XORMFKField(global::Projecao.Core.PET.DB.PETx.PETxRaca.PETxFamiliaID, new Guid("7C61328B-7D93-4331-8D3C-17529C4C2762"), "PETxFamiliaID", "Família");
            public static XORMFaceField Raca = new XORMFaceField(global::Projecao.Core.PET.DB.PETx.PETxRaca.Raca, new Guid("F4CADBBB-9206-488F-AA2C-3A2635561A86"), "Raca", "Raça");
        }
        #endregion xPETxRaca 


        #region xPETxAnimalTutor 
        public class xPETxAnimalTutor : XSVCTable
        {

            public static Guid gCID => new Guid("4166187C-E351-4643-B6E7-66F69F2B9242");

            public xPETxAnimalTutor()
            {
                Name = "PETxAnimalTutor";
                Alias = "PETxAnimalTutor";
                ID = gCID;
                ParentID =  global::Projecao.Core.PET.DB.PETx.PETxAnimalTutor.gCID;

                Items.Add(PETxTutorID, PETxTutorID.ID);
                PETxTutorID.Owner = this;
                PETxTutorID.OwnerID = ID;
                PETxTutorID.TableName = Name;
                PETxTutorID.Alias = "PETxTutorID";
                Items.Add(PETxAnimalID, PETxAnimalID.ID);
                PETxAnimalID.Owner = this;
                PETxAnimalID.OwnerID = ID;
                PETxAnimalID.TableName = Name;
                Items.Add(PETxAnimalTutorID, PETxAnimalTutorID.ID);
                PETxAnimalTutorID.Owner = this;
                PETxAnimalTutorID.OwnerID = ID;
                PETxAnimalTutorID.TableName = Name;
                PETxAnimalTutorID.Alias = "PETxAnimalTutorID";
                Items.Add(SYSxEstadoID, SYSxEstadoID.ID);
                SYSxEstadoID.Owner = this;
                SYSxEstadoID.OwnerID = ID;
                SYSxEstadoID.TableName = Name;
            }

            public static XORMFKField PETxTutorID = new XORMFKField(global::Projecao.Core.PET.DB.PETx.PETxAnimalTutor.PETxTutorID, new Guid("D49FF2BA-20E4-417F-8C5F-4644BDC09C39"), "PETxTutorID", "Tutor");
            public static XORMFKField PETxAnimalID = new XORMFKField(global::Projecao.Core.PET.DB.PETx.PETxAnimalTutor.PETxAnimalID, new Guid("E0C97FE8-46C1-4C5E-B9D5-5F4D4C85F612"), "PETxAnimalID", "PET");
            public static XORMFaceField PETxAnimalTutorID = new XORMFaceField(global::Projecao.Core.PET.DB.PETx.PETxAnimalTutor.PETxAnimalTutorID, new Guid("64A95B65-3854-494F-ABF1-CB4043152085"), "PETxAnimalTutorID", "PETs por Tutor");
            public static XORMStateField SYSxEstadoID = new XORMStateField(global::Projecao.Core.PET.DB.PETx.PETxAnimalTutor.SYSxEstadoID, new Guid("FF53A29B-BDEA-4F8C-8048-588C2F72D895"), "SYSxEstadoID", "Estado");
        }
        #endregion xPETxAnimalTutor 


        #region xPETxPelagem 
        public class xPETxPelagem : XSVCTable
        {

            public static Guid gCID => new Guid("4A2A6114-F6AF-47DD-A160-DE847005D248");

            public xPETxPelagem()
            {
                Name = "PETxPelagem";
                Alias = "PETxPelagem";
                ID = gCID;
                ParentID =  global::Projecao.Core.PET.DB.PETx.PETxPelagem.gCID;

                Items.Add(PETxPelagemID, PETxPelagemID.ID);
                PETxPelagemID.Owner = this;
                PETxPelagemID.OwnerID = ID;
                PETxPelagemID.TableName = Name;
                Items.Add(Pelagem, Pelagem.ID);
                Pelagem.Owner = this;
                Pelagem.OwnerID = ID;
                Pelagem.TableName = Name;
                Pelagem.Alias = "Pelagem";
            }

            public static XORMPKField PETxPelagemID = new XORMPKField(global::Projecao.Core.PET.DB.PETx.PETxPelagem.PETxPelagemID, new Guid("88CE39EA-F96A-4363-A523-BD65A55E5A16"), "PETxPelagemID", "Pelagem");
            public static XORMFaceField Pelagem = new XORMFaceField(global::Projecao.Core.PET.DB.PETx.PETxPelagem.Pelagem, new Guid("7969D082-BC8F-4456-AD99-19D115E4CF5D"), "Pelagem", "Pelagem");
        }
        #endregion xPETxPelagem 


        #region xPETxFamilia 
        public class xPETxFamilia : XSVCTable
        {

            public static Guid gCID => new Guid("861B3A6B-221A-44DF-A0C1-4F9E81DDDFC2");

            public xPETxFamilia()
            {
                Name = "PETxFamilia";
                Alias = "PETxFamilia";
                ID = gCID;
                ParentID =  global::Projecao.Core.PET.DB.PETx.PETxFamilia.gCID;

                Items.Add(Familia, Familia.ID);
                Familia.Owner = this;
                Familia.OwnerID = ID;
                Familia.TableName = Name;
                Familia.Alias = "Familia";
                Items.Add(PETxFamiliaID, PETxFamiliaID.ID);
                PETxFamiliaID.Owner = this;
                PETxFamiliaID.OwnerID = ID;
                PETxFamiliaID.TableName = Name;
            }

            public static XORMFaceField Familia = new XORMFaceField(global::Projecao.Core.PET.DB.PETx.PETxFamilia.Familia, new Guid("35518737-E286-4E20-9FE9-150E90B4EE6A"), "Familia", "Família");
            public static XORMPKField PETxFamiliaID = new XORMPKField(global::Projecao.Core.PET.DB.PETx.PETxFamilia.PETxFamiliaID, new Guid("3118315A-2D41-4855-8293-30189BE720E7"), "PETxFamiliaID", "Família");
        }
        #endregion xPETxFamilia 


        public xERPxGenero ERPxGenero;
        public xPETxAnimal PETxAnimal;
        public xPETxAnimalTutor PETxAnimalTutor;
        public xPETxFamilia PETxFamilia;
        public xPETxPelagem PETxPelagem;
        public xPETxPorte PETxPorte;
        public xPETxRaca PETxRaca;

        public AnimalSVC()
        {
            TupleType = typeof(AnimalSVC.XTuple);
            DataSetType = typeof(AnimalSVC.XDataSet);
            ServiceRuleCID = new Guid("266D3B55-E31F-4A29-B6C7-142ABAB21191");
            OnlyActives = false;
            Actions = XSVCAction.All;
            Type = XServiceType.Default;
            ID = new Guid("0AF54CE8-D142-4BC6-AC86-03FB95EBC282");
            Name = "Animal";
            Title = "PET";
            IsCacheable = false;
            CompanyControl = false;
            IsJob = false;
            AutoLoad = true;
            FreeForUsers = false;
            ServerSideNewRecord = false;
            UseDistinct = false;
            CheckTenant = true;
            JobType = XJobType.Default;
            ModuleID = new Guid("E3D05D28-7014-4B59-9CB6-C283BEEFDB82");
            Rights = new Int16[] { 1, 2, 3, 4, 5, 6, 7 }; 
            FilterFormID = new Guid("4F717469-591F-42D7-8411-FB5C9A2926DB");
            IsReadOnly = false;
            ReferenceScripts = new String[] { "TFX.Core.Service.js", "Projecao.Core.CEP.js", "Projecao.Core.ERP.js", "Projecao.Core.IMC.js", "Projecao.Core.ISE.js", "Projecao.Core.PET.js" };
            GridFields = new Guid[] { xPETxAnimal.Nome.ID, xERPxGenero.Designacao.ID, xPETxAnimal.Cor.ID, xPETxFamilia.Familia.ID, xPETxRaca.Raca.ID, xPETxAnimal.SYSxEstadoID.ID };
            OrderByFields = new Guid[] { xPETxAnimal.Nome.ID };
            DataSetFields = new Guid[] { xERPxGenero.Genero.ID, xERPxGenero.Designacao.ID, xPETxAnimal.Cor.ID, xPETxAnimal.ERPxSexoID.ID, xPETxAnimal.Nascimento.ID, xPETxAnimal.Nome.ID, xPETxAnimal.PETxAnimalID.ID, xPETxAnimal.PETxPelagemID.ID, xPETxAnimal.PETxPorteID.ID, xPETxAnimal.PETxRacaID.ID, xPETxAnimal.Observacao.ID, xPETxAnimal.SYSxEstadoID.ID, xPETxAnimalTutor.PETxAnimalTutorID.ID, xPETxAnimalTutor.PETxTutorID.ID, xPETxFamilia.Familia.ID, xPETxPelagem.Pelagem.ID, xPETxPorte.Porte.ID, xPETxRaca.Raca.ID };
            PKField = xPETxAnimal.PETxAnimalID.ID;
            ConfigTableID = new Guid("01301E20-761A-4FBD-BAB5-706F923D01C4");
            StateField = xPETxAnimal.SYSxEstadoID.ID;
            MasterRuleCID = new Guid("266D3B55-E31F-4A29-B6C7-142ABAB21191");
            ERPxGenero = new xERPxGenero();
            ERPxGenero.IsReadOnly = true;
            AddTable(ERPxGenero);
            PETxAnimal = new xPETxAnimal();
            PETxAnimal.IsReadOnly = false;
            AddTable(PETxAnimal);
            PETxAnimalTutor = new xPETxAnimalTutor();
            PETxAnimalTutor.IsReadOnly = false;
            AddTable(PETxAnimalTutor);
            PETxFamilia = new xPETxFamilia();
            PETxFamilia.IsReadOnly = true;
            AddTable(PETxFamilia);
            PETxPelagem = new xPETxPelagem();
            PETxPelagem.IsReadOnly = true;
            AddTable(PETxPelagem);
            PETxPorte = new xPETxPorte();
            PETxPorte.IsReadOnly = true;
            AddTable(PETxPorte);
            PETxRaca = new xPETxRaca();
            PETxRaca.IsReadOnly = true;
            AddTable(PETxRaca);
            MasterTableID = PETxAnimal.ID;
            PETxPorte_PETxPorteID_PETxAnimal_PETxPorteID = AddReference(new XSVCReference(new Guid("319459F7-6975-43AE-A30B-056FE110124D"), "FK_319459F7697543AEA30B056FE110124D", AnimalSVC.xPETxPorte.gCID, xPETxPorte.PETxPorteID.ID, AnimalSVC.xPETxAnimal.gCID, xPETxAnimal.PETxPorteID.ID, XJoinType.Inner)); // PETxPorte.PETxPorteID --> PETxAnimal.PETxPorteID
            PETxAnimalTutor_PETxAnimalID_PETxAnimal_PETxAnimalID = AddReference(new XSVCReference(new Guid("3870B151-325A-4426-8C2D-33FB7081417D"), "FK_3870B151325A44268C2D33FB7081417D", AnimalSVC.xPETxAnimalTutor.gCID, xPETxAnimalTutor.PETxAnimalID.ID, AnimalSVC.xPETxAnimal.gCID, xPETxAnimal.PETxAnimalID.ID, XJoinType.Inner)); // PETxAnimalTutor.PETxAnimalID --> PETxAnimal.PETxAnimalID
            PETxRaca_PETxRacaID_PETxAnimal_PETxRacaID = AddReference(new XSVCReference(new Guid("39833097-A9A5-41E5-A586-E817718244A0"), "FK_39833097A9A541E5A586E817718244A0", AnimalSVC.xPETxRaca.gCID, xPETxRaca.PETxRacaID.ID, AnimalSVC.xPETxAnimal.gCID, xPETxAnimal.PETxRacaID.ID, XJoinType.Inner)); // PETxRaca.PETxRacaID --> PETxAnimal.PETxRacaID
            ERPxGenero_ERPxGeneroID_PETxAnimal_ERPxSexoID = AddReference(new XSVCReference(new Guid("70B09DF9-8881-4C7A-AD9E-DE5BA58042FA"), "FK_70B09DF988814C7AAD9EDE5BA58042FA", AnimalSVC.xERPxGenero.gCID, xERPxGenero.ERPxGeneroID.ID, AnimalSVC.xPETxAnimal.gCID, xPETxAnimal.ERPxSexoID.ID, XJoinType.Inner)); // ERPxGenero.ERPxGeneroID --> PETxAnimal.ERPxSexoID
            PETxFamilia_PETxFamiliaID_PETxRaca_PETxFamiliaID = AddReference(new XSVCReference(new Guid("E672BA27-78CB-4F2D-A2F3-97F76524DFFF"), "FK_E672BA2778CB4F2DA2F397F76524DFFF", AnimalSVC.xPETxFamilia.gCID, xPETxFamilia.PETxFamiliaID.ID, AnimalSVC.xPETxRaca.gCID, xPETxRaca.PETxFamiliaID.ID, XJoinType.Inner)); // PETxFamilia.PETxFamiliaID --> PETxRaca.PETxFamiliaID
            PETxPelagem_PETxPelagemID_PETxAnimal_PETxPelagemID = AddReference(new XSVCReference(new Guid("F6295364-870A-4ADD-A409-8CE8CC79CFF2"), "FK_F6295364870A4ADDA4098CE8CC79CFF2", AnimalSVC.xPETxPelagem.gCID, xPETxPelagem.PETxPelagemID.ID, AnimalSVC.xPETxAnimal.gCID, xPETxAnimal.PETxPelagemID.ID, XJoinType.Inner)); // PETxPelagem.PETxPelagemID --> PETxAnimal.PETxPelagemID
            xPETxAnimal.Cor.Length = 15;
            xPETxAnimal.Cor.IsDataField = true;
            xPETxAnimal.Cor.AllowEmpty = true;
            xERPxGenero.Designacao.IsReadOnly = true;
            xERPxGenero.Designacao.Length = 20;
            xERPxGenero.Designacao.IsDataField = true;
            xERPxGenero.Designacao.AllowEmpty = true;
            xPETxAnimal.ERPxSexoID.IsDataField = true;
            xPETxAnimal.ERPxSexoID.AllowEmpty = true;
            xPETxFamilia.Familia.IsReadOnly = true;
            xPETxFamilia.Familia.Length = 25;
            xPETxFamilia.Familia.IsDataField = true;
            xPETxFamilia.Familia.AllowEmpty = true;
            xERPxGenero.Genero.IsReadOnly = true;
            xERPxGenero.Genero.Length = 15;
            xERPxGenero.Genero.IsDataField = true;
            xERPxGenero.Genero.AllowEmpty = true;
            xPETxAnimal.Nascimento.Mask = "dd/MM/yyyy";
            xPETxAnimal.Nascimento.IsDataField = true;
            xPETxAnimal.Nascimento.IsVariable = true;
            xPETxAnimal.Nascimento.AllowEmpty = true;
            xPETxAnimal.Nome.OrderType = XOrderType.Asc;
            xPETxAnimal.Nome.Length = 60;
            xPETxAnimal.Nome.IsDataField = true;
            xPETxAnimal.Nome.IsVariable = true;
            xPETxAnimal.Nome.AllowEmpty = true;
            xPETxAnimal.Observacao.IsDataField = true;
            xPETxAnimal.Observacao.AllowEmpty = true;
            xPETxPelagem.Pelagem.IsReadOnly = true;
            xPETxPelagem.Pelagem.Length = 20;
            xPETxPelagem.Pelagem.IsDataField = true;
            xPETxPelagem.Pelagem.AllowEmpty = true;
            xPETxAnimal.PETxAnimalID.GeneratePK = true;
            xPETxAnimal.PETxAnimalID.IsDataField = true;
            xPETxAnimal.PETxAnimalID.AllowEmpty = true;
            xPETxAnimalTutor.PETxAnimalTutorID.GeneratePK = true;
            xPETxAnimalTutor.PETxAnimalTutorID.IsDataField = true;
            xPETxAnimalTutor.PETxAnimalTutorID.AllowEmpty = true;
            xPETxAnimal.PETxPelagemID.IsDataField = true;
            xPETxAnimal.PETxPelagemID.AllowEmpty = true;
            xPETxAnimal.PETxPorteID.IsDataField = true;
            xPETxAnimal.PETxPorteID.AllowEmpty = true;
            xPETxAnimal.PETxRacaID.IsDataField = true;
            xPETxAnimal.PETxRacaID.AllowEmpty = true;
            xPETxAnimalTutor.PETxTutorID.IsDataField = true;
            xPETxAnimalTutor.PETxTutorID.AllowEmpty = true;
            xPETxPorte.Porte.IsReadOnly = true;
            xPETxPorte.Porte.Length = 25;
            xPETxPorte.Porte.IsDataField = true;
            xPETxPorte.Porte.AllowEmpty = true;
            xPETxRaca.Raca.IsReadOnly = true;
            xPETxRaca.Raca.Length = 48;
            xPETxRaca.Raca.IsDataField = true;
            xPETxRaca.Raca.IsVariable = true;
            xPETxRaca.Raca.AllowEmpty = true;
            xPETxAnimal.SYSxEstadoID.IsDataField = true;
            xPETxAnimal.SYSxEstadoID.AllowEmpty = true;
            xPETxAnimal.Cor.DefaultValue = @"Própria da Raça";
            xPETxAnimal.SYSxEstadoID.DefaultValue = (Int16)1;
        }

        #region XFields

        public class XFields
        {
        public XORMField Cor => xPETxAnimal.Cor;
        public XORMField Designacao => xERPxGenero.Designacao;
        public XORMField ERPxSexoID => xPETxAnimal.ERPxSexoID;
        public XORMField Familia => xPETxFamilia.Familia;
        public XORMField Genero => xERPxGenero.Genero;
        public XORMField Nascimento => xPETxAnimal.Nascimento;
        public XORMField Nome => xPETxAnimal.Nome;
        public XORMField Observacao => xPETxAnimal.Observacao;
        public XORMField Pelagem => xPETxPelagem.Pelagem;
        public XORMField PETxAnimalID => xPETxAnimal.PETxAnimalID;
        public XORMField PETxAnimalTutorID => xPETxAnimalTutor.PETxAnimalTutorID;
        public XORMField PETxPelagemID => xPETxAnimal.PETxPelagemID;
        public XORMField PETxPorteID => xPETxAnimal.PETxPorteID;
        public XORMField PETxRacaID => xPETxAnimal.PETxRacaID;
        public XORMField PETxTutorID => xPETxAnimalTutor.PETxTutorID;
        public XORMField Porte => xPETxPorte.Porte;
        public XORMField Raca => xPETxRaca.Raca;
        public XORMField SYSxEstadoID => xPETxAnimal.SYSxEstadoID;
        }
        #endregion XFields
        #region AnimalSVC.XTuple

        public  class XTuple : XDataTuple
        {

            public XTuple()
            {
            }

            public XTuple(Object[] pSource)
                : base(pSource)
            {
            }

            public XTuple(Int32 pColCount)
               : this(new Object[pColCount])
            {
            }

            public readonly XFields Fields = new XFields();

            #nullable enable

        public String Cor
        {
            get
            {
                return (String)Value[AnimalSVC.xPETxAnimal.Cor.ID];
            }
            set
            {
                Value[AnimalSVC.xPETxAnimal.Cor.ID] = value;
            }
        }
        public String? oCor
        {
            get
            {
                GetOldValue(AnimalSVC.xPETxAnimal.Cor, out Object ovlr);
                return (String?)ovlr;
            }
        }

        public String Designacao
        {
            get
            {
                return (String)Value[AnimalSVC.xERPxGenero.Designacao.ID];
            }
            set
            {
                Value[AnimalSVC.xERPxGenero.Designacao.ID] = value;
            }
        }
        public String? oDesignacao
        {
            get
            {
                GetOldValue(AnimalSVC.xERPxGenero.Designacao, out Object ovlr);
                return (String?)ovlr;
            }
        }

        public Int16 ERPxSexoID
        {
            get
            {
                return (Int16)Value[AnimalSVC.xPETxAnimal.ERPxSexoID.ID];
            }
            set
            {
                Value[AnimalSVC.xPETxAnimal.ERPxSexoID.ID] = value;
            }
        }
        public Int16? oERPxSexoID
        {
            get
            {
                GetOldValue(AnimalSVC.xPETxAnimal.ERPxSexoID, out Object ovlr);
                return (Int16?)ovlr;
            }
        }

        public String Familia
        {
            get
            {
                return (String)Value[AnimalSVC.xPETxFamilia.Familia.ID];
            }
            set
            {
                Value[AnimalSVC.xPETxFamilia.Familia.ID] = value;
            }
        }
        public String? oFamilia
        {
            get
            {
                GetOldValue(AnimalSVC.xPETxFamilia.Familia, out Object ovlr);
                return (String?)ovlr;
            }
        }

        public String Genero
        {
            get
            {
                return (String)Value[AnimalSVC.xERPxGenero.Genero.ID];
            }
            set
            {
                Value[AnimalSVC.xERPxGenero.Genero.ID] = value;
            }
        }
        public String? oGenero
        {
            get
            {
                GetOldValue(AnimalSVC.xERPxGenero.Genero, out Object ovlr);
                return (String?)ovlr;
            }
        }

        public DateTime Nascimento
        {
            get
            {
                return (DateTime)Value[AnimalSVC.xPETxAnimal.Nascimento.ID];
            }
            set
            {
                Value[AnimalSVC.xPETxAnimal.Nascimento.ID] = value;
            }
        }
        public DateTime? oNascimento
        {
            get
            {
                GetOldValue(AnimalSVC.xPETxAnimal.Nascimento, out Object ovlr);
                return (DateTime?)ovlr;
            }
        }

        public String Nome
        {
            get
            {
                return (String)Value[AnimalSVC.xPETxAnimal.Nome.ID];
            }
            set
            {
                Value[AnimalSVC.xPETxAnimal.Nome.ID] = value;
            }
        }
        public String? oNome
        {
            get
            {
                GetOldValue(AnimalSVC.xPETxAnimal.Nome, out Object ovlr);
                return (String?)ovlr;
            }
        }

        public String Observacao
        {
            get
            {
                return (String)Value[AnimalSVC.xPETxAnimal.Observacao.ID];
            }
            set
            {
                Value[AnimalSVC.xPETxAnimal.Observacao.ID] = value;
            }
        }
        public String? oObservacao
        {
            get
            {
                GetOldValue(AnimalSVC.xPETxAnimal.Observacao, out Object ovlr);
                return (String?)ovlr;
            }
        }

        public String Pelagem
        {
            get
            {
                return (String)Value[AnimalSVC.xPETxPelagem.Pelagem.ID];
            }
            set
            {
                Value[AnimalSVC.xPETxPelagem.Pelagem.ID] = value;
            }
        }
        public String? oPelagem
        {
            get
            {
                GetOldValue(AnimalSVC.xPETxPelagem.Pelagem, out Object ovlr);
                return (String?)ovlr;
            }
        }

        public Guid PETxAnimalID
        {
            get
            {
                return (Guid)Value[AnimalSVC.xPETxAnimal.PETxAnimalID.ID];
            }
            set
            {
                Value[AnimalSVC.xPETxAnimal.PETxAnimalID.ID] = value;
            }
        }
        public Guid? oPETxAnimalID
        {
            get
            {
                GetOldValue(AnimalSVC.xPETxAnimal.PETxAnimalID, out Object ovlr);
                return (Guid?)ovlr;
            }
        }

        public Guid PETxAnimalTutorID
        {
            get
            {
                return (Guid)Value[AnimalSVC.xPETxAnimalTutor.PETxAnimalTutorID.ID];
            }
            set
            {
                Value[AnimalSVC.xPETxAnimalTutor.PETxAnimalTutorID.ID] = value;
            }
        }
        public Guid? oPETxAnimalTutorID
        {
            get
            {
                GetOldValue(AnimalSVC.xPETxAnimalTutor.PETxAnimalTutorID, out Object ovlr);
                return (Guid?)ovlr;
            }
        }

        public Int16 PETxPelagemID
        {
            get
            {
                return (Int16)Value[AnimalSVC.xPETxAnimal.PETxPelagemID.ID];
            }
            set
            {
                Value[AnimalSVC.xPETxAnimal.PETxPelagemID.ID] = value;
            }
        }
        public Int16? oPETxPelagemID
        {
            get
            {
                GetOldValue(AnimalSVC.xPETxAnimal.PETxPelagemID, out Object ovlr);
                return (Int16?)ovlr;
            }
        }

        public Int16 PETxPorteID
        {
            get
            {
                return (Int16)Value[AnimalSVC.xPETxAnimal.PETxPorteID.ID];
            }
            set
            {
                Value[AnimalSVC.xPETxAnimal.PETxPorteID.ID] = value;
            }
        }
        public Int16? oPETxPorteID
        {
            get
            {
                GetOldValue(AnimalSVC.xPETxAnimal.PETxPorteID, out Object ovlr);
                return (Int16?)ovlr;
            }
        }

        public Int16 PETxRacaID
        {
            get
            {
                return (Int16)Value[AnimalSVC.xPETxAnimal.PETxRacaID.ID];
            }
            set
            {
                Value[AnimalSVC.xPETxAnimal.PETxRacaID.ID] = value;
            }
        }
        public Int16? oPETxRacaID
        {
            get
            {
                GetOldValue(AnimalSVC.xPETxAnimal.PETxRacaID, out Object ovlr);
                return (Int16?)ovlr;
            }
        }

        public Guid PETxTutorID
        {
            get
            {
                return (Guid)Value[AnimalSVC.xPETxAnimalTutor.PETxTutorID.ID];
            }
            set
            {
                Value[AnimalSVC.xPETxAnimalTutor.PETxTutorID.ID] = value;
            }
        }
        public Guid? oPETxTutorID
        {
            get
            {
                GetOldValue(AnimalSVC.xPETxAnimalTutor.PETxTutorID, out Object ovlr);
                return (Guid?)ovlr;
            }
        }

        public String Porte
        {
            get
            {
                return (String)Value[AnimalSVC.xPETxPorte.Porte.ID];
            }
            set
            {
                Value[AnimalSVC.xPETxPorte.Porte.ID] = value;
            }
        }
        public String? oPorte
        {
            get
            {
                GetOldValue(AnimalSVC.xPETxPorte.Porte, out Object ovlr);
                return (String?)ovlr;
            }
        }

        public String Raca
        {
            get
            {
                return (String)Value[AnimalSVC.xPETxRaca.Raca.ID];
            }
            set
            {
                Value[AnimalSVC.xPETxRaca.Raca.ID] = value;
            }
        }
        public String? oRaca
        {
            get
            {
                GetOldValue(AnimalSVC.xPETxRaca.Raca, out Object ovlr);
                return (String?)ovlr;
            }
        }

        public Int16 SYSxEstadoID
        {
            get
            {
                return (Int16)Value[AnimalSVC.xPETxAnimal.SYSxEstadoID.ID];
            }
            set
            {
                Value[AnimalSVC.xPETxAnimal.SYSxEstadoID.ID] = value;
            }
        }
        public Int16? oSYSxEstadoID
        {
            get
            {
                GetOldValue(AnimalSVC.xPETxAnimal.SYSxEstadoID, out Object ovlr);
                return (Int16?)ovlr;
            }
        }

            #nullable disable
        }
        #endregion AnimalSVC.XTuple

        #region AnimalSVC.XDataSet

        public class XDataSet : XDataSet<AnimalSVC.XTuple>
        {
            public XDataSet()
            {
                DataSetType = typeof(AnimalSVC.XDataSet);
            }
        }

        public class XDataSet<T> : XServiceDataSet<AnimalSVC.XTuple> where T : XDataTuple
        {

            public class xFLDs{
                public Guid Cor => AnimalSVC.xPETxAnimal.Cor.ID;
                public Guid Designacao => AnimalSVC.xERPxGenero.Designacao.ID;
                public Guid ERPxSexoID => AnimalSVC.xPETxAnimal.ERPxSexoID.ID;
                public Guid Familia => AnimalSVC.xPETxFamilia.Familia.ID;
                public Guid Genero => AnimalSVC.xERPxGenero.Genero.ID;
                public Guid Nascimento => AnimalSVC.xPETxAnimal.Nascimento.ID;
                public Guid Nome => AnimalSVC.xPETxAnimal.Nome.ID;
                public Guid Observacao => AnimalSVC.xPETxAnimal.Observacao.ID;
                public Guid Pelagem => AnimalSVC.xPETxPelagem.Pelagem.ID;
                public Guid PETxAnimalID => AnimalSVC.xPETxAnimal.PETxAnimalID.ID;
                public Guid PETxAnimalTutorID => AnimalSVC.xPETxAnimalTutor.PETxAnimalTutorID.ID;
                public Guid PETxPelagemID => AnimalSVC.xPETxAnimal.PETxPelagemID.ID;
                public Guid PETxPorteID => AnimalSVC.xPETxAnimal.PETxPorteID.ID;
                public Guid PETxRacaID => AnimalSVC.xPETxAnimal.PETxRacaID.ID;
                public Guid PETxTutorID => AnimalSVC.xPETxAnimalTutor.PETxTutorID.ID;
                public Guid Porte => AnimalSVC.xPETxPorte.Porte.ID;
                public Guid Raca => AnimalSVC.xPETxRaca.Raca.ID;
                public Guid SYSxEstadoID => AnimalSVC.xPETxAnimal.SYSxEstadoID.ID;
            }

            public xFLDs FLDs = new xFLDs();

            public XDataSet()
            {
                DataSetType = typeof(AnimalSVC.XDataSet);
            }

        }
        #endregion AnimalSVC.XDataSet
        #if !OnlyDef
        #region AnimalSVC.XRule
        public abstract class XRule : XServiceRule<AnimalSVC.XDataSet, AnimalSVC, AnimalSVC.XTuple>
        {
        }
        #endregion AnimalSVC.XRule

        [Guid(AnimalSVC.sCID)]
        public  interface XService : XIBaseService
        {
            new XDataSet DataSet
            {
                get;
            }
            new XTuple NewTuple(Object pPKValue = null);
             IEnumerable<XTuple> Tuples
            {
                get;
            }
             XTuple Current
            {
                get;
            }
            new XDataSet Get(XServiceData pData);
             XDataSet Get(params Object[] pWhere);
        }
        [XRegister(typeof(_Service), _Service.sCID, typeof(AnimalSVC))]
        protected class _Service : Service<AnimalSVC, XDataSet, XTuple>
        {
            public const String sCID = "C524B303-F146-4DE5-A9FC-BDDF361D9052";
            public Guid gCID = new Guid(sCID);
        }

        public class Service<TModel, TDataSet, TTuple> : XBaseService<AnimalSVC, XDataSet, XTuple>, XService
             where TModel : AnimalSVC, new()
             where TDataSet : XDataSet, new()
             where TTuple : XTuple
        {
            XDataSet XService.DataSet => (XDataSet)DataSet;
            XTuple XService.NewTuple(Object pPKValue)
            {
                return (XTuple)NewTuple(pPKValue);
            }
            public new XDataTuple NewTuple(Object pPKValue = null)
            {
                return (XTuple)base.NewTuple(pPKValue);
            }
            IEnumerable<XTuple> XService.Tuples => (IEnumerable<XTuple>)Tuples;
            XTuple XService.Current => (XTuple )Current;
            XDataSet XService.Get(XServiceData pData)
            {
                return (XDataSet)Get(pData);
            }
            XDataSet XService.Get(params Object[] pWhere)
            {
                return (XDataSet)Get(pWhere);
            }
            public Service()
            {
                ID = gCID;
            }
        }
        #endif
    }

}