//<auto-generated/>
using System;
using TFX.Core.Data;
using System.Drawing;
using Newtonsoft.Json;
using TFX.Core.Objects;
using TFX.Core.Model.DIC;
using TFX.Core.Reflections;
using TFX.Core.Model.DIC.APP;
using TFX.Core.Model.DIC.FRM;
using TFX.Core.Model.DIC.RPT;
using TFX.Core.Model.DIC.ORM;
using TFX.Core.Model.DIC.Types;

namespace Projecao.Core.CRD.AutorizacaoWEB
{
    [XRegister(typeof(AutorizacaoWEBSAM), sCID)]
    [XDASESource(@"D:\Tootega\Source\TFX20\Modules\Projecao.Core.CRD\Projecao.Core.CRD.csproj", @"D:\Tootega\Source\TFX20\Modules\Projecao.Core.CRD\AutorizacaoWEB\AutorizacaoWEB.dssam")]
    public class AutorizacaoWEBSAM : XAPPModel
    {
        #region xAutorizacaoWEBACT

        [XRegister(typeof(xAutorizacaoWEBACT), sCID)]
        public class xAutorizacaoWEBACT : XAPPStep
        {
            public const String sCID = "5161C81C-BB52-41DE-8CA8-F67A9B8ED109";
            public static Guid gCID = new Guid(sCID);
            public xAutorizacaoWEBACT(Guid pID, String pName, String pTitle, Guid pFormID, Guid pDataSourceID)
              :base(pID, pName, pTitle, pFormID, pDataSourceID)
            {
            }
        }

        #endregion xAutorizacaoWEBACT

        #region AutorizacaoWEBFRM

        [XRegister(typeof(AutorizacaoWEBFRM), sCID)]
        public class AutorizacaoWEBFRM : XFRMModel
        {
            public const String sCID = "6CFA7760-3F04-4CB9-B60C-0045CBACB208";
            static AutorizacaoWEBFRM()
            {
                gCID = new Guid(sCID);
            }
            public AutorizacaoWEBFRM()
            {
                ID = gCID;
                Name = "AutorizacaoWEB";
                Title = "";
                MinRows = 2;
                ConfigCID = new Guid("00000000-0000-0000-0000-000000000000");
                ConfigPKFilter = false;
                Rect = new XRect(0, 0, 814, 2898);
                Style = XFRMStyle.Normal;
                ActionContext = XActionContext.All;
                AddItem(CRDxCartaoLogID);
                CRDxCartaoLogID.IsReadOnly = true;
                CRDxCartaoLogID.CanInsert = true;
                CRDxCartaoLogID.CanUpdate = true;
                CRDxCartaoLogID.RowCount = 1;
                CRDxCartaoLogID.ColCount = 9;
                CRDxCartaoLogID.RowCountSmall = 1;
                CRDxCartaoLogID.ColCountSmall = 9;
                CRDxCartaoLogID.IsHidden = false;
                CRDxCartaoLogID.IsHiddenSmall = false;
                CRDxCartaoLogID.AdditionalTitle = "";
                CRDxCartaoLogID.Location = 1;
                CRDxCartaoLogID.EditorCID = new Guid("6FD76216-1D13-4438-B568-72556767B3DF");
                CRDxCartaoLogID.FormImplace = true;
                CRDxCartaoLogID.Operator = XOperator.EqualTo;
                CRDxCartaoLogID.JustifyHeight = false;
                CRDxCartaoLogID.AllowEmpty = true;
                CRDxCartaoLogID.FontColor = "#000000";
                CRDxCartaoLogID.FontStyle = XFontStyle.Normal;
                CRDxCartaoLogID.ShowFooter = false;
                CRDxCartaoLogID.ViewSAM = new Guid("00000000-0000-0000-0000-000000000000");
                CRDxCartaoLogID.Scale = 0;
                CRDxCartaoLogID.Length = 0;
                CRDxCartaoLogID.SearchAction = XSearchAction.Default;
                CRDxCartaoLogID.TypeID = XInt32.CID;
                CRDxCartaoLogID.AdditionalFieldsID = new Guid[] {  };
                CRDxCartaoLogID.AdditionalDataFieldsID = new Guid[] {  };
                CRDxCartaoLogID.TargetFilterFieldID = new Guid[] {  };
                CRDxCartaoLogID.SourceFilterFieldID = new Guid[] {  };
                CRDxCartaoLogID.TargetDisplayFieldID = new Guid[] {  };
                CRDxCartaoLogID.SourceDisplayFieldID = new Guid[] {  };
                CRDxCartaoLogID.AutoLoad = false;
                CRDxCartaoLogID.FilterInative = true;
                CRDxCartaoLogID.IsAnswer = false;
                CRDxCartaoLogID.AllowMultiSelect = false;
                AddItem(Nome);
                Nome.IsReadOnly = true;
                Nome.CanInsert = true;
                Nome.CanUpdate = true;
                Nome.RowCount = 1;
                Nome.ColCount = 23;
                Nome.RowCountSmall = 1;
                Nome.ColCountSmall = 23;
                Nome.IsHidden = false;
                Nome.IsHiddenSmall = false;
                Nome.AdditionalTitle = "";
                Nome.Location = 2;
                Nome.EditorCID = new Guid("F5982E79-BA45-40FB-85E1-9F2C8B90B6EF");
                Nome.FormImplace = true;
                Nome.Operator = XOperator.EqualTo;
                Nome.JustifyHeight = false;
                Nome.AllowEmpty = true;
                Nome.FontColor = "#000000";
                Nome.FontStyle = XFontStyle.Normal;
                Nome.ShowFooter = false;
                Nome.ViewSAM = new Guid("00000000-0000-0000-0000-000000000000");
                Nome.Scale = 0;
                Nome.Length = 256;
                Nome.SearchAction = XSearchAction.Default;
                Nome.TypeID = XString.CID;
                Nome.AdditionalFieldsID = new Guid[] {  };
                Nome.AdditionalDataFieldsID = new Guid[] {  };
                Nome.TargetFilterFieldID = new Guid[] {  };
                Nome.SourceFilterFieldID = new Guid[] {  };
                Nome.TargetDisplayFieldID = new Guid[] {  };
                Nome.SourceDisplayFieldID = new Guid[] {  };
                Nome.AutoLoad = false;
                Nome.FilterInative = true;
                Nome.IsAnswer = false;
                Nome.AllowMultiSelect = false;
                AddItem(Data);
                Data.IsReadOnly = true;
                Data.CanInsert = true;
                Data.CanUpdate = true;
                Data.RowCount = 1;
                Data.ColCount = 9;
                Data.RowCountSmall = 1;
                Data.ColCountSmall = 9;
                Data.IsHidden = false;
                Data.IsHiddenSmall = false;
                Data.AdditionalTitle = "";
                Data.Location = 3;
                Data.EditorCID = new Guid("D56E8E17-9D09-4FE9-9A30-A6AA5865ABC6");
                Data.FormImplace = true;
                Data.Operator = XOperator.EqualTo;
                Data.JustifyHeight = false;
                Data.AllowEmpty = true;
                Data.FontColor = "#000000";
                Data.FontStyle = XFontStyle.Normal;
                Data.ShowFooter = false;
                Data.ViewSAM = new Guid("00000000-0000-0000-0000-000000000000");
                Data.Scale = 0;
                Data.Length = 0;
                Data.SearchAction = XSearchAction.Default;
                Data.TypeID = XDateTime.CID;
                Data.AdditionalFieldsID = new Guid[] {  };
                Data.AdditionalDataFieldsID = new Guid[] {  };
                Data.TargetFilterFieldID = new Guid[] {  };
                Data.SourceFilterFieldID = new Guid[] {  };
                Data.TargetDisplayFieldID = new Guid[] {  };
                Data.SourceDisplayFieldID = new Guid[] {  };
                Data.AutoLoad = false;
                Data.FilterInative = true;
                Data.IsAnswer = false;
                Data.AllowMultiSelect = false;
                AddItem(NumeroVenda);
                NumeroVenda.IsReadOnly = true;
                NumeroVenda.CanInsert = true;
                NumeroVenda.CanUpdate = true;
                NumeroVenda.RowCount = 1;
                NumeroVenda.ColCount = 6;
                NumeroVenda.RowCountSmall = 1;
                NumeroVenda.ColCountSmall = 6;
                NumeroVenda.IsHidden = false;
                NumeroVenda.IsHiddenSmall = false;
                NumeroVenda.AdditionalTitle = "";
                NumeroVenda.Location = 4;
                NumeroVenda.EditorCID = new Guid("F5982E79-BA45-40FB-85E1-9F2C8B90B6EF");
                NumeroVenda.FormImplace = true;
                NumeroVenda.Operator = XOperator.EqualTo;
                NumeroVenda.JustifyHeight = false;
                NumeroVenda.AllowEmpty = true;
                NumeroVenda.FontColor = "#000000";
                NumeroVenda.FontStyle = XFontStyle.Normal;
                NumeroVenda.ShowFooter = false;
                NumeroVenda.ViewSAM = new Guid("00000000-0000-0000-0000-000000000000");
                NumeroVenda.Scale = 0;
                NumeroVenda.Length = 50;
                NumeroVenda.SearchAction = XSearchAction.Default;
                NumeroVenda.TypeID = XString.CID;
                NumeroVenda.AdditionalFieldsID = new Guid[] {  };
                NumeroVenda.AdditionalDataFieldsID = new Guid[] {  };
                NumeroVenda.TargetFilterFieldID = new Guid[] {  };
                NumeroVenda.SourceFilterFieldID = new Guid[] {  };
                NumeroVenda.TargetDisplayFieldID = new Guid[] {  };
                NumeroVenda.SourceDisplayFieldID = new Guid[] {  };
                NumeroVenda.AutoLoad = false;
                NumeroVenda.FilterInative = true;
                NumeroVenda.IsAnswer = false;
                NumeroVenda.AllowMultiSelect = false;
                AddItem(Valor);
                Valor.IsReadOnly = true;
                Valor.CanInsert = true;
                Valor.CanUpdate = true;
                Valor.RowCount = 1;
                Valor.ColCount = 7;
                Valor.RowCountSmall = 1;
                Valor.ColCountSmall = 7;
                Valor.IsHidden = false;
                Valor.IsHiddenSmall = false;
                Valor.AdditionalTitle = "";
                Valor.Location = 5;
                Valor.EditorCID = new Guid("6FD76216-1D13-4438-B568-72556767B3DF");
                Valor.FormImplace = true;
                Valor.Operator = XOperator.EqualTo;
                Valor.JustifyHeight = false;
                Valor.AllowEmpty = true;
                Valor.FontColor = "#000000";
                Valor.FontStyle = XFontStyle.Normal;
                Valor.ShowFooter = false;
                Valor.ViewSAM = new Guid("00000000-0000-0000-0000-000000000000");
                Valor.Scale = 2;
                Valor.Length = 20;
                Valor.SearchAction = XSearchAction.Default;
                Valor.TypeID = XDecimal.CID;
                Valor.AdditionalFieldsID = new Guid[] {  };
                Valor.AdditionalDataFieldsID = new Guid[] {  };
                Valor.TargetFilterFieldID = new Guid[] {  };
                Valor.SourceFilterFieldID = new Guid[] {  };
                Valor.TargetDisplayFieldID = new Guid[] {  };
                Valor.SourceDisplayFieldID = new Guid[] {  };
                Valor.AutoLoad = false;
                Valor.FilterInative = true;
                Valor.IsAnswer = false;
                Valor.AllowMultiSelect = false;
                AddItem(Tipo);
                Tipo.IsReadOnly = true;
                Tipo.CanInsert = true;
                Tipo.CanUpdate = true;
                Tipo.RowCount = 1;
                Tipo.ColCount = 10;
                Tipo.RowCountSmall = 1;
                Tipo.ColCountSmall = 10;
                Tipo.IsHidden = false;
                Tipo.IsHiddenSmall = false;
                Tipo.AdditionalTitle = "";
                Tipo.Location = 6;
                Tipo.EditorCID = new Guid("F5982E79-BA45-40FB-85E1-9F2C8B90B6EF");
                Tipo.FormImplace = true;
                Tipo.Operator = XOperator.EqualTo;
                Tipo.JustifyHeight = false;
                Tipo.AllowEmpty = true;
                Tipo.FontColor = "#000000";
                Tipo.FontStyle = XFontStyle.Normal;
                Tipo.ShowFooter = false;
                Tipo.ViewSAM = new Guid("00000000-0000-0000-0000-000000000000");
                Tipo.Scale = 0;
                Tipo.Length = 54;
                Tipo.SearchAction = XSearchAction.Default;
                Tipo.TypeID = XString.CID;
                Tipo.AdditionalFieldsID = new Guid[] {  };
                Tipo.AdditionalDataFieldsID = new Guid[] {  };
                Tipo.TargetFilterFieldID = new Guid[] {  };
                Tipo.SourceFilterFieldID = new Guid[] {  };
                Tipo.TargetDisplayFieldID = new Guid[] {  };
                Tipo.SourceDisplayFieldID = new Guid[] {  };
                Tipo.AutoLoad = false;
                Tipo.FilterInative = true;
                Tipo.IsAnswer = false;
                Tipo.AllowMultiSelect = false;
            }
            public XFRMField CRDxCartaoLogID = new XFRMField(new Guid("B93EC358-969D-462E-97CC-28B93E85B0F8"), "CRDxCartaoLogID", "Número Transação", XInt32.CID, 1, 9, false, gCID, null, new Guid("84659C04-01E5-4DEB-93A5-FA7B93E42E4D")); // Int32;
            public XFRMField Nome = new XFRMField(new Guid("9575CA88-8018-4C4E-97CC-B59632A16CBE"), "Nome", "Nome do Cliente", XString.CID, 1, 23, false, gCID, null, new Guid("0494B023-EFC8-40EE-BDCE-4A0EBD4D3451")); // String;
            public XFRMField Data = new XFRMField(new Guid("7509A6F9-ED14-4D5A-8C00-2341251BEE39"), "Data", "Data Ocorrência", XDateTime.CID, 1, 9, false, gCID, null, new Guid("9050F994-2772-43B0-82CB-4B5ABE0F9FB3")); // DateTime;
            public XFRMField NumeroVenda = new XFRMField(new Guid("FAD20E18-DECD-485F-8DB5-E713BB2C1DD1"), "NumeroVenda", "Número da Venda", XString.CID, 1, 6, true, gCID, null, new Guid("9D45EC9C-F062-4541-A656-10AC6C7A7D39")); // String;
            public XFRMField Valor = new XFRMField(new Guid("C3796EC4-4CA9-4D9D-AC36-94C9CE3C7F63"), "Valor", "Valor", XDecimal.CID, 1, 7, false, gCID, null, new Guid("D9236BC3-BDF1-471A-94F6-EF9EC85B3839")); // Decimal;
            public XFRMField Tipo = new XFRMField(new Guid("F340F565-C4B7-4512-B5F6-D20CAA0AD97D"), "Tipo", "Tipo", XString.CID, 1, 10, false, gCID, null, new Guid("D0465AFB-F827-4539-BBED-B3A97DE7ECEE")); // String;
            public static class Fields
            {
                public static XFieldInfo CRDxCartaoLogID = new XFieldInfo(new Guid("B93EC358-969D-462E-97CC-28B93E85B0F8"), "CRDxCartaoLogID", "Número Transação", typeof(Int32));
                public static XFieldInfo Nome = new XFieldInfo(new Guid("9575CA88-8018-4C4E-97CC-B59632A16CBE"), "Nome", "Nome do Cliente", typeof(String));
                public static XFieldInfo Data = new XFieldInfo(new Guid("7509A6F9-ED14-4D5A-8C00-2341251BEE39"), "Data", "Data Ocorrência", typeof(DateTime));
                public static XFieldInfo NumeroVenda = new XFieldInfo(new Guid("FAD20E18-DECD-485F-8DB5-E713BB2C1DD1"), "NumeroVenda", "Número da Venda", typeof(String));
                public static XFieldInfo Valor = new XFieldInfo(new Guid("C3796EC4-4CA9-4D9D-AC36-94C9CE3C7F63"), "Valor", "Valor", typeof(Decimal));
                public static XFieldInfo Tipo = new XFieldInfo(new Guid("F340F565-C4B7-4512-B5F6-D20CAA0AD97D"), "Tipo", "Tipo", typeof(String));
            }
        }

        #endregion AutorizacaoWEBFRM

        public const String sCID = "DEBF8E6C-A850-4307-8FBD-3881C639C8D2";
        public static Guid gCID = new Guid(sCID);
        public static readonly xAutorizacaoWEBACT AutorizacaoWEBACT;

        public static Guid AutorizaVenda = new Guid("E2C515DA-C391-473C-8CCC-FB1C35D8F909");

        static AutorizacaoWEBSAM()
        {
            AutorizacaoWEBACT = new xAutorizacaoWEBACT(new Guid("5161C81C-BB52-41DE-8CA8-F67A9B8ED109"), "AutorizacaoWEBACT", "Autorização WEB", new Guid("6CFA7760-3F04-4CB9-B60C-0045CBACB208"), new Guid("00000000-0000-0000-0000-000000000000"));
        }

        public AutorizacaoWEBSAM()
        {
            ID = new Guid("DEBF8E6C-A850-4307-8FBD-3881C639C8D2");
            Name = "AutorizacaoWEB";
            Title = "Controle de Autorização";
            AppTypeID = XAppType.SAM;
            Userlevel = XUserlevel.User;
            UseTypeID = new Int16[] { 1, 2 };
            Rights = new Int16[] { 3, 6, 4, 1, 5, 2 }; 
            IsDisabled = false;
            StartAction = XStartAction.DataGrid;
            ClientScript = "Projecao.Core.CRD.js";
            Size = new Size(10, 10);
            DataSourceID = global::Projecao.Core.CRD.AutorizacaoWEB.AutorizacaoWEBSVC.gCID;
            AppModulesID = new [] { (Int16)9 };
            AppGroupsID = new [] { (Int16)2 };
            AutorizacaoWEBACT.FormID = new Guid("6CFA7760-3F04-4CB9-B60C-0045CBACB208"); 
            AutorizacaoWEBACT.Type = XActivityType.UserActivity;
            AddItem(AutorizacaoWEBACT);
        }
    }
}