<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <UserSecretsId>5f13828d-94c9-4249-8949-1859ad5dce60</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.10" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="6.1.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.10">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.22.1" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="9.0.6" />
    <PackageReference Include="System.Diagnostics.PerformanceCounter" Version="9.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Core\TFX.Core.Access\TFX.Core.Access.csproj" />
    <ProjectReference Include="..\..\Core\TFX.Core.Data\TFX.Core.Data.csproj" />
    <ProjectReference Include="..\..\Core\TFX.Core\TFX.Core.csproj" />
    <ProjectReference Include="..\..\Modules\ESC\TFX.ESC.Core\TFX.ESC.Core.csproj" />
    <ProjectReference Include="..\..\Modules\Tootega.Core.CEP\Tootega.Core.CEP.csproj" />
    <ProjectReference Include="..\..\Modules\Tootega.Core.ERP\Tootega.Core.ERP.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\AssemblyInfo.cs">
      <Visible>True</Visible>
    </Compile>
  </ItemGroup>

</Project>
