//<auto-generated/>
using System;
using System.Collections.Generic;
using TFX.Core;
using TFX.Core.Model.Cache;
using TFX.Core.Reflections;
using TFX.CIT.Core.Model;
using Projecao.Core.ERP.Empresa;
using Projecao.Core.ERP.Pessoa;

namespace Projecao.Core.ERP.Test.Empresa
{
    [XRegister(typeof(EmpresaSAMTootegaTestCIT), sCID)]
    [XDASESource(@"D:\Tootega\Source\TFX20\Modules\Projecao.Core.ERP.Test\Projecao.Core.ERP.Test.csproj", @"D:\Tootega\Source\TFX20\Modules\Projecao.Core.ERP.Test\Empresa\Empresa.SAM.Tootega.Test.dscit")]
    public class EmpresaSAMTootegaTestCIT : XCITInfo
    {
        public const String sCID = "C06E2AFE-F054-47D0-BF20-B70696BDFF50";
        public static Guid gCID = new Guid(sCID);
        public class XRule : XCITRule<EmpresaSAMTootegaTestCIT, EmpresaSVC, EmpresaSVC.XDataSet, EmpresaSVC.XTuple>
        {
        }

        public EmpresaSVC Tutor;
        public EmpresaSVC.XDataSet DataSet;
        public EmpresaSAMTootegaTestCIT()
        {
            ID = gCID;
            Name = "EmpresaSAMTootegaTest";
            ApplicationID = new Guid("042C5B34-309F-467B-A954-35B184002537");
            MenuItemID = new Guid("042C5B34-309F-467B-A954-35B184002537");
            AppModulesID = new [] { (Int16)14 };
            AppGroupsID = new [] { (Int16)2 };
            PlayCount = 1;
            Title = "Afiliados";
            ServiceID = new Guid("9E8C925A-4D52-4CB2-BA77-674A969F44E3");
            Tutor = (EmpresaSVC)XModelCache.Instance.GetSVC(ServiceID);
            DataSet = Tutor.DataSetType.CreateInstance<EmpresaSVC.XDataSet>();
            DataSet.Prepare(Tutor);
            EmpresaSVC.XTuple EmpresaxTPL;
            EmpresaxTPL = new EmpresaSVC.XTuple(DataSet.Fields.Count);
            EmpresaxTPL.PKValue = new Guid("63D32D2E-7F0F-4EE2-8433-E3E407711AE9");
            DataSet.AddTuple(EmpresaxTPL);
            EmpresaxTPL.SYSxPessoaID = new Guid("63D32D2E-7F0F-4EE2-8433-E3E407711AE9");
            EmpresaxTPL.SYSxEstadoID = (Int16)1;
            EmpresaxTPL.RazaoSocial = @"TTG01 - Tootega Pesquisa e Inovação";
            EmpresaxTPL.Nome = @"TTG01 - Tootega Pesquisa e Inovação";
            EmpresaxTPL.Sigla = @"TTG01";
            EmpresaxTPL.Grupo = @"TTG01";
            EmpresaxTPL.Numero = @"58375887000182";
            EmpresaxTPL.Chave = null;
            EmpresaxTPL.SYSxEmpresaMatrizID = new Guid("63D32D2E-7F0F-4EE2-8433-E3E407711AE9");
            EmpresaxTPL.SYSxEmpresaGrupoID = new Guid("9AF51F47-F23F-4E58-B92F-F2529BF45414");
            DocumentoSVC.XTuple DocumentoxTPL;
            DocumentoxTPL = new DocumentoSVC.XTuple(DataSet.DocumentoDataSet.Fields.Count);
            DocumentoxTPL.PKValue = new Guid("7FF313C0-94E1-4167-86AF-2E42D942C3F4");
            DataSet.DocumentoDataSet.AddTuple(DocumentoxTPL);
            DocumentoxTPL.Numero = @"58375887000182";
            DocumentoxTPL.SYSxEstadoID = (Int16)1;
            DocumentoxTPL.SYSxPessoaID = new Guid("63D32D2E-7F0F-4EE2-8433-E3E407711AE9");
            DocumentoxTPL.ERPxDocumentoID = new Guid("7FF313C0-94E1-4167-86AF-2E42D942C3F4");
            DocumentoxTPL.ERPxDocumentoTipoID = (Int16)2;
            DocumentoxTPL.Tipo = @"CNPJ";
            DocumentoxTPL.Mascara = @"00.000.000/0000-00";
        }
    }
}