//<auto-generated/>
using System;
using TFX.Core.Model;

namespace TFX.Core.Access.UsuariosAtivos
{
    public class UsuariosAtivos : XSAMApplication
    {
        public UsuariosAtivos()
        {
            Title = "Usuários Ativos";
            Module = "TFX.Core.Access";
            Icon = "";
            MenuID = new Guid("C20B474B-B025-41AF-9343-44359EAB0790");
            Ordem = 1;
        }
    }
}