//<auto-generated/>
using System;
using System.Linq;
using Newtonsoft.Json;
using TFX.Core.Objects;
using TFX.Core.Model.Data;
using TFX.Core.Model.Cache;
using TFX.Core.Reflections;
using TFX.Core.Service.Job;
using TFX.Core.Service.SVC;
using Projecao.Core.CRD.DB;
using Projecao.Core.ERP.DB;
using TFX.Core.Service.Apps;
using TFX.Core.Model.DIC.SVC;
using TFX.Core.Model.DIC.ORM;
using TFX.Core.Model.DIC.FRM;
using TFX.Core.Model.DIC.APP;
using TFX.Core.Model.DIC.RPT;
using TFX.Core.Model.Services;
using TFX.Core.Model.DIC.Types;
using Projecao.Core.ERP.Pessoa;
using TFX.Core.Model.Interfaces;
using System.Collections.Generic;
using Projecao.Core.CRD.Convenio;
using System.Runtime.InteropServices;

namespace Projecao.Core.CRD.Convenio
{
    [XRegister(typeof(ConvenioSVC), sCID)]
    [XDASESource(@"D:\Tootega\Source\TFX20\Modules\Projecao.Core.CRD\Projecao.Core.CRD.csproj", @"D:\Tootega\Source\TFX20\Modules\Projecao.Core.CRD\Convenio\Convenio.dssvc")]
    public class ConvenioSVC : XSVCModel
    {
        #region ConvenioFilterFRM

        [XRegister(typeof(ConvenioFilterFRM), sCID)]
        public class ConvenioFilterFRM : XFRMModel
        {
            public const String sCID = "604F6640-A53F-4450-A818-3917530B8976";
            static ConvenioFilterFRM()
            {
                gCID = new Guid(sCID);
            }
            public ConvenioFilterFRM()
            {
                ID = gCID;
                Name = "ConvenioFilter";
                Title = "";
                MinRows = 1;
                ConfigCID = new Guid("00000000-0000-0000-0000-000000000000");
                ConfigPKFilter = false;
                Rect = new XRect(20, 20, 965, 678);
                Style = XFRMStyle.Normal;
                ActionContext = XActionContext.All;
                AddItem(RazaoSocial);
                RazaoSocial.ForceRW = true;
                RazaoSocial.CanInsert = true;
                RazaoSocial.CanUpdate = true;
                RazaoSocial.RowCount = 1;
                RazaoSocial.ColCount = 32;
                RazaoSocial.RowCountSmall = 1;
                RazaoSocial.ColCountSmall = 32;
                RazaoSocial.IsHidden = false;
                RazaoSocial.IsHiddenSmall = false;
                RazaoSocial.AdditionalTitle = "";
                RazaoSocial.Location = 1;
                RazaoSocial.EditorCID = new Guid("AA2A0DB9-2C59-4833-994D-3DBF2AA0CB3C");
                RazaoSocial.FormImplace = true;
                RazaoSocial.Operator = XOperator.Like;
                RazaoSocial.JustifyHeight = false;
                RazaoSocial.AllowEmpty = true;
                RazaoSocial.FontColor = "#000000";
                RazaoSocial.FontStyle = XFontStyle.Normal;
                RazaoSocial.ShowFooter = false;
                RazaoSocial.ViewSAM = new Guid("00000000-0000-0000-0000-000000000000");
                RazaoSocial.Scale = 0;
                RazaoSocial.Length = 160;
                RazaoSocial.SearchAction = XSearchAction.Default;
                RazaoSocial.TypeID = XString.CID;
                RazaoSocial.AdditionalFieldsID = new Guid[] { new Guid("F08FE609-6332-44C8-A569-CA9D51765F56"), new Guid("3EF72D40-4115-422E-B159-17C8A4592288") };
                RazaoSocial.AdditionalDataFieldsID = new Guid[] {  };
                RazaoSocial.TargetFilterFieldID = new Guid[] {  };
                RazaoSocial.SourceFilterFieldID = new Guid[] {  };
                RazaoSocial.TargetDisplayFieldID = new Guid[] {  };
                RazaoSocial.SourceDisplayFieldID = new Guid[] {  };
                RazaoSocial.AutoLoad = false;
                RazaoSocial.FilterInative = true;
                RazaoSocial.IsAnswer = false;
                RazaoSocial.AllowMultiSelect = false;
            }
            public XFRMField RazaoSocial = new XFRMField(new Guid("7F6359CE-F6AD-4601-9ED4-CA59DF97D10C"), "RazaoSocial", "Razão Social", XString.CID, 1, 32, false, gCID, null, new Guid("8331AB57-CD70-43C4-88F5-BB525575F3B0")); // String;
            public static class Fields
            {
                public static XFieldInfo RazaoSocial = new XFieldInfo(new Guid("7F6359CE-F6AD-4601-9ED4-CA59DF97D10C"), "RazaoSocial", "Razão Social", typeof(String));
            }
        }

        #endregion ConvenioFilterFRM

        public const String sCID = "E17A9F12-E95D-40FE-91EF-5CC6DC86735F";
        public static Guid gCID = new Guid(sCID);
        public static XSVCReference CRDxConvenio_CRDxConvenioID_ERPxPessoaJuridica_ERPxPessoaJuridicaID; // CRDxConvenio.CRDxConvenioID --> ERPxPessoaJuridica.ERPxPessoaJuridicaID
        public static XSVCReference ERPxPessoaJuridica_ERPxPessoaJuridicaID_SYSxPessoa_SYSxPessoaID; // ERPxPessoaJuridica.ERPxPessoaJuridicaID --> SYSxPessoa.SYSxPessoaID
        public static XSVCReference CRDxConvenioTipo_CRDxConvenioTipoID_CRDxConvenio_CRDxConvenioTipoID; // CRDxConvenioTipo.CRDxConvenioTipoID --> CRDxConvenio.CRDxConvenioTipoID

        #region xCRDxConvenioTipo 
        public class xCRDxConvenioTipo : XSVCTable
        {

            public static Guid gCID => new Guid("541CDE0D-C8A6-49FF-A8A6-6FB6022ECAB2");

            public xCRDxConvenioTipo()
            {
                Name = "CRDxConvenioTipo";
                Alias = "CRDxConvenioTipo";
                ID = gCID;
                ParentID =  global::Projecao.Core.CRD.DB.CRDx.CRDxConvenioTipo.gCID;

                Items.Add(CRDxConvenioTipoID, CRDxConvenioTipoID.ID);
                CRDxConvenioTipoID.Owner = this;
                CRDxConvenioTipoID.OwnerID = ID;
                CRDxConvenioTipoID.TableName = Name;
                Items.Add(Tipo, Tipo.ID);
                Tipo.Owner = this;
                Tipo.OwnerID = ID;
                Tipo.TableName = Name;
                Tipo.Alias = "Tipo";
            }

            public static XORMPKField CRDxConvenioTipoID = new XORMPKField(global::Projecao.Core.CRD.DB.CRDx.CRDxConvenioTipo.CRDxConvenioTipoID, new Guid("7A420B9C-398C-4F80-8D0B-91F16C9E205D"), "CRDxConvenioTipoID", "Tipo de Convênio");
            public static XORMFaceField Tipo = new XORMFaceField(global::Projecao.Core.CRD.DB.CRDx.CRDxConvenioTipo.Tipo, new Guid("5AF9E9AA-D290-4FE6-ACA1-3E5B7231AD5C"), "Tipo", "Tipo");
        }
        #endregion xCRDxConvenioTipo 


        #region xSYSxPessoa 
        public class xSYSxPessoa : XSVCTable
        {

            public static Guid gCID => new Guid("8869965B-5DAE-40A1-A481-C46908F9B3D6");

            public xSYSxPessoa()
            {
                Name = "SYSxPessoa";
                Alias = "SYSxPessoa";
                ID = gCID;
                ParentID =  global::TFX.Core.Service.Apps.SYSx.SYSxPessoa.gCID;

                Items.Add(Nome, Nome.ID);
                Nome.Owner = this;
                Nome.OwnerID = ID;
                Nome.TableName = Name;
                Nome.Alias = "Nome";
                Items.Add(SYSxPessoaID, SYSxPessoaID.ID);
                SYSxPessoaID.Owner = this;
                SYSxPessoaID.OwnerID = ID;
                SYSxPessoaID.TableName = Name;
                SYSxPessoaID.Alias = "SYSxPessoaID";
            }

            public static XORMFaceField Nome = new XORMFaceField(global::TFX.Core.Service.Apps.SYSx.SYSxPessoa.Nome, new Guid("1FBFDECE-E491-4ABC-A638-53E73ED31727"), "Nome", "Nome");
            public static XORMPKField SYSxPessoaID = new XORMPKField(global::TFX.Core.Service.Apps.SYSx.SYSxPessoa.SYSxPessoaID, new Guid("63C1EFB6-42B6-4C40-9EB3-D7BDDA13C2AF"), "SYSxPessoaID", "Pessoas");
        }
        #endregion xSYSxPessoa 


        #region xCRDxConvenio 
        public class xCRDxConvenio : XSVCTable
        {

            public static Guid gCID => new Guid("AF0111FD-2894-41C8-BE04-644193C3D006");

            public xCRDxConvenio()
            {
                Name = "CRDxConvenio";
                Alias = "CRDxConvenio";
                ID = gCID;
                ParentID =  global::Projecao.Core.CRD.DB.CRDx.CRDxConvenio.gCID;

                Items.Add(CRDxConvenioID, CRDxConvenioID.ID);
                CRDxConvenioID.Owner = this;
                CRDxConvenioID.OwnerID = ID;
                CRDxConvenioID.TableName = Name;
                Items.Add(Inicio, Inicio.ID);
                Inicio.Owner = this;
                Inicio.OwnerID = ID;
                Inicio.TableName = Name;
                Inicio.Alias = "Inicio";
                Items.Add(Pagamento, Pagamento.ID);
                Pagamento.Owner = this;
                Pagamento.OwnerID = ID;
                Pagamento.TableName = Name;
                Pagamento.Alias = "Pagamento";
                Items.Add(Fechamento, Fechamento.ID);
                Fechamento.Owner = this;
                Fechamento.OwnerID = ID;
                Fechamento.TableName = Name;
                Fechamento.Alias = "Fechamento";
                Items.Add(SYSxEstadoID, SYSxEstadoID.ID);
                SYSxEstadoID.Owner = this;
                SYSxEstadoID.OwnerID = ID;
                SYSxEstadoID.TableName = Name;
                SYSxEstadoID.Alias = "SYSxEstadoID";
                Items.Add(CRDxConvenioTipoID, CRDxConvenioTipoID.ID);
                CRDxConvenioTipoID.Owner = this;
                CRDxConvenioTipoID.OwnerID = ID;
                CRDxConvenioTipoID.TableName = Name;
                CRDxConvenioTipoID.Alias = "CRDxConvenioTipoID";
            }

            public static XORMFaceField CRDxConvenioID = new XORMFaceField(global::Projecao.Core.CRD.DB.CRDx.CRDxConvenio.CRDxConvenioID, new Guid("339A5561-5076-4C6A-ABEB-72DF808B3356"), "CRDxConvenioID", "Convênio");
            public static XORMDateTimeField Inicio = new XORMDateTimeField(global::Projecao.Core.CRD.DB.CRDx.CRDxConvenio.Inicio, new Guid("83A4EC4B-B5D3-43B1-9FE2-94411A84E968"), "Inicio", "Início");
            public static XORMField Pagamento = new XORMField(global::Projecao.Core.CRD.DB.CRDx.CRDxConvenio.Pagamento, new Guid("4193E358-170E-4765-89C8-9C8C442F9B7B"), "Pagamento", "Dia de Pagamento");
            public static XORMField Fechamento = new XORMField(global::Projecao.Core.CRD.DB.CRDx.CRDxConvenio.Fechamento, new Guid("16971781-0C8E-425E-A38D-303889B12F31"), "Fechamento", "Dia de Fechamento");
            public static XORMStateField SYSxEstadoID = new XORMStateField(global::Projecao.Core.CRD.DB.CRDx.CRDxConvenio.SYSxEstadoID, new Guid("F352B3B7-8D32-4221-9475-FBFA8B537BAF"), "SYSxEstadoID", "Estado");
            public static XORMFKField CRDxConvenioTipoID = new XORMFKField(global::Projecao.Core.CRD.DB.CRDx.CRDxConvenio.CRDxConvenioTipoID, new Guid("2A3868C3-6042-4B7C-A45C-DB646B349E96"), "CRDxConvenioTipoID", "Tipo de Convênio");
        }
        #endregion xCRDxConvenio 


        #region xERPxPessoaJuridica 
        public class xERPxPessoaJuridica : XSVCTable
        {

            public static Guid gCID => new Guid("CDC61A3D-7BC0-4374-A05D-C96A9EF13AD7");

            public xERPxPessoaJuridica()
            {
                Name = "ERPxPessoaJuridica";
                Alias = "ERPxPessoaJuridica";
                ID = gCID;
                ParentID =  global::Projecao.Core.ERP.DB.ERPx.ERPxPessoaJuridica.gCID;

                Items.Add(ERPxPessoaJuridicaID, ERPxPessoaJuridicaID.ID);
                ERPxPessoaJuridicaID.Owner = this;
                ERPxPessoaJuridicaID.OwnerID = ID;
                ERPxPessoaJuridicaID.TableName = Name;
                Items.Add(SYSxEstadoID, SYSxEstadoID.ID);
                SYSxEstadoID.Owner = this;
                SYSxEstadoID.OwnerID = ID;
                SYSxEstadoID.TableName = Name;
                SYSxEstadoID.Alias = "SYSxPJEstadoID";
                Items.Add(RazaoSocial, RazaoSocial.ID);
                RazaoSocial.Owner = this;
                RazaoSocial.OwnerID = ID;
                RazaoSocial.TableName = Name;
                RazaoSocial.Alias = "RazaoSocial";
            }

            public static XORMFaceField ERPxPessoaJuridicaID = new XORMFaceField(global::Projecao.Core.ERP.DB.ERPx.ERPxPessoaJuridica.ERPxPessoaJuridicaID, new Guid("E66287A0-5A16-444F-B2C2-D6F9F5283C5C"), "ERPxPessoaJuridicaID", "Pessoa Jurídica");
            public static XORMStateField SYSxEstadoID = new XORMStateField(global::Projecao.Core.ERP.DB.ERPx.ERPxPessoaJuridica.SYSxEstadoID, new Guid("CA9FE56D-B4C0-45BB-BE87-47E286FD50DB"), "SYSxEstadoID", "Estado");
            public static XORMField RazaoSocial = new XORMField(global::Projecao.Core.ERP.DB.ERPx.ERPxPessoaJuridica.RazaoSocial, new Guid("8331AB57-CD70-43C4-88F5-BB525575F3B0"), "RazaoSocial", "Razão Social");
        }
        #endregion xERPxPessoaJuridica 


        public xCRDxConvenio CRDxConvenio;
        public xCRDxConvenioTipo CRDxConvenioTipo;
        public xERPxPessoaJuridica ERPxPessoaJuridica;
        public xSYSxPessoa SYSxPessoa;
        public static readonly XORMParameterField CNPJ = new XORMParameterField(new Guid("41020239-0E28-4DA4-B717-D8C20202955A"), "CNPJ", "CNPJ", XString.CID, 0, 0, false, gCID, null);

        public ConvenioSVC()
        {
            TupleType = typeof(ConvenioSVC.XTuple);
            DataSetType = typeof(ConvenioSVC.XDataSet);
            ServiceRuleCID = new Guid("72914434-EDA1-433F-B468-0F2756D8A124");
            OnlyActives = false;
            Actions = XSVCAction.All;
            Type = XServiceType.Default;
            ID = new Guid("E17A9F12-E95D-40FE-91EF-5CC6DC86735F");
            Name = "Convenio";
            Title = "Convênio";
            IsCacheable = false;
            CompanyControl = false;
            IsJob = false;
            AutoLoad = true;
            FreeForUsers = false;
            ServerSideNewRecord = false;
            UseDistinct = false;
            JobType = XJobType.Default;
            CanExport = false;
            ModuleID = new Guid("EBB5930C-9A21-4AB6-993E-B86F40039784");
            Rights = new Int16[] { 1, 2, 3, 4, 5, 6, 7 }; 
            FilterFormID = new Guid("604F6640-A53F-4450-A818-3917530B8976");
            IsReadOnly = false;
            ClientScript = "Projecao.Core.CRD.js";
            GridFields = new Guid[] { xSYSxPessoa.SYSxPessoaID.ID, xERPxPessoaJuridica.RazaoSocial.ID, xSYSxPessoa.Nome.ID, xCRDxConvenioTipo.Tipo.ID };
            OrderByFields = new Guid[] { xERPxPessoaJuridica.RazaoSocial.ID };
            DataSetFields = new Guid[] { CNPJ.ID, xCRDxConvenio.CRDxConvenioTipoID.ID, xCRDxConvenio.Fechamento.ID, xCRDxConvenio.Inicio.ID, xCRDxConvenio.Pagamento.ID, xCRDxConvenio.SYSxEstadoID.ID, xCRDxConvenioTipo.Tipo.ID, xERPxPessoaJuridica.RazaoSocial.ID, xERPxPessoaJuridica.SYSxEstadoID.ID, xSYSxPessoa.Nome.ID, xSYSxPessoa.SYSxPessoaID.ID };
            StateField = xCRDxConvenio.SYSxEstadoID.ID;
            PKField = xSYSxPessoa.SYSxPessoaID.ID;
            ConfigTableID = new Guid("6FBFB697-EAEA-4747-A431-053B84E28FEC");
            MasterRuleCID = new Guid("72914434-EDA1-433F-B468-0F2756D8A124");
            XSubServiceItem ss536EFB6236724861B2B3B3FD0EAB865A = new XSubServiceItem(EmpresasPermitidasSVC.gCID, EmpresasPermitidasSVC.xCRDxConvenioEmpresa.CRDxConvenioID.ID, ConvenioSVC.gCID, xSYSxPessoa.SYSxPessoaID.ID, true, XSubSeviceType.Default);
            ss536EFB6236724861B2B3B3FD0EAB865A.Rights = new Int16[] { 1 }; 
            ss536EFB6236724861B2B3B3FD0EAB865A.LateLoad = false;
            SubServices.Add(ss536EFB6236724861B2B3B3FD0EAB865A);
            XSubServiceItem ss8CC383823CD64321ABCA84902EAFACE4 = new XSubServiceItem(DocumentoSVC.gCID, DocumentoSVC.xERPxDocumento.SYSxPessoaID.ID, ConvenioSVC.gCID, xSYSxPessoa.SYSxPessoaID.ID, true, XSubSeviceType.Default);
            ss8CC383823CD64321ABCA84902EAFACE4.Rights = new Int16[] { 1 }; 
            ss8CC383823CD64321ABCA84902EAFACE4.LateLoad = false;
            SubServices.Add(ss8CC383823CD64321ABCA84902EAFACE4);
            XSubServiceItem ssD73435CB8D284177A0F0E0F3D5E5460D = new XSubServiceItem(EnderecoSVC.gCID, EnderecoSVC.xERPxEndereco.SYSxPessoaID.ID, ConvenioSVC.gCID, xSYSxPessoa.SYSxPessoaID.ID, true, XSubSeviceType.Default);
            ssD73435CB8D284177A0F0E0F3D5E5460D.Rights = new Int16[] { 1 }; 
            ssD73435CB8D284177A0F0E0F3D5E5460D.LateLoad = false;
            SubServices.Add(ssD73435CB8D284177A0F0E0F3D5E5460D);
            XSubServiceItem ss1E27BDB4899442B6A8B32BA91EAD578D = new XSubServiceItem(ContatoSVC.gCID, ContatoSVC.xERPxContato.SYSxPessoaID.ID, ConvenioSVC.gCID, xSYSxPessoa.SYSxPessoaID.ID, true, XSubSeviceType.Default);
            ss1E27BDB4899442B6A8B32BA91EAD578D.Rights = new Int16[] { 1 }; 
            ss1E27BDB4899442B6A8B32BA91EAD578D.LateLoad = false;
            SubServices.Add(ss1E27BDB4899442B6A8B32BA91EAD578D);
            CRDxConvenio = new xCRDxConvenio();
            CRDxConvenio.IsReadOnly = false;
            AddTable(CRDxConvenio);
            CRDxConvenioTipo = new xCRDxConvenioTipo();
            CRDxConvenioTipo.IsReadOnly = true;
            AddTable(CRDxConvenioTipo);
            ERPxPessoaJuridica = new xERPxPessoaJuridica();
            ERPxPessoaJuridica.IsReadOnly = false;
            AddTable(ERPxPessoaJuridica);
            SYSxPessoa = new xSYSxPessoa();
            SYSxPessoa.IsReadOnly = false;
            AddTable(SYSxPessoa);
            MasterTableID = SYSxPessoa.ID;
            CRDxConvenio_CRDxConvenioID_ERPxPessoaJuridica_ERPxPessoaJuridicaID = AddReference(new XSVCReference(new Guid("01E89DD2-72AE-4D84-B5B7-2011FBB4551B"), "FK_01E89DD272AE4D84B5B72011FBB4551B", ConvenioSVC.xCRDxConvenio.gCID, xCRDxConvenio.CRDxConvenioID.ID, ConvenioSVC.xERPxPessoaJuridica.gCID, xERPxPessoaJuridica.ERPxPessoaJuridicaID.ID, XJoinType.Inner)); // CRDxConvenio.CRDxConvenioID --> ERPxPessoaJuridica.ERPxPessoaJuridicaID
            ERPxPessoaJuridica_ERPxPessoaJuridicaID_SYSxPessoa_SYSxPessoaID = AddReference(new XSVCReference(new Guid("3EBC3277-9E9C-4897-A009-34943D403E27"), "FK_3EBC32779E9C4897A00934943D403E27", ConvenioSVC.xERPxPessoaJuridica.gCID, xERPxPessoaJuridica.ERPxPessoaJuridicaID.ID, ConvenioSVC.xSYSxPessoa.gCID, xSYSxPessoa.SYSxPessoaID.ID, XJoinType.Inner)); // ERPxPessoaJuridica.ERPxPessoaJuridicaID --> SYSxPessoa.SYSxPessoaID
            CRDxConvenioTipo_CRDxConvenioTipoID_CRDxConvenio_CRDxConvenioTipoID = AddReference(new XSVCReference(new Guid("43FB27F7-65A8-4D05-A3A5-8D49D91E9B19"), "FK_43FB27F765A84D05A3A58D49D91E9B19", ConvenioSVC.xCRDxConvenioTipo.gCID, xCRDxConvenioTipo.CRDxConvenioTipoID.ID, ConvenioSVC.xCRDxConvenio.gCID, xCRDxConvenio.CRDxConvenioTipoID.ID, XJoinType.Inner)); // CRDxConvenioTipo.CRDxConvenioTipoID --> CRDxConvenio.CRDxConvenioTipoID
            XSVCReference FK_2608C1FE03FB48A5B727DAC1C878BBE3 = new XSVCReference(new Guid("2608C1FE-03FB-48A5-B727-DAC1C878BBE3"), "FK_2608C1FE03FB48A5B727DAC1C878BBE3", EmpresasPermitidasSVC.gCID, EmpresasPermitidasSVC.xCRDxConvenioEmpresa.CRDxConvenioID.ID, SYSxPessoa.ID, ConvenioSVC.xSYSxPessoa.SYSxPessoaID.ID, XJoinType.SubService); // EmpresasPermitidasSVC.CRDxConvenioID --> Convenio.SYSxPessoaID
            FK_2608C1FE03FB48A5B727DAC1C878BBE3.IsLowRelevance = false;
            AddReference(FK_2608C1FE03FB48A5B727DAC1C878BBE3);
            XSVCReference FK_27A2C2E78FDC48BFA6BB5E1890EA0621 = new XSVCReference(new Guid("27A2C2E7-8FDC-48BF-A6BB-5E1890EA0621"), "FK_27A2C2E78FDC48BFA6BB5E1890EA0621", DocumentoSVC.gCID, DocumentoSVC.xERPxDocumento.SYSxPessoaID.ID, SYSxPessoa.ID, ConvenioSVC.xSYSxPessoa.SYSxPessoaID.ID, XJoinType.SubService); // DocumentoSVC.SYSxPessoaID --> Convenio.SYSxPessoaID
            FK_27A2C2E78FDC48BFA6BB5E1890EA0621.IsLowRelevance = false;
            AddReference(FK_27A2C2E78FDC48BFA6BB5E1890EA0621);
            XSVCReference FK_304261E3D77E4C899ACC9BAA5835407B = new XSVCReference(new Guid("304261E3-D77E-4C89-9ACC-9BAA5835407B"), "FK_304261E3D77E4C899ACC9BAA5835407B", EnderecoSVC.gCID, EnderecoSVC.xERPxEndereco.SYSxPessoaID.ID, SYSxPessoa.ID, ConvenioSVC.xSYSxPessoa.SYSxPessoaID.ID, XJoinType.SubService); // EnderecoSVC.SYSxPessoaID --> Convenio.SYSxPessoaID
            FK_304261E3D77E4C899ACC9BAA5835407B.IsLowRelevance = false;
            AddReference(FK_304261E3D77E4C899ACC9BAA5835407B);
            XSVCReference FK_8DE3A058A16F45BCA8662B5A471C7741 = new XSVCReference(new Guid("8DE3A058-A16F-45BC-A866-2B5A471C7741"), "FK_8DE3A058A16F45BCA8662B5A471C7741", ContatoSVC.gCID, ContatoSVC.xERPxContato.SYSxPessoaID.ID, SYSxPessoa.ID, ConvenioSVC.xSYSxPessoa.SYSxPessoaID.ID, XJoinType.SubService); // ContatoSVC.SYSxPessoaID --> Convenio.SYSxPessoaID
            FK_8DE3A058A16F45BCA8662B5A471C7741.IsLowRelevance = false;
            AddReference(FK_8DE3A058A16F45BCA8662B5A471C7741);
            AddField(CNPJ);
            CNPJ.IsParam = true;
            CNPJ.IsReadOnly = false;
            CNPJ.Length = 0;
            CNPJ.Scale = 0;
            CNPJ.IsDataField = true;
            CNPJ.AllowEmpty = true;
            xCRDxConvenio.CRDxConvenioTipoID.IsDataField = true;
            xCRDxConvenio.CRDxConvenioTipoID.AllowEmpty = true;
            xCRDxConvenio.Fechamento.IsDataField = true;
            xCRDxConvenio.Fechamento.AllowEmpty = true;
            xCRDxConvenio.Inicio.IsDataField = true;
            xCRDxConvenio.Inicio.AllowEmpty = true;
            xSYSxPessoa.Nome.Length = 256;
            xSYSxPessoa.Nome.IsDataField = true;
            xSYSxPessoa.Nome.FilterUse = true;
            xSYSxPessoa.Nome.AllowEmpty = true;
            xCRDxConvenio.Pagamento.IsDataField = true;
            xCRDxConvenio.Pagamento.AllowEmpty = true;
            xERPxPessoaJuridica.RazaoSocial.OrderType = XOrderType.Asc;
            xERPxPessoaJuridica.RazaoSocial.Length = 160;
            xERPxPessoaJuridica.RazaoSocial.IsDataField = true;
            xERPxPessoaJuridica.RazaoSocial.FilterUse = true;
            xERPxPessoaJuridica.RazaoSocial.AllowEmpty = true;
            xCRDxConvenio.SYSxEstadoID.IsDataField = true;
            xCRDxConvenio.SYSxEstadoID.AllowEmpty = true;
            xSYSxPessoa.SYSxPessoaID.GeneratePK = true;
            xSYSxPessoa.SYSxPessoaID.IsDataField = true;
            xSYSxPessoa.SYSxPessoaID.AllowEmpty = true;
            xERPxPessoaJuridica.SYSxEstadoID.IsDataField = true;
            xERPxPessoaJuridica.SYSxEstadoID.AllowEmpty = true;
            xCRDxConvenioTipo.Tipo.IsReadOnly = true;
            xCRDxConvenioTipo.Tipo.Length = 25;
            xCRDxConvenioTipo.Tipo.IsDataField = true;
            xCRDxConvenioTipo.Tipo.AllowEmpty = true;
            xERPxPessoaJuridica.RazaoSocial.DefaultValue = @"NI";
            xCRDxConvenio.SYSxEstadoID.DefaultValue = (Int16)1;
            xERPxPessoaJuridica.SYSxEstadoID.DefaultValue = (Int16)1;
        }

        #region XFields

        public class XFields
        {
        public XORMField CNPJ => ConvenioSVC.CNPJ;
        public XORMField CRDxConvenioTipoID => xCRDxConvenio.CRDxConvenioTipoID;
        public XORMField Fechamento => xCRDxConvenio.Fechamento;
        public XORMField Inicio => xCRDxConvenio.Inicio;
        public XORMField Nome => xSYSxPessoa.Nome;
        public XORMField Pagamento => xCRDxConvenio.Pagamento;
        public XORMField RazaoSocial => xERPxPessoaJuridica.RazaoSocial;
        public XORMField SYSxEstadoID => xCRDxConvenio.SYSxEstadoID;
        public XORMField SYSxPessoaID => xSYSxPessoa.SYSxPessoaID;
        public XORMField SYSxPJEstadoID => xERPxPessoaJuridica.SYSxEstadoID;
        public XORMField Tipo => xCRDxConvenioTipo.Tipo;
        }
        #endregion XFields
        #region ConvenioSVC.XTuple

        public  class XTuple : XDataTuple
        {

            public XTuple()
            {
            }

            public XTuple(Object[] pSource)
                : base(pSource)
            {
            }

            public XTuple(Int32 pColCount)
               : this(new Object[pColCount])
            {
            }

            public readonly XFields Fields = new XFields();

            #nullable enable

        public String CNPJ
        {
            get
            {
                return (String)Value[ConvenioSVC.CNPJ.ID];
            }
            set
            {
                Value[ConvenioSVC.CNPJ.ID] = value;
            }
        }
        public String? oCNPJ
        {
            get
            {
                GetOldValue(ConvenioSVC.CNPJ, out Object ovlr);
                return (String?)ovlr;
            }
        }

        public Int16 CRDxConvenioTipoID
        {
            get
            {
                return (Int16)Value[ConvenioSVC.xCRDxConvenio.CRDxConvenioTipoID.ID];
            }
            set
            {
                Value[ConvenioSVC.xCRDxConvenio.CRDxConvenioTipoID.ID] = value;
            }
        }
        public Int16? oCRDxConvenioTipoID
        {
            get
            {
                GetOldValue(ConvenioSVC.xCRDxConvenio.CRDxConvenioTipoID, out Object ovlr);
                return (Int16?)ovlr;
            }
        }

        public Int16 Fechamento
        {
            get
            {
                return (Int16)Value[ConvenioSVC.xCRDxConvenio.Fechamento.ID];
            }
            set
            {
                Value[ConvenioSVC.xCRDxConvenio.Fechamento.ID] = value;
            }
        }
        public Int16? oFechamento
        {
            get
            {
                GetOldValue(ConvenioSVC.xCRDxConvenio.Fechamento, out Object ovlr);
                return (Int16?)ovlr;
            }
        }

        public DateTime Inicio
        {
            get
            {
                return (DateTime)Value[ConvenioSVC.xCRDxConvenio.Inicio.ID];
            }
            set
            {
                Value[ConvenioSVC.xCRDxConvenio.Inicio.ID] = value;
            }
        }
        public DateTime? oInicio
        {
            get
            {
                GetOldValue(ConvenioSVC.xCRDxConvenio.Inicio, out Object ovlr);
                return (DateTime?)ovlr;
            }
        }

        public String Nome
        {
            get
            {
                return (String)Value[ConvenioSVC.xSYSxPessoa.Nome.ID];
            }
            set
            {
                Value[ConvenioSVC.xSYSxPessoa.Nome.ID] = value;
            }
        }
        public String? oNome
        {
            get
            {
                GetOldValue(ConvenioSVC.xSYSxPessoa.Nome, out Object ovlr);
                return (String?)ovlr;
            }
        }

        public Int16 Pagamento
        {
            get
            {
                return (Int16)Value[ConvenioSVC.xCRDxConvenio.Pagamento.ID];
            }
            set
            {
                Value[ConvenioSVC.xCRDxConvenio.Pagamento.ID] = value;
            }
        }
        public Int16? oPagamento
        {
            get
            {
                GetOldValue(ConvenioSVC.xCRDxConvenio.Pagamento, out Object ovlr);
                return (Int16?)ovlr;
            }
        }

        public String RazaoSocial
        {
            get
            {
                return (String)Value[ConvenioSVC.xERPxPessoaJuridica.RazaoSocial.ID];
            }
            set
            {
                Value[ConvenioSVC.xERPxPessoaJuridica.RazaoSocial.ID] = value;
            }
        }
        public String? oRazaoSocial
        {
            get
            {
                GetOldValue(ConvenioSVC.xERPxPessoaJuridica.RazaoSocial, out Object ovlr);
                return (String?)ovlr;
            }
        }

        public Int16 SYSxEstadoID
        {
            get
            {
                return (Int16)Value[ConvenioSVC.xCRDxConvenio.SYSxEstadoID.ID];
            }
            set
            {
                Value[ConvenioSVC.xCRDxConvenio.SYSxEstadoID.ID] = value;
            }
        }
        public Int16? oSYSxEstadoID
        {
            get
            {
                GetOldValue(ConvenioSVC.xCRDxConvenio.SYSxEstadoID, out Object ovlr);
                return (Int16?)ovlr;
            }
        }

        public Guid SYSxPessoaID
        {
            get
            {
                return (Guid)Value[ConvenioSVC.xSYSxPessoa.SYSxPessoaID.ID];
            }
            set
            {
                Value[ConvenioSVC.xSYSxPessoa.SYSxPessoaID.ID] = value;
            }
        }
        public Guid? oSYSxPessoaID
        {
            get
            {
                GetOldValue(ConvenioSVC.xSYSxPessoa.SYSxPessoaID, out Object ovlr);
                return (Guid?)ovlr;
            }
        }

        public Int16 SYSxPJEstadoID
        {
            get
            {
                return (Int16)Value[ConvenioSVC.xERPxPessoaJuridica.SYSxEstadoID.ID];
            }
            set
            {
                Value[ConvenioSVC.xERPxPessoaJuridica.SYSxEstadoID.ID] = value;
            }
        }
        public Int16? oSYSxPJEstadoID
        {
            get
            {
                GetOldValue(ConvenioSVC.xERPxPessoaJuridica.SYSxEstadoID, out Object ovlr);
                return (Int16?)ovlr;
            }
        }

        public String Tipo
        {
            get
            {
                return (String)Value[ConvenioSVC.xCRDxConvenioTipo.Tipo.ID];
            }
            set
            {
                Value[ConvenioSVC.xCRDxConvenioTipo.Tipo.ID] = value;
            }
        }
        public String? oTipo
        {
            get
            {
                GetOldValue(ConvenioSVC.xCRDxConvenioTipo.Tipo, out Object ovlr);
                return (String?)ovlr;
            }
        }

            #nullable disable
        }
        #endregion ConvenioSVC.XTuple

        #region ConvenioSVC.XRule
        public abstract class XRule : XServiceRule<ConvenioSVC.XDataSet, ConvenioSVC, ConvenioSVC.XTuple>
        {
        }
        #endregion ConvenioSVC.XRule

        #region ConvenioSVC.XDataSet

        public class XDataSet : XDataSet<ConvenioSVC.XTuple>
        {
            public XDataSet()
            {
                DataSetType = typeof(ConvenioSVC.XDataSet);
            }
        }

        public class XDataSet<T> : XServiceDataSet<ConvenioSVC.XTuple> where T : XDataTuple
        {

            public Guid CNPJ => ConvenioSVC.CNPJ.ID;
            public Guid CRDxConvenioTipoID => ConvenioSVC.xCRDxConvenio.CRDxConvenioTipoID.ID;
            public Guid Fechamento => ConvenioSVC.xCRDxConvenio.Fechamento.ID;
            public Guid Inicio => ConvenioSVC.xCRDxConvenio.Inicio.ID;
            public Guid Nome => ConvenioSVC.xSYSxPessoa.Nome.ID;
            public Guid Pagamento => ConvenioSVC.xCRDxConvenio.Pagamento.ID;
            public Guid RazaoSocial => ConvenioSVC.xERPxPessoaJuridica.RazaoSocial.ID;
            public Guid SYSxEstadoID => ConvenioSVC.xCRDxConvenio.SYSxEstadoID.ID;
            public Guid SYSxPessoaID => ConvenioSVC.xSYSxPessoa.SYSxPessoaID.ID;
            public Guid SYSxPJEstadoID => ConvenioSVC.xERPxPessoaJuridica.SYSxEstadoID.ID;
            public Guid Tipo => ConvenioSVC.xCRDxConvenioTipo.Tipo.ID;

            public XDataSet()
            {
                DataSetType = typeof(ConvenioSVC.XDataSet);
            }

            private Projecao.Core.ERP.Pessoa.ContatoSVC.XDataSet _ContatoDataSet;

            public Projecao.Core.ERP.Pessoa.ContatoSVC.XDataSet ContatoDataSet
            {
                get
                {
                    if (_ContatoDataSet == null)
                    {
                        _ContatoDataSet = (Projecao.Core.ERP.Pessoa.ContatoSVC.XDataSet)Children.Get(Projecao.Core.ERP.Pessoa.ContatoSVC.gCID);
                        _ContatoDataSet.IsReadOnly = true;
                    }
                    return  _ContatoDataSet;
                }
            }

            private Projecao.Core.CRD.Convenio.EmpresasPermitidasSVC.XDataSet _EmpresasPermitidasDataSet;

            public Projecao.Core.CRD.Convenio.EmpresasPermitidasSVC.XDataSet EmpresasPermitidasDataSet
            {
                get
                {
                    if (_EmpresasPermitidasDataSet == null)
                    {
                        _EmpresasPermitidasDataSet = (Projecao.Core.CRD.Convenio.EmpresasPermitidasSVC.XDataSet)Children.Get(Projecao.Core.CRD.Convenio.EmpresasPermitidasSVC.gCID);
                        _EmpresasPermitidasDataSet.IsReadOnly = true;
                    }
                    return  _EmpresasPermitidasDataSet;
                }
            }

            private Projecao.Core.ERP.Pessoa.DocumentoSVC.XDataSet _DocumentoDataSet;

            public Projecao.Core.ERP.Pessoa.DocumentoSVC.XDataSet DocumentoDataSet
            {
                get
                {
                    if (_DocumentoDataSet == null)
                    {
                        _DocumentoDataSet = (Projecao.Core.ERP.Pessoa.DocumentoSVC.XDataSet)Children.Get(Projecao.Core.ERP.Pessoa.DocumentoSVC.gCID);
                        _DocumentoDataSet.IsReadOnly = true;
                    }
                    return  _DocumentoDataSet;
                }
            }

            private Projecao.Core.ERP.Pessoa.EnderecoSVC.XDataSet _EnderecoDataSet;

            public Projecao.Core.ERP.Pessoa.EnderecoSVC.XDataSet EnderecoDataSet
            {
                get
                {
                    if (_EnderecoDataSet == null)
                    {
                        _EnderecoDataSet = (Projecao.Core.ERP.Pessoa.EnderecoSVC.XDataSet)Children.Get(Projecao.Core.ERP.Pessoa.EnderecoSVC.gCID);
                        _EnderecoDataSet.IsReadOnly = true;
                    }
                    return  _EnderecoDataSet;
                }
            }

        }
        #endregion ConvenioSVC.XDataSet

        [Guid(ConvenioSVC.sCID)]
        public  interface XService : XIBaseService
        {
            new XDataSet DataSet
            {
                get;
            }
            new XTuple NewTuple(Object pPKValue = null);
             IEnumerable<XTuple> Tuples
            {
                get;
            }
             XTuple Current
            {
                get;
            }
            new XDataSet Get(XServiceData pData);
             XDataSet Get(params Object[] pWhere);
        }
        [XRegister(typeof(_Service), _Service.sCID, typeof(ConvenioSVC))]
        protected class _Service : Service<ConvenioSVC, XDataSet, XTuple>
        {
            public const String sCID = "DBC19220-D6EA-42BA-A887-B2C1A0817615";
            public Guid gCID = new Guid(sCID);
        }

        public class Service<TModel, TDataSet, TTuple> : XBaseService<ConvenioSVC, XDataSet, XTuple>, XService
             where TModel : ConvenioSVC, new()
             where TDataSet : XDataSet, new()
             where TTuple : XTuple
        {
            XDataSet XService.DataSet => (XDataSet)DataSet;
            XTuple XService.NewTuple(Object pPKValue)
            {
                return (XTuple)NewTuple(pPKValue);
            }
            public new XDataTuple NewTuple(Object pPKValue = null)
            {
                return (XTuple)base.NewTuple(pPKValue);
            }
            IEnumerable<XTuple> XService.Tuples => (IEnumerable<XTuple>)Tuples;
            XTuple XService.Current => (XTuple )Current;
            XDataSet XService.Get(XServiceData pData)
            {
                return (XDataSet)Get(pData);
            }
            XDataSet XService.Get(params Object[] pWhere)
            {
                return (XDataSet)Get(pWhere);
            }
            public Service()
            {
                ID = gCID;
            }
        }
    }

}