//<auto-generated/>
using System;
using TFX.Core.Data;
using System.Drawing;
using Newtonsoft.Json;
using TFX.Core.Objects;
using TFX.Core.Model.DIC;
using TFX.Core.Reflections;
using TFX.Core.Model.DIC.APP;
using TFX.Core.Model.DIC.FRM;
using TFX.Core.Model.DIC.RPT;
using TFX.Core.Model.DIC.ORM;
using TFX.Core.Model.DIC.Types;

namespace Projecao.Core.CRD.FaturaFranqueado
{
    [XRegister(typeof(FaturaFranqueadoSAM), sCID)]
    [XDASESource(@"D:\Tootega\Source\TFX20\Modules\Projecao.Core.CRD\Projecao.Core.CRD.csproj", @"D:\Tootega\Source\TFX20\Modules\Projecao.Core.CRD\FaturaFranqueado\FaturaFranqueado.dssam")]
    public class FaturaFranqueadoSAM : XAPPModel
    {
        #region xFaturaFranqueadoACT

        [XRegister(typeof(xFaturaFranqueadoACT), sCID)]
        public class xFaturaFranqueadoACT : XAPPStep
        {
            public const String sCID = "F0AD39CD-D92A-4575-9905-561FA7349113";
            public static Guid gCID = new Guid(sCID);
            public xFaturaFranqueadoACT(Guid pID, String pName, String pTitle, Guid pFormID, Guid pDataSourceID)
              :base(pID, pName, pTitle, pFormID, pDataSourceID)
            {
            }
        }

        #endregion xFaturaFranqueadoACT

        #region FaturaFranqueadoFRM

        [XRegister(typeof(FaturaFranqueadoFRM), sCID)]
        public class FaturaFranqueadoFRM : XFRMModel
        {
            public const String sCID = "82D86F9B-72F8-44FF-B4E2-5AA25764E56B";
            static FaturaFranqueadoFRM()
            {
                gCID = new Guid(sCID);
            }
            public FaturaFranqueadoFRM()
            {
                ID = gCID;
                Name = "FaturaFranqueado";
                Title = "";
                MinRows = 0;
                ConfigCID = new Guid("00000000-0000-0000-0000-000000000000");
                ConfigPKFilter = false;
                Rect = new XRect(0, 0, 830, 50);
                Style = XFRMStyle.Normal;
                ActionContext = XActionContext.All;
            }
            public static class Fields
            {
            }
        }

        #endregion FaturaFranqueadoFRM

        public const String sCID = "B3D1DA7D-1B16-4973-BEFD-8193BDEF512B";
        public static Guid gCID = new Guid(sCID);
        public static readonly xFaturaFranqueadoACT FaturaFranqueadoACT;

        static FaturaFranqueadoSAM()
        {
            FaturaFranqueadoACT = new xFaturaFranqueadoACT(new Guid("F0AD39CD-D92A-4575-9905-561FA7349113"), "FaturaFranqueadoACT", "Faturas por Franqueado", new Guid("82D86F9B-72F8-44FF-B4E2-5AA25764E56B"), new Guid("00000000-0000-0000-0000-000000000000"));
        }

        public FaturaFranqueadoSAM()
        {
            ID = new Guid("B3D1DA7D-1B16-4973-BEFD-8193BDEF512B");
            Name = "FaturaFranqueado";
            Title = "Faturas por Franqueado";
            AppTypeID = XAppType.SAM;
            Userlevel = XUserlevel.User;
            UseTypeID = new Int16[] { 1, 2 };
            Rights = new Int16[] { 3, 6, 4, 1, 5, 2 }; 
            IsDisabled = false;
            StartAction = XStartAction.DataGrid;
            ClientScript = "Projecao.Core.CRD.js";
            Size = new Size(822, 390);
            DataSourceID = global::Projecao.Core.CRD.FaturaFranqueado.FaturaFranqueadoSVC.gCID;
            AppModulesID = new [] { (Int16)9 };
            AppGroupsID = new [] { (Int16)2 };
            FaturaFranqueadoACT.FormID = new Guid("82D86F9B-72F8-44FF-B4E2-5AA25764E56B"); 
            FaturaFranqueadoACT.Type = XActivityType.UserActivity;
            AddItem(FaturaFranqueadoACT);
        }
    }
}