//<auto-generated/>
using System;
using System.Linq;
using TFX.Core;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using TFX.Core.Lzma;

namespace TFX.Core.Data.DB
{
    public class CORxMenu : XEntity
    {
        public Boolean IsPKEmpty => Object.Equals(CORxMenuID, typeof(Guid).GetDefault());
        [Display(Name = "Menu")]
        [Required()]
        public Guid? CORxMenuID {get; set;}

        [Display(Name = "Ícone")]
        [MaxLength(25)]
        [Required()]
        public String Icone {get; set;}

        [MaxLength(50)]
        [Required()]
        public String Menu {get; set;}

        public List<CORxMenuItem> CORxMenuItem {get; set;} = new List<CORxMenuItem>();
    }
}
