//<auto-generated/>
using System;
using System.Linq;
using TFX.Core;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using TFX.Core.Lzma;

namespace TFX.Core.Data.DB
{
    public class CORxFavorito : XEntity
    {
        public Boolean IsPKEmpty => Object.Equals(CORxFavoritoID, typeof(Guid).GetDefault());
        [Display(Name = "Favoritos")]
        [Required()]
        public Guid? CORxFavoritoID {get; set;}

        [Display(Name = "Item de Menu")]
        [Required()]
        public Guid CORxMenuItemID {get; set;}

        [Display(Name = "Usuário")]
        [Required()]
        public Guid CORxUsuarioID {get; set;}

        [Display(Name = "Frequência")]
        [Required()]
        public Int32 Frequencia {get; set;}

        public CORxMenuItem CORxMenuItem {get; set;}
        public CORxUsuario CORxUsuario {get; set;}
    }
}
