//<auto-generated/>
using System;
using System.Linq;
using TFX.Core;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using TFX.Core.Lzma;

namespace TFX.Core.Data.DB
{
    public class CORxRecursoTemplateDireito : XEntity
    {
        [Display(Name = "Direitos por Recurso")]
        [Required()]
        public Guid CORxRecursoDireitoID {get; set;}

        public Boolean IsPKEmpty => Object.Equals(CORxRecursoTemplateDireitoID, typeof(Guid).GetDefault());
        [Display(Name = "Direito de Recurso por Template")]
        [Required()]
        public Guid? CORxRecursoTemplateDireitoID {get; set;}

        [Display(Name = "Conjunto de Recursos")]
        [Required()]
        public Guid CORxRecursoTemplateID {get; set;}

        public CORxRecursoTemplate CORxRecursoTemplate {get; set;}
        public CORxRecursoDireito CORxRecursoDireito {get; set;}
    }
}
