//<auto-generated/>
using System;
using System.Linq;
using TFX.Core;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using TFX.Core.Lzma;

namespace TFX.Core.Data.DB
{
    public class CORxEmpresa : XEntity
    {
        [Display(Name = "Agregado")]
        [Required()]
        public Guid CORxAgregadoID {get; set;}

        public Boolean IsPKEmpty => Object.Equals(CORxEmpresaID, typeof(Guid).GetDefault());
        [Display(Name = "Empresa")]
        [Required()]
        public Guid? CORxEmpresaID {get; set;}

        [Display(Name = "Estado")]
        [Required()]
        public Int16 CORxStatusID {get; set;}

        public CORxPessoa CORxPessoa {get; set;}
        public CORxAgregado CORxAgregado {get; set;}
        public CORxStatus CORxStatus {get; set;}
        public List<CORxEmpresaGrupo> CORxEmpresaGrupo {get; set;} = new List<CORxEmpresaGrupo>();
    }
}
