//<auto-generated/>
using System;
using System.Linq;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TFX.Core.Data.DB
{
    public  static class CORModel
    {

        public static class CORxStatus
        {
            public const string sInatoivo = @"Inatoivo";
            public const Int16 Inatoivo = (Int16)0;
            public const string sAtivo = @"Ativo";
            public const Int16 Ativo = (Int16)1;
        }

        public static class CORxDireitos
        {
            public const string sNA = @"NA";
            public const Int16 NA = (Int16)0;
            public const string sApagar = @"Apagar";
            public const Int16 Apagar = (Int16)5;
            public const string sInativar = @"Inativar";
            public const Int16 Inativar = (Int16)4;
            public const string sInserir = @"Inserir";
            public const Int16 Inserir = (Int16)2;
            public const string sVisualizar = @"Visualizar";
            public const Int16 Visualizar = (Int16)1;
            public const string sAlterar = @"Alterar";
            public const Int16 Alterar = (Int16)3;
        }

        public static class CORxRecursoTipo
        {
            public const string sAplicacao_de_UI = @"Aplicação de UI";
            public const Int16 Aplicacao_de_UI = (Int16)1;
            public const string sNA = @"NA";
            public const Int16 NA = (Int16)0;
            public const string sWeb_API = @"Web API";
            public const Int16 Web_API = (Int16)2;
        }
    }
}