//<auto-generated/>
using System;
using System.Linq;
using System.Collections.Generic;
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using TFX.Core;
using TFX.Core.Model;
using TFX.Core.Services;
using TFX.Core.Reflections;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.Extensions.DependencyInjection;
using TFX.Core.Exceptions;
using Microsoft.AspNetCore.Http;
using System.Data;
using TFX.Core.Lzma;
using TFX.Core.Identity;
using System.Text;
using Projecao.Core.ERP.ReadOnly.Rules;
using Projecao.Core.ERP.ReadOnly;

namespace Projecao.Core.ERP.ReadOnly
{
    [XGuid("1A5539DE-36CF-4423-8CCB-952EC72F7E76", typeof(IEmpresaService))]
    public class EmpresaService : XService, IEmpresaService
    {
        public class ERPxPessoaJuridica : XEntity
        {
            [Display(Name = "Estado")]
            [Required()]
            public Int16 CORxStatusID {get; set;}

            public Boolean IsPKEmpty => !ERPxPessoaJuridicaID.HasValue;
            [Display(Name = "Pessoa Jurídica")]
            [Required()]
            public Guid? ERPxPessoaJuridicaID {get; set;}

            [Display(Name = "Razão Social")]
            [MaxLength(160)]
            [Required()]
            public String RazaoSocial {get; set;}


            public CORxPessoa CORxPessoa {get; set;}
        }
        public class ERPxDocumento : XEntity
        {
            [Display(Name = "Pessoas")]
            [Required()]
            public Guid CORxPessoaID {get; set;}

            [Display(Name = "Estado")]
            [Required()]
            public Int16 CORxStatusID {get; set;}

            public Boolean IsPKEmpty => !ERPxDocumentoID.HasValue;
            [Display(Name = "Documento")]
            [Required()]
            public Guid? ERPxDocumentoID {get; set;}

            [Display(Name = "Tipo de Documento")]
            [Required()]
            public Int16 ERPxDocumentoTipoID {get; set;}

            [Display(Name = "Número")]
            [MaxLength(25)]
            [Required()]
            public String Numero {get; set;}


            public List<ERPxDocumentoTipo> ERPxDocumentoTipo {get; set;} = new List<ERPxDocumentoTipo>();

            public CORxPessoa CORxPessoa {get; set;}
        }
        public class ERPxDocumentoTipo : XEntity
        {
            public Boolean IsPKEmpty => Object.Equals(ERPxDocumentoTipoID, typeof(Int16).GetDefault());
            [Display(Name = "Tipo de Documento")]
            [Required()]
            [DatabaseGenerated(DatabaseGeneratedOption.None)]
            public Int16 ERPxDocumentoTipoID {get; set;}

            [Required()]
            public Int32 Filtro {get; set;}

            [Display(Name = "Máscara")]
            [MaxLength(30)]
            public String Mascara {get; set;}

            [Display(Name = "Tipo de Documento")]
            [MaxLength(25)]
            [Required()]
            public String Tipo {get; set;}


            public ERPxDocumento ERPxDocumento {get; set;}
        }
        public class CORxPessoa : XEntity
        {
            [Display(Name = "Localidade")]
            [Required()]
            public Int32 CEPxLocalidadePrincipalID {get; set;}

            public Boolean IsPKEmpty => !CORxPessoaID.HasValue;
            [Display(Name = "Pessoa")]
            [Required()]
            public Guid? CORxPessoaID {get; set;}

            [MaxLength(180)]
            [Required()]
            public String Nome {get; set;}


            public List<ERPxDocumento> ERPxDocumento {get; set;} = new List<ERPxDocumento>();

            public List<ERPxPessoaJuridica> ERPxPessoaJuridica {get; set;} = new List<ERPxPessoaJuridica>();
        }
        public class DBContext : XDBContext
        {
            public DBContext(DbContextOptions<DBContext> pOptions, XITenantProvider pTenantProvider, XISharedTransaction pSharedTransaction)
                   : base(pOptions, pTenantProvider, pSharedTransaction)
            {
            }

            public DbSet<ERPxPessoaJuridica> ERPxPessoaJuridica{get; set;}
            public DbSet<ERPxDocumento> ERPxDocumento{get; set;}
            public DbSet<ERPxDocumentoTipo> ERPxDocumentoTipo{get; set;}
            public DbSet<CORxPessoa> CORxPessoa{get; set;}

        private void ConfigureERPxPessoaJuridica(ModelBuilder pBuilder)
        {
            pBuilder.Entity<ERPxPessoaJuridica>(ett =>
            {
                ett.HasKey(e => e.ERPxPessoaJuridicaID).HasName("PK_ERPxPessoaJuridica");

                ett.Property(d => d.ERPxPessoaJuridicaID).HasColumnType(GetDBType("Guid"));
                ett.Property(d => d.CORxStatusID).HasColumnType(GetDBType("Int16"))
                    .HasDefaultValue(GetDBValue("Int16", (Int16)0));
                ett.Property(d => d.RazaoSocial).HasColumnType(GetDBType("String", 160))
                    .HasDefaultValue(GetDBValue("String", @"NI"));
                ett.ToTable("ERPxPessoaJuridica");
                ett.HasOne(d => d.CORxPessoa)
                   .WithMany(p => p.ERPxPessoaJuridica)
                   .HasForeignKey(d => d.ERPxPessoaJuridicaID)
                   .OnDelete(DeleteBehavior.Restrict);
            });
        }
        private void ConfigureERPxDocumento(ModelBuilder pBuilder)
        {
            pBuilder.Entity<ERPxDocumento>(ett =>
            {
                ett.HasKey(e => e.ERPxDocumentoID).HasName("PK_ERPxDocumento");

                ett.Property(d => d.ERPxDocumentoID).HasColumnType(GetDBType("Guid"));
                ett.Property(d => d.ERPxDocumentoTipoID).HasColumnType(GetDBType("Int16"));
                ett.Property(d => d.CORxPessoaID).HasColumnType(GetDBType("Guid"));
                ett.Property(d => d.Numero).HasColumnType(GetDBType("String", 25));
                ett.Property(d => d.CORxStatusID).HasColumnType(GetDBType("Int16"))
                    .HasDefaultValue(GetDBValue("Int16", (Int16)0));
                ett.ToTable("ERPxDocumento");
                ett.HasOne(d => d.CORxPessoa)
                   .WithMany(p => p.ERPxDocumento)
                   .HasForeignKey(d => d.CORxPessoaID)
                   .OnDelete(DeleteBehavior.Restrict);
            });
        }
        private void ConfigureERPxDocumentoTipo(ModelBuilder pBuilder)
        {
            pBuilder.Entity<ERPxDocumentoTipo>(ett =>
            {
                ett.HasKey(e => e.ERPxDocumentoTipoID).HasName("PK_ERPxDocumentoTipo");

                ett.Property(d => d.Tipo).HasColumnType(GetDBType("String", 25));
                ett.Property(d => d.ERPxDocumentoTipoID).HasColumnType(GetDBType("Int16"));
                ett.Property(d => d.Mascara).HasColumnType(GetDBType("String", 30)).IsRequired(false);
                ett.Property(d => d.Filtro).HasColumnType(GetDBType("Int32"));
                ett.ToTable("ERPxDocumentoTipo");
                ett.HasOne(d => d.ERPxDocumento)
                   .WithMany(p => p.ERPxDocumentoTipo)
                   .HasForeignKey(d => d.ERPxDocumentoTipoID)
                   .OnDelete(DeleteBehavior.Restrict);
            });
        }
        private void ConfigureCORxPessoa(ModelBuilder pBuilder)
        {
            pBuilder.Entity<CORxPessoa>(ett =>
            {
                ett.HasKey(e => e.CORxPessoaID).HasName("PK_CORxPessoa");

                ett.Property(d => d.CORxPessoaID).HasColumnType(GetDBType("Guid"));
                ett.Property(d => d.Nome).HasColumnType(GetDBType("String", 180));
                ett.Property(d => d.CEPxLocalidadePrincipalID).HasColumnType(GetDBType("Int32"));
                ett.ToTable("CORxPessoa");
            });
        }

            protected override void OnModelCreating(ModelBuilder pBuilder)
            {
                ConfigureERPxPessoaJuridica(pBuilder);
                ConfigureERPxDocumento(pBuilder);
                ConfigureERPxDocumentoTipo(pBuilder);
                ConfigureCORxPessoa(pBuilder);
                base.OnModelCreating(pBuilder);
            }

            protected override string GetConnectionString()
            {
                if (ConnectionString != null)
                    return ConnectionString;
                return XEnvironment.Read("SQL_SERVER_TFX", base.GetConnectionString());
            }
        }

        public abstract class BaseINFEmpresaServiceRule : XServiceINFRule<EmpresaService, EmpresaTuple>
        {
            public BaseINFEmpresaServiceRule(EmpresaService pService)
                : base(pService)
            {
            }
            protected DBContext Context
            {
                get;
                private set;
            }
            protected internal virtual T GetWhere<T>(T pQuery)
            {
                return pQuery;
            }
            internal void SetContext(DBContext pContext)
            {
                Context = pContext;
            }

        }

        public EmpresaService(ILogger<XService> pLogger, DBContext pContext)
               :base(pLogger)
        {
            Rule = new EmpresaRule(this);
            _INFRule = new INFEmpresaServiceRule(this);
            Context = pContext;
            _INFRule.SetContext(Context);
        }

        internal XIServiceRule<EmpresaTuple, EmpresaTuple> Rule;
        private INFEmpresaServiceRule _INFRule;

        public override Guid ID => new Guid("1A5539DE-36CF-4423-8CCB-952EC72F7E76");

        public DBContext Context
        {
            get;
        }

        public override void GracefullyClose()
        {
            Context.Commit();
        }
        public IQueryable<EmpresaTuple> ExecuteQuery(EmpresaFilter pFilter)
        {
            var ctx = Context;
            var query = from CORxPessoa in ctx.CORxPessoa
                        join ERPxDocumento in ctx.ERPxDocumento on CORxPessoa.CORxPessoaID equals ERPxDocumento.CORxPessoaID
                        join ERPxDocumentoTipo in ctx.ERPxDocumentoTipo on ERPxDocumento.ERPxDocumentoTipoID equals ERPxDocumentoTipo.ERPxDocumentoTipoID
                        join ERPxPessoaJuridica in ctx.ERPxPessoaJuridica on CORxPessoa.CORxPessoaID equals ERPxPessoaJuridica.ERPxPessoaJuridicaID
                        where ERPxDocumento.ERPxDocumentoTipoID == Projecao.Core.ERP.DB.ERPxModel.ERPxDocumentoTipo.CNPJ
                        select new {ERPxPessoaJuridica, ERPxDocumento, ERPxDocumentoTipo, CORxPessoa};
            query = _INFRule.GetWhere(query);


            if (!LoadAll)
            {
                if (pFilter?.SkipRows > 0)
                    query = query.Skip(pFilter.SkipRows.Value);

                if (pFilter?.TakeRows > 0)
                    query = query.Take(pFilter.TakeRows.Value);
                else
                    query = query.Take(75);
            }

            var qry = query.Select(q => new EmpresaTuple(q.CORxPessoa.Nome,
                             q.CORxPessoa.CORxPessoaID,
                             q.CORxPessoa.CEPxLocalidadePrincipalID,
                             q.ERPxDocumento.Numero,
                             q.ERPxDocumentoTipo.Mascara,
                             q.ERPxPessoaJuridica.RazaoSocial));
            return qry;
        }

        public EmpresaDataSet Execute(EmpresaFilter pFilter)
        {
            _INFRule.InternalBeforeExecute();
            var qry = ExecuteQuery(pFilter);
            var tuples = qry.ToList();
            tuples = Rule.InternalAfterSelect(tuples);
            _INFRule.InternalAfterExecute(tuples);
            var dataset = new EmpresaDataSet { Tuples = tuples };
            return dataset;
        }
    }
}