//<auto-generated/>
using System;
using System.Linq;
using Newtonsoft.Json;
using TFX.Core.Objects;
using TFX.Core.Model.Data;
using TFX.Core.Model.Cache;
using TFX.Core.Reflections;
using TFX.Core.Service.Job;
using TFX.Core.Service.SVC;
using Projecao.Core.CRD.DB;
using TFX.Core.Service.Apps;
using TFX.Core.Model.DIC.SVC;
using TFX.Core.Model.DIC.ORM;
using TFX.Core.Model.DIC.FRM;
using TFX.Core.Model.DIC.APP;
using TFX.Core.Model.DIC.RPT;
using TFX.Core.Model.Services;
using TFX.Core.Model.DIC.Types;
using TFX.Core.Model.Interfaces;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using Projecao.Core.CRD.GrupoDesconto;

namespace Projecao.Core.CRD.GrupoDesconto
{
    [XRegister(typeof(ConvenioEmpresaSVC), sCID)]
    [XDASESource(@"D:\Tootega\Source\TFX20\Modules\Projecao.Core.CRD\Projecao.Core.CRD.csproj", @"D:\Tootega\Source\TFX20\Modules\Projecao.Core.CRD\GrupoDesconto\ConvenioEmpresa.dssvc")]
    public class ConvenioEmpresaSVC : XSVCModel
    {
        #region ConvenioEmpresaFilterFRM

        [XRegister(typeof(ConvenioEmpresaFilterFRM), sCID)]
        public class ConvenioEmpresaFilterFRM : XFRMModel
        {
            public const String sCID = "E31B17DB-F60D-4DF9-8248-8BC97767A543";
            static ConvenioEmpresaFilterFRM()
            {
                gCID = new Guid(sCID);
            }
            public ConvenioEmpresaFilterFRM()
            {
                ID = gCID;
                Name = "ConvenioEmpresaFilter";
                Title = "";
                MinRows = 1;
                ConfigCID = new Guid("00000000-0000-0000-0000-000000000000");
                ConfigPKFilter = false;
                Rect = new XRect(0, 0, 1125, 92);
                Style = XFRMStyle.Normal;
                ActionContext = XActionContext.All;
                AddItem(Nome);
                Nome.ForceRW = true;
                Nome.CanInsert = true;
                Nome.CanUpdate = true;
                Nome.RowCount = 1;
                Nome.ColCount = 32;
                Nome.RowCountSmall = 1;
                Nome.ColCountSmall = 32;
                Nome.IsHidden = false;
                Nome.IsHiddenSmall = false;
                Nome.AdditionalTitle = "";
                Nome.Location = 1;
                Nome.EditorCID = new Guid("F5982E79-BA45-40FB-85E1-9F2C8B90B6EF");
                Nome.FormImplace = true;
                Nome.Operator = XOperator.Like;
                Nome.JustifyHeight = false;
                Nome.AllowEmpty = true;
                Nome.FontColor = "#000000";
                Nome.FontStyle = XFontStyle.Normal;
                Nome.ShowFooter = false;
                Nome.ViewSAM = new Guid("00000000-0000-0000-0000-000000000000");
                Nome.Scale = 0;
                Nome.Length = 256;
                Nome.SearchAction = XSearchAction.Default;
                Nome.TypeID = XString.CID;
                Nome.AdditionalFieldsID = new Guid[] { new Guid("F08FE609-6332-44C8-A569-CA9D51765F56") };
                Nome.AdditionalDataFieldsID = new Guid[] {  };
                Nome.TargetFilterFieldID = new Guid[] {  };
                Nome.SourceFilterFieldID = new Guid[] {  };
                Nome.TargetDisplayFieldID = new Guid[] {  };
                Nome.SourceDisplayFieldID = new Guid[] {  };
                Nome.AutoLoad = false;
                Nome.FilterInative = true;
                Nome.IsAnswer = false;
                Nome.AllowMultiSelect = false;
            }
            public XFRMField Nome = new XFRMField(new Guid("74CC1CA8-7DE7-4C7A-BF4D-0E9E11722C74"), "Nome", "Nome do Convênio/Empresa", XString.CID, 1, 32, false, gCID, null, new Guid("73F6EBB1-2FCA-4C97-B63C-45AC0E84F7D2")); // String;
            public static class Fields
            {
                public static XFieldInfo Nome = new XFieldInfo(new Guid("74CC1CA8-7DE7-4C7A-BF4D-0E9E11722C74"), "Nome", "Nome do Convênio/Empresa", typeof(String));
            }
        }

        #endregion ConvenioEmpresaFilterFRM

        public const String sCID = "55CB95C5-10DF-449F-943E-9A0D38C512D0";
        public static Guid gCID = new Guid(sCID);
        public static XSVCReference SYSxPessoaConvenio_SYSxPessoaID_CRDxConvenio_CRDxConvenioID; // SYSxPessoaConvenio.SYSxPessoaID --> CRDxConvenio.CRDxConvenioID
        public static XSVCReference CRDxConvenioEmpresa_SYSxProprietariaID_SYSxEmpresa_SYSxEmpresaID; // CRDxConvenioEmpresa.SYSxProprietariaID --> SYSxEmpresa.SYSxEmpresaID
        public static XSVCReference CRDxConvenioEmpresa_CRDxConvenioID_CRDxConvenio_CRDxConvenioID; // CRDxConvenioEmpresa.CRDxConvenioID --> CRDxConvenio.CRDxConvenioID
        public static XSVCReference SYSxEmpresa_SYSxEmpresaID_SYSxPessoa_SYSxPessoaID; // SYSxEmpresa.SYSxEmpresaID --> SYSxPessoa.SYSxPessoaID

        #region xSYSxEmpresa 
        public class xSYSxEmpresa : XSVCTable
        {

            public static Guid gCID => new Guid("1881542E-8242-4843-87B3-38E06F85A64F");

            public xSYSxEmpresa()
            {
                Name = "SYSxEmpresa";
                Alias = "SYSxEmpresa";
                ID = gCID;
                ParentID =  global::TFX.Core.Service.Apps.SYSx.SYSxEmpresa.gCID;

                Items.Add(Sigla, Sigla.ID);
                Sigla.Owner = this;
                Sigla.OwnerID = ID;
                Sigla.TableName = Name;
                Sigla.Alias = "Sigla";
                Items.Add(SYSxEmpresaID, SYSxEmpresaID.ID);
                SYSxEmpresaID.Owner = this;
                SYSxEmpresaID.OwnerID = ID;
                SYSxEmpresaID.TableName = Name;
                Items.Add(SYSxEstadoID, SYSxEstadoID.ID);
                SYSxEstadoID.Owner = this;
                SYSxEstadoID.OwnerID = ID;
                SYSxEstadoID.TableName = Name;
                Items.Add(SYSxEmpresaMatrizID, SYSxEmpresaMatrizID.ID);
                SYSxEmpresaMatrizID.Owner = this;
                SYSxEmpresaMatrizID.OwnerID = ID;
                SYSxEmpresaMatrizID.TableName = Name;
                Items.Add(SYSxEmpresaGrupoID, SYSxEmpresaGrupoID.ID);
                SYSxEmpresaGrupoID.Owner = this;
                SYSxEmpresaGrupoID.OwnerID = ID;
                SYSxEmpresaGrupoID.TableName = Name;
            }

            public static XORMFaceField Sigla = new XORMFaceField(global::TFX.Core.Service.Apps.SYSx.SYSxEmpresa.Sigla, new Guid("53994D69-FD6D-4C74-8CF6-55A39B7D9D07"), "Sigla", "Sigla");
            public static XORMPKField SYSxEmpresaID = new XORMPKField(global::TFX.Core.Service.Apps.SYSx.SYSxEmpresa.SYSxEmpresaID, new Guid("3F021CE1-7A94-4F33-A7CA-B5523CF3CEF8"), "SYSxEmpresaID", "Empresa");
            public static XORMStateField SYSxEstadoID = new XORMStateField(global::TFX.Core.Service.Apps.SYSx.SYSxEmpresa.SYSxEstadoID, new Guid("485C0B18-B37F-404D-B74F-4AE0E7CB52B6"), "SYSxEstadoID", "Estado");
            public static XORMFKField SYSxEmpresaMatrizID = new XORMFKField(global::TFX.Core.Service.Apps.SYSx.SYSxEmpresa.SYSxEmpresaMatrizID, new Guid("D61D59A8-1EFC-4222-B2DF-DE8157126755"), "SYSxEmpresaMatrizID", "Empresa");
            public static XORMFKField SYSxEmpresaGrupoID = new XORMFKField(global::TFX.Core.Service.Apps.SYSx.SYSxEmpresa.SYSxEmpresaGrupoID, new Guid("5D22C100-C4D4-491D-88EF-147C7B7DECFD"), "SYSxEmpresaGrupoID", "Grupo de Empresas");
        }
        #endregion xSYSxEmpresa 


        #region xCRDxConvenio 
        public class xCRDxConvenio : XSVCTable
        {

            public static Guid gCID => new Guid("3574FBB6-B8BF-4F91-91F3-A0DFDE1D258A");

            public xCRDxConvenio()
            {
                Name = "CRDxConvenio";
                Alias = "CRDxConvenio";
                ID = gCID;
                ParentID =  global::Projecao.Core.CRD.DB.CRDx.CRDxConvenio.gCID;

                Items.Add(CRDxConvenioID, CRDxConvenioID.ID);
                CRDxConvenioID.Owner = this;
                CRDxConvenioID.OwnerID = ID;
                CRDxConvenioID.TableName = Name;
                CRDxConvenioID.Alias = "CRDxConvenioID";
                Items.Add(Inicio, Inicio.ID);
                Inicio.Owner = this;
                Inicio.OwnerID = ID;
                Inicio.TableName = Name;
                Items.Add(Pagamento, Pagamento.ID);
                Pagamento.Owner = this;
                Pagamento.OwnerID = ID;
                Pagamento.TableName = Name;
                Items.Add(Fechamento, Fechamento.ID);
                Fechamento.Owner = this;
                Fechamento.OwnerID = ID;
                Fechamento.TableName = Name;
                Items.Add(SYSxEstadoID, SYSxEstadoID.ID);
                SYSxEstadoID.Owner = this;
                SYSxEstadoID.OwnerID = ID;
                SYSxEstadoID.TableName = Name;
                Items.Add(CRDxConvenioTipoID, CRDxConvenioTipoID.ID);
                CRDxConvenioTipoID.Owner = this;
                CRDxConvenioTipoID.OwnerID = ID;
                CRDxConvenioTipoID.TableName = Name;
            }

            public static XORMFaceField CRDxConvenioID = new XORMFaceField(global::Projecao.Core.CRD.DB.CRDx.CRDxConvenio.CRDxConvenioID, new Guid("B0CA8377-8765-4C48-A32B-D7734BDFFA7E"), "CRDxConvenioID", "Convênio");
            public static XORMDateTimeField Inicio = new XORMDateTimeField(global::Projecao.Core.CRD.DB.CRDx.CRDxConvenio.Inicio, new Guid("D664DAF2-AB19-4330-BBB1-ACD83CF707D9"), "Inicio", "Início");
            public static XORMField Pagamento = new XORMField(global::Projecao.Core.CRD.DB.CRDx.CRDxConvenio.Pagamento, new Guid("70AC1FA3-3FBC-4065-B3CC-B4A9F76579A2"), "Pagamento", "Dia de Pagamento");
            public static XORMField Fechamento = new XORMField(global::Projecao.Core.CRD.DB.CRDx.CRDxConvenio.Fechamento, new Guid("D9D9B681-B075-42C8-AC67-E24B5E34DE0E"), "Fechamento", "Dia de Fechamento");
            public static XORMStateField SYSxEstadoID = new XORMStateField(global::Projecao.Core.CRD.DB.CRDx.CRDxConvenio.SYSxEstadoID, new Guid("5CCDF836-B5BB-43B8-8BBF-E700CDDE279D"), "SYSxEstadoID", "Estado");
            public static XORMFKField CRDxConvenioTipoID = new XORMFKField(global::Projecao.Core.CRD.DB.CRDx.CRDxConvenio.CRDxConvenioTipoID, new Guid("F6B1643B-F7C8-4CBB-8937-357DF4C503F2"), "CRDxConvenioTipoID", "Tipo de Convênio");
        }
        #endregion xCRDxConvenio 


        #region xSYSxPessoa 
        public class xSYSxPessoa : XSVCTable
        {

            public static Guid gCID => new Guid("3C69486A-2C69-416B-B34E-E395591C2FDB");

            public xSYSxPessoa()
            {
                Name = "SYSxPessoa";
                Alias = "SYSxPessoa";
                ID = gCID;
                ParentID =  global::TFX.Core.Service.Apps.SYSx.SYSxPessoa.gCID;

                Items.Add(Nome, Nome.ID);
                Nome.Owner = this;
                Nome.OwnerID = ID;
                Nome.TableName = Name;
                Nome.Alias = "Nome";
                Items.Add(SYSxPessoaID, SYSxPessoaID.ID);
                SYSxPessoaID.Owner = this;
                SYSxPessoaID.OwnerID = ID;
                SYSxPessoaID.TableName = Name;
            }

            public static XORMFaceField Nome = new XORMFaceField(global::TFX.Core.Service.Apps.SYSx.SYSxPessoa.Nome, new Guid("2AD6286E-A1E5-4E20-BD37-878DA068D23D"), "Nome", "Empresa Participante");
            public static XORMPKField SYSxPessoaID = new XORMPKField(global::TFX.Core.Service.Apps.SYSx.SYSxPessoa.SYSxPessoaID, new Guid("E1211333-C9FE-4C5B-B323-8C22C26E142A"), "SYSxPessoaID", "Pessoas");
        }
        #endregion xSYSxPessoa 


        #region xCRDxConvenioEmpresa 
        public class xCRDxConvenioEmpresa : XSVCTable
        {

            public static Guid gCID => new Guid("6B249B00-8863-43B4-A098-426049F82B08");

            public xCRDxConvenioEmpresa()
            {
                Name = "CRDxConvenioEmpresa";
                Alias = "CRDxConvenioEmpresa";
                ID = gCID;
                ParentID =  global::Projecao.Core.CRD.DB.CRDx.CRDxConvenioEmpresa.gCID;

                Items.Add(SYSxProprietariaID, SYSxProprietariaID.ID);
                SYSxProprietariaID.Owner = this;
                SYSxProprietariaID.OwnerID = ID;
                SYSxProprietariaID.TableName = Name;
                SYSxProprietariaID.Alias = "SYSxProprietariaID";
                Items.Add(CRDxConvenioID, CRDxConvenioID.ID);
                CRDxConvenioID.Owner = this;
                CRDxConvenioID.OwnerID = ID;
                CRDxConvenioID.TableName = Name;
                Items.Add(CRDxConvenioEmpresaID, CRDxConvenioEmpresaID.ID);
                CRDxConvenioEmpresaID.Owner = this;
                CRDxConvenioEmpresaID.OwnerID = ID;
                CRDxConvenioEmpresaID.TableName = Name;
                CRDxConvenioEmpresaID.Alias = "CRDxConvenioEmpresaID";
                Items.Add(SYSxEstadoID, SYSxEstadoID.ID);
                SYSxEstadoID.Owner = this;
                SYSxEstadoID.OwnerID = ID;
                SYSxEstadoID.TableName = Name;
            }

            public static XORMFKField SYSxProprietariaID = new XORMFKField(global::Projecao.Core.CRD.DB.CRDx.CRDxConvenioEmpresa.SYSxProprietariaID, new Guid("AB0B4C20-6CBC-40C4-BAAD-DB4F7568973E"), "SYSxProprietariaID", "Empresa");
            public static XORMFKField CRDxConvenioID = new XORMFKField(global::Projecao.Core.CRD.DB.CRDx.CRDxConvenioEmpresa.CRDxConvenioID, new Guid("497FD29C-F01A-4868-B2BC-8D06DD47BD22"), "CRDxConvenioID", "Convênio");
            public static XORMPKField CRDxConvenioEmpresaID = new XORMPKField(global::Projecao.Core.CRD.DB.CRDx.CRDxConvenioEmpresa.CRDxConvenioEmpresaID, new Guid("7D08576E-8C1F-448E-B5D5-5F2F8D4EC8D7"), "CRDxConvenioEmpresaID", "Empresas por Convênio");
            public static XORMStateField SYSxEstadoID = new XORMStateField(global::Projecao.Core.CRD.DB.CRDx.CRDxConvenioEmpresa.SYSxEstadoID, new Guid("E33F06DA-8FFA-4FDC-9FF0-8D509DF1B3F6"), "SYSxEstadoID", "Estado");
        }
        #endregion xCRDxConvenioEmpresa 


        #region xSYSxPessoaConvenio 
        public class xSYSxPessoaConvenio : XSVCTable
        {

            public static Guid gCID => new Guid("9FB72C74-18CE-473F-8740-64E455D947C9");

            public xSYSxPessoaConvenio()
            {
                Name = "SYSxPessoa";
                Alias = "SYSxPessoaConvenio";
                ID = gCID;
                ParentID =  global::TFX.Core.Service.Apps.SYSx.SYSxPessoa.gCID;

                Items.Add(Nome, Nome.ID);
                Nome.Owner = this;
                Nome.OwnerID = ID;
                Nome.TableName = Name;
                Nome.Alias = "NomeConvenio";
                Items.Add(SYSxPessoaID, SYSxPessoaID.ID);
                SYSxPessoaID.Owner = this;
                SYSxPessoaID.OwnerID = ID;
                SYSxPessoaID.TableName = Name;
            }

            public static XORMFaceField Nome = new XORMFaceField(global::TFX.Core.Service.Apps.SYSx.SYSxPessoa.Nome, new Guid("73F6EBB1-2FCA-4C97-B63C-45AC0E84F7D2"), "Nome", "Nome do Convênio");
            public static XORMPKField SYSxPessoaID = new XORMPKField(global::TFX.Core.Service.Apps.SYSx.SYSxPessoa.SYSxPessoaID, new Guid("996D9956-05BE-4160-B92C-BA84488C71C8"), "SYSxPessoaID", "Pessoas");
        }
        #endregion xSYSxPessoaConvenio 


        public xCRDxConvenio CRDxConvenio;
        public xCRDxConvenioEmpresa CRDxConvenioEmpresa;
        public xSYSxEmpresa SYSxEmpresa;
        public xSYSxPessoa SYSxPessoa;
        public xSYSxPessoaConvenio SYSxPessoaConvenio;

        public ConvenioEmpresaSVC()
        {
            TupleType = typeof(ConvenioEmpresaSVC.XTuple);
            DataSetType = typeof(ConvenioEmpresaSVC.XDataSet);
            ServiceRuleCID = new Guid("F77163B2-EB8D-4945-8700-0B3D845A212F");
            OnlyActives = false;
            Actions = XSVCAction.All;
            Type = XServiceType.Default;
            ID = new Guid("55CB95C5-10DF-449F-943E-9A0D38C512D0");
            Name = "ConvenioEmpresa";
            Title = "Convênios e Empresas";
            IsCacheable = false;
            CompanyControl = false;
            IsJob = false;
            AutoLoad = true;
            FreeForUsers = false;
            ServerSideNewRecord = false;
            UseDistinct = false;
            JobType = XJobType.Default;
            CanExport = false;
            ModuleID = new Guid("EBB5930C-9A21-4AB6-993E-B86F40039784");
            Rights = new Int16[] { 1 }; 
            FilterFormID = new Guid("E31B17DB-F60D-4DF9-8248-8BC97767A543");
            IsReadOnly = true;
            ClientScript = "Projecao.Core.CRD.js";
            GridFields = new Guid[] { xSYSxPessoaConvenio.Nome.ID, xSYSxEmpresa.Sigla.ID, xSYSxPessoa.Nome.ID };
            OrderByFields = new Guid[] { xSYSxPessoaConvenio.Nome.ID, xSYSxEmpresa.Sigla.ID };
            DataSetFields = new Guid[] { xSYSxEmpresa.Sigla.ID, xSYSxPessoa.Nome.ID, xSYSxPessoaConvenio.Nome.ID, xCRDxConvenioEmpresa.SYSxProprietariaID.ID, xCRDxConvenio.CRDxConvenioID.ID, xCRDxConvenioEmpresa.CRDxConvenioEmpresaID.ID };
            PKField = xCRDxConvenioEmpresa.CRDxConvenioEmpresaID.ID;
            ConfigTableID = new Guid("A7625E52-5208-49D4-AE45-87CFEA28EDDA");
            MasterRuleCID = new Guid("F77163B2-EB8D-4945-8700-0B3D845A212F");
            XSubServiceItem ss4C04B56762A84F6DA27C7867ABF95D15 = new XSubServiceItem(GrupoDescontoSVC.gCID, GrupoDescontoSVC.xCRDxConvenioGrupo.SYSxFilialID.ID, ConvenioEmpresaSVC.gCID, xCRDxConvenioEmpresa.SYSxProprietariaID.ID, true, XSubSeviceType.Default);
            ss4C04B56762A84F6DA27C7867ABF95D15.Rights = new Int16[] { 1 }; 
            ss4C04B56762A84F6DA27C7867ABF95D15.LateLoad = false;
            SubServices.Add(ss4C04B56762A84F6DA27C7867ABF95D15);
            CRDxConvenio = new xCRDxConvenio();
            CRDxConvenio.IsReadOnly = true;
            AddTable(CRDxConvenio);
            CRDxConvenioEmpresa = new xCRDxConvenioEmpresa();
            CRDxConvenioEmpresa.IsReadOnly = true;
            AddTable(CRDxConvenioEmpresa);
            SYSxEmpresa = new xSYSxEmpresa();
            SYSxEmpresa.IsReadOnly = true;
            AddTable(SYSxEmpresa);
            SYSxPessoa = new xSYSxPessoa();
            SYSxPessoa.IsReadOnly = true;
            AddTable(SYSxPessoa);
            SYSxPessoaConvenio = new xSYSxPessoaConvenio();
            SYSxPessoaConvenio.IsReadOnly = true;
            AddTable(SYSxPessoaConvenio);
            MasterTableID = CRDxConvenioEmpresa.ID;
            SYSxPessoaConvenio_SYSxPessoaID_CRDxConvenio_CRDxConvenioID = AddReference(new XSVCReference(new Guid("282D9004-C2A8-45C3-A87B-AD05B8050889"), "FK_282D9004C2A845C3A87BAD05B8050889", ConvenioEmpresaSVC.xSYSxPessoaConvenio.gCID, xSYSxPessoaConvenio.SYSxPessoaID.ID, ConvenioEmpresaSVC.xCRDxConvenio.gCID, xCRDxConvenio.CRDxConvenioID.ID, XJoinType.Inner)); // SYSxPessoaConvenio.SYSxPessoaID --> CRDxConvenio.CRDxConvenioID
            CRDxConvenioEmpresa_SYSxProprietariaID_SYSxEmpresa_SYSxEmpresaID = AddReference(new XSVCReference(new Guid("3C292A8A-9B43-4092-9E0E-E8564DB341F4"), "FK_3C292A8A9B4340929E0EE8564DB341F4", ConvenioEmpresaSVC.xCRDxConvenioEmpresa.gCID, xCRDxConvenioEmpresa.SYSxProprietariaID.ID, ConvenioEmpresaSVC.xSYSxEmpresa.gCID, xSYSxEmpresa.SYSxEmpresaID.ID, XJoinType.Inner)); // CRDxConvenioEmpresa.SYSxProprietariaID --> SYSxEmpresa.SYSxEmpresaID
            CRDxConvenioEmpresa_CRDxConvenioID_CRDxConvenio_CRDxConvenioID = AddReference(new XSVCReference(new Guid("4ABB4DDD-0A9B-441F-8432-E23CE5EC18B4"), "FK_4ABB4DDD0A9B441F8432E23CE5EC18B4", ConvenioEmpresaSVC.xCRDxConvenioEmpresa.gCID, xCRDxConvenioEmpresa.CRDxConvenioID.ID, ConvenioEmpresaSVC.xCRDxConvenio.gCID, xCRDxConvenio.CRDxConvenioID.ID, XJoinType.Inner)); // CRDxConvenioEmpresa.CRDxConvenioID --> CRDxConvenio.CRDxConvenioID
            SYSxEmpresa_SYSxEmpresaID_SYSxPessoa_SYSxPessoaID = AddReference(new XSVCReference(new Guid("A0FD3D5E-2D62-4BC9-95F5-7D6791E5CC51"), "FK_A0FD3D5E2D624BC995F57D6791E5CC51", ConvenioEmpresaSVC.xSYSxEmpresa.gCID, xSYSxEmpresa.SYSxEmpresaID.ID, ConvenioEmpresaSVC.xSYSxPessoa.gCID, xSYSxPessoa.SYSxPessoaID.ID, XJoinType.Inner)); // SYSxEmpresa.SYSxEmpresaID --> SYSxPessoa.SYSxPessoaID
            XSVCReference FK_09ECC850663E4B2D9A13F060FFA631C6 = new XSVCReference(new Guid("09ECC850-663E-4B2D-9A13-F060FFA631C6"), "FK_09ECC850663E4B2D9A13F060FFA631C6", GrupoDescontoSVC.gCID, GrupoDescontoSVC.xCRDxConvenioGrupo.SYSxFilialID.ID, CRDxConvenioEmpresa.ID, ConvenioEmpresaSVC.xCRDxConvenioEmpresa.SYSxProprietariaID.ID, XJoinType.SubService); // GrupoDescontoSVC.SYSxFilialID --> ConvenioEmpresa.SYSxProprietariaID
            FK_09ECC850663E4B2D9A13F060FFA631C6.IsLowRelevance = false;
            AddReference(FK_09ECC850663E4B2D9A13F060FFA631C6);
            XSVCReference FK_7904EB46CEE84E11BD8722262C60F90F = new XSVCReference(new Guid("7904EB46-CEE8-4E11-BD87-22262C60F90F"), "FK_7904EB46CEE84E11BD8722262C60F90F", GrupoDescontoSVC.gCID, GrupoDescontoSVC.xCRDxConvenioGrupo.CRDxConvenioID.ID, CRDxConvenio.ID, ConvenioEmpresaSVC.xCRDxConvenio.CRDxConvenioID.ID, XJoinType.SubService); // GrupoDescontoSVC.CRDxConvenioID --> ConvenioEmpresa.CRDxConvenioID
            FK_7904EB46CEE84E11BD8722262C60F90F.IsLowRelevance = false;
            AddReference(FK_7904EB46CEE84E11BD8722262C60F90F);
            xCRDxConvenioEmpresa.CRDxConvenioEmpresaID.IsReadOnly = true;
            xCRDxConvenioEmpresa.CRDxConvenioEmpresaID.IsDataField = true;
            xCRDxConvenioEmpresa.CRDxConvenioEmpresaID.AllowEmpty = true;
            xCRDxConvenio.CRDxConvenioID.IsReadOnly = true;
            xCRDxConvenio.CRDxConvenioID.IsDataField = true;
            xCRDxConvenio.CRDxConvenioID.AllowEmpty = true;
            xSYSxPessoa.Nome.IsReadOnly = true;
            xSYSxPessoa.Nome.Length = 256;
            xSYSxPessoa.Nome.IsDataField = true;
            xSYSxPessoa.Nome.AllowEmpty = true;
            xSYSxPessoaConvenio.Nome.IsReadOnly = true;
            xSYSxPessoaConvenio.Nome.OrderType = XOrderType.Asc;
            xSYSxPessoaConvenio.Nome.Length = 256;
            xSYSxPessoaConvenio.Nome.IsDataField = true;
            xSYSxPessoaConvenio.Nome.AllowEmpty = true;
            xSYSxEmpresa.Sigla.IsReadOnly = true;
            xSYSxEmpresa.Sigla.OrderType = XOrderType.Asc;
            xSYSxEmpresa.Sigla.Length = 25;
            xSYSxEmpresa.Sigla.IsDataField = true;
            xSYSxEmpresa.Sigla.AllowEmpty = true;
            xCRDxConvenioEmpresa.SYSxProprietariaID.IsReadOnly = true;
            xCRDxConvenioEmpresa.SYSxProprietariaID.IsDataField = true;
            xCRDxConvenioEmpresa.SYSxProprietariaID.AllowEmpty = true;
        }

        #region XFields

        public class XFields
        {
        public XORMField CRDxConvenioEmpresaID => xCRDxConvenioEmpresa.CRDxConvenioEmpresaID;
        public XORMField CRDxConvenioID => xCRDxConvenio.CRDxConvenioID;
        public XORMField Nome => xSYSxPessoa.Nome;
        public XORMField NomeConvenio => xSYSxPessoaConvenio.Nome;
        public XORMField Sigla => xSYSxEmpresa.Sigla;
        public XORMField SYSxProprietariaID => xCRDxConvenioEmpresa.SYSxProprietariaID;
        }
        #endregion XFields
        #region ConvenioEmpresaSVC.XTuple

        public  class XTuple : XDataTuple
        {

            public XTuple()
            {
            }

            public XTuple(Object[] pSource)
                : base(pSource)
            {
            }

            public XTuple(Int32 pColCount)
               : this(new Object[pColCount])
            {
            }

            public readonly XFields Fields = new XFields();

            #nullable enable

        public Int32 CRDxConvenioEmpresaID
        {
            get
            {
                return (Int32)Value[ConvenioEmpresaSVC.xCRDxConvenioEmpresa.CRDxConvenioEmpresaID.ID];
            }
            set
            {
                Value[ConvenioEmpresaSVC.xCRDxConvenioEmpresa.CRDxConvenioEmpresaID.ID] = value;
            }
        }
        public Int32? oCRDxConvenioEmpresaID
        {
            get
            {
                GetOldValue(ConvenioEmpresaSVC.xCRDxConvenioEmpresa.CRDxConvenioEmpresaID, out Object ovlr);
                return (Int32?)ovlr;
            }
        }

        public Guid CRDxConvenioID
        {
            get
            {
                return (Guid)Value[ConvenioEmpresaSVC.xCRDxConvenio.CRDxConvenioID.ID];
            }
            set
            {
                Value[ConvenioEmpresaSVC.xCRDxConvenio.CRDxConvenioID.ID] = value;
            }
        }
        public Guid? oCRDxConvenioID
        {
            get
            {
                GetOldValue(ConvenioEmpresaSVC.xCRDxConvenio.CRDxConvenioID, out Object ovlr);
                return (Guid?)ovlr;
            }
        }

        public String Nome
        {
            get
            {
                return (String)Value[ConvenioEmpresaSVC.xSYSxPessoa.Nome.ID];
            }
            set
            {
                Value[ConvenioEmpresaSVC.xSYSxPessoa.Nome.ID] = value;
            }
        }
        public String? oNome
        {
            get
            {
                GetOldValue(ConvenioEmpresaSVC.xSYSxPessoa.Nome, out Object ovlr);
                return (String?)ovlr;
            }
        }

        public String NomeConvenio
        {
            get
            {
                return (String)Value[ConvenioEmpresaSVC.xSYSxPessoaConvenio.Nome.ID];
            }
            set
            {
                Value[ConvenioEmpresaSVC.xSYSxPessoaConvenio.Nome.ID] = value;
            }
        }
        public String? oNomeConvenio
        {
            get
            {
                GetOldValue(ConvenioEmpresaSVC.xSYSxPessoaConvenio.Nome, out Object ovlr);
                return (String?)ovlr;
            }
        }

        public String Sigla
        {
            get
            {
                return (String)Value[ConvenioEmpresaSVC.xSYSxEmpresa.Sigla.ID];
            }
            set
            {
                Value[ConvenioEmpresaSVC.xSYSxEmpresa.Sigla.ID] = value;
            }
        }
        public String? oSigla
        {
            get
            {
                GetOldValue(ConvenioEmpresaSVC.xSYSxEmpresa.Sigla, out Object ovlr);
                return (String?)ovlr;
            }
        }

        public Guid SYSxProprietariaID
        {
            get
            {
                return (Guid)Value[ConvenioEmpresaSVC.xCRDxConvenioEmpresa.SYSxProprietariaID.ID];
            }
            set
            {
                Value[ConvenioEmpresaSVC.xCRDxConvenioEmpresa.SYSxProprietariaID.ID] = value;
            }
        }
        public Guid? oSYSxProprietariaID
        {
            get
            {
                GetOldValue(ConvenioEmpresaSVC.xCRDxConvenioEmpresa.SYSxProprietariaID, out Object ovlr);
                return (Guid?)ovlr;
            }
        }

            #nullable disable
        }
        #endregion ConvenioEmpresaSVC.XTuple

        #region ConvenioEmpresaSVC.XRule
        public abstract class XRule : XServiceRule<ConvenioEmpresaSVC.XDataSet, ConvenioEmpresaSVC, ConvenioEmpresaSVC.XTuple>
        {
        }
        #endregion ConvenioEmpresaSVC.XRule

        #region ConvenioEmpresaSVC.XDataSet

        public class XDataSet : XDataSet<ConvenioEmpresaSVC.XTuple>
        {
            public XDataSet()
            {
                DataSetType = typeof(ConvenioEmpresaSVC.XDataSet);
            }
        }

        public class XDataSet<T> : XServiceDataSet<ConvenioEmpresaSVC.XTuple> where T : XDataTuple
        {

            public Guid CRDxConvenioEmpresaID => ConvenioEmpresaSVC.xCRDxConvenioEmpresa.CRDxConvenioEmpresaID.ID;
            public Guid CRDxConvenioID => ConvenioEmpresaSVC.xCRDxConvenio.CRDxConvenioID.ID;
            public Guid Nome => ConvenioEmpresaSVC.xSYSxPessoa.Nome.ID;
            public Guid NomeConvenio => ConvenioEmpresaSVC.xSYSxPessoaConvenio.Nome.ID;
            public Guid Sigla => ConvenioEmpresaSVC.xSYSxEmpresa.Sigla.ID;
            public Guid SYSxProprietariaID => ConvenioEmpresaSVC.xCRDxConvenioEmpresa.SYSxProprietariaID.ID;

            public XDataSet()
            {
                DataSetType = typeof(ConvenioEmpresaSVC.XDataSet);
            }

            private Projecao.Core.CRD.GrupoDesconto.GrupoDescontoSVC.XDataSet _GrupoDescontoDataSet;

            public Projecao.Core.CRD.GrupoDesconto.GrupoDescontoSVC.XDataSet GrupoDescontoDataSet
            {
                get
                {
                    if (_GrupoDescontoDataSet == null)
                    {
                        _GrupoDescontoDataSet = (Projecao.Core.CRD.GrupoDesconto.GrupoDescontoSVC.XDataSet)Children.Get(Projecao.Core.CRD.GrupoDesconto.GrupoDescontoSVC.gCID);
                        _GrupoDescontoDataSet.IsReadOnly = true;
                    }
                    return  _GrupoDescontoDataSet;
                }
            }

        }
        #endregion ConvenioEmpresaSVC.XDataSet

        [Guid(ConvenioEmpresaSVC.sCID)]
        public  interface XService : XIBaseService
        {
            new XDataSet DataSet
            {
                get;
            }
            new XTuple NewTuple(Object pPKValue = null);
             IEnumerable<XTuple> Tuples
            {
                get;
            }
             XTuple Current
            {
                get;
            }
            new XDataSet Get(XServiceData pData);
             XDataSet Get(params Object[] pWhere);
        }
        [XRegister(typeof(_Service), _Service.sCID, typeof(ConvenioEmpresaSVC))]
        protected class _Service : Service<ConvenioEmpresaSVC, XDataSet, XTuple>
        {
            public const String sCID = "4DB77D80-A1B6-464C-BB95-A68FAA3E5003";
            public Guid gCID = new Guid(sCID);
        }

        public class Service<TModel, TDataSet, TTuple> : XBaseService<ConvenioEmpresaSVC, XDataSet, XTuple>, XService
             where TModel : ConvenioEmpresaSVC, new()
             where TDataSet : XDataSet, new()
             where TTuple : XTuple
        {
            XDataSet XService.DataSet => (XDataSet)DataSet;
            XTuple XService.NewTuple(Object pPKValue)
            {
                return (XTuple)NewTuple(pPKValue);
            }
            public new XDataTuple NewTuple(Object pPKValue = null)
            {
                return (XTuple)base.NewTuple(pPKValue);
            }
            IEnumerable<XTuple> XService.Tuples => (IEnumerable<XTuple>)Tuples;
            XTuple XService.Current => (XTuple )Current;
            XDataSet XService.Get(XServiceData pData)
            {
                return (XDataSet)Get(pData);
            }
            XDataSet XService.Get(params Object[] pWhere)
            {
                return (XDataSet)Get(pWhere);
            }
            public Service()
            {
                ID = gCID;
            }
        }
    }

}