//<auto-generated/>
using System;
using TFX.Core.DB;
using TFX.Core.Model;
using TFX.Core.Model.FRM;

namespace Tootega.Core.ERP.Pessoa
{
    public class FRMDocumento : XFRMModel
    {
        public FRMDocumento()
        {
            ID = new Guid("365723DF-452C-48A8-A12B-89091137D98B");
            Name = "Documento";
            Title = "";
            MinRows = 2;
            Style = XFRMStyle.Normal;
            Type = XFRMType.StandAlone;
            XFRMField fld;
            fld = AddField(new XFRMField());
            fld.Name = "ERPxDocumentoTipoID";
            fld.Title = "Tipo de Documento";
            fld.CanInsert = true;
            fld.CanUpdate = true;
            fld.RowCount = 2;
            fld.ColCount = 14;
            fld.IsHidden = false;
            fld.DataSourceID = new Guid("F3E35F4C-5EB3-4E7D-B7C8-C879EE1414A6");
            fld.Location = 1;
            fld.EditorCID = XModelEditors.XStaticCombo;
            fld.Operator = XOperator.EqualTo;
            fld.JustifyHeight = false;
            fld.AllowEmpty = true;
            fld.FontColor = "#000000";
            fld.FontStyle = XFontStyle.Normal;
            fld.ShowFooter = false;
            fld.ViewSAM = new Guid("00000000-0000-0000-0000-000000000000");
            fld.Order = 1;
            fld.Scale = -1;
            fld.Length = -1;
            fld.TypeID = XDataTypes.XInt16;
            fld.AdditionalFieldsID = new Guid[] {  };
            fld.AdditionalDataFieldsID = new Guid[] {  };
            fld.TargetFilterFieldID = new Guid[] {  };
            fld.SourceFilterFieldID = new Guid[] {  };
            fld.TargetFieldID = new Guid[] { new Guid("CB957AA1-665D-438D-BB90-3FEC3A7CE3F0"), new Guid("BE0F57C6-CF6C-41E4-ACA1-BAD819FEBD9D") };
            fld.SourceFieldID = new Guid[] { new Guid("BAA71C0C-B8B9-4767-9D5B-6AB3A829A89A"), new Guid("7154AB23-E94B-48FD-9D58-F903D166D05A") };
            fld.DataSourceID = new Guid("4E22A7DA-AD65-4076-85B0-71C22F6634A6");
            fld.AutoLoad = false;
            fld.FilterInative = true;
            fld.IsAnswer = false;
            fld.AllowMultiSelect = false;
            fld = AddField(new XFRMField());
            fld.Name = "Numero";
            fld.Title = "Doc. Nº";
            fld.CanInsert = true;
            fld.CanUpdate = true;
            fld.RowCount = 2;
            fld.ColCount = 18;
            fld.IsHidden = false;
            fld.Location = 2;
            fld.EditorCID = XModelEditors.XString;
            fld.Operator = XOperator.EqualTo;
            fld.JustifyHeight = false;
            fld.AllowEmpty = true;
            fld.FontColor = "#000000";
            fld.FontStyle = XFontStyle.Normal;
            fld.ShowFooter = false;
            fld.ViewSAM = new Guid("00000000-0000-0000-0000-000000000000");
            fld.Order = 2;
            fld.Scale = -1;
            fld.Length = -1;
            fld.TypeID = XDataTypes.XString;
            fld.AdditionalFieldsID = new Guid[] {  };
            fld.AdditionalDataFieldsID = new Guid[] {  };
            fld.TargetFilterFieldID = new Guid[] {  };
            fld.SourceFilterFieldID = new Guid[] {  };
            fld.TargetFieldID = new Guid[] {  };
            fld.SourceFieldID = new Guid[] {  };
            fld.AutoLoad = false;
            fld.FilterInative = true;
            fld.IsAnswer = false;
            fld.AllowMultiSelect = false;
        }
    }
}