//<auto-generated/>
using System;
using TFX.Core;
using TFX.CIT.Core.Model;
using TFX.Core.Reflections;
using Projecao.Core.PCR.Vacina;
using System.Collections.Generic;

namespace Projecao.Core.PCR.Test.Vacina
{
    [XRegister(typeof(VacinaSAMVacinasTestCIT), sCID)]
    [XDASESource(@"D:\Tootega\Source\TFX20\Modules\Projecao.Core.PCR.Test\Projecao.Core.PCR.Test.csproj", @"D:\Tootega\Source\TFX20\Modules\Projecao.Core.PCR.Test\Vacina\Vacina.SAM.Vacinas.Test.dscit")]
    public class VacinaSAMVacinasTestCIT : XCITInfo
    {
        public const String sCID = "46773050-1841-4AE2-A5B4-6B1C555B786F";
        public static Guid gCID = new Guid(sCID);
        public class XRule : XCITRule<VacinaSAMVacinasTestCIT, VacinaSVC, VacinaSVC.XDataSet, VacinaSVC.XTuple>
        {
        }

        public xVacina[] DataVacina = new xVacina[6];
        public record xVacina(String Nome, String Categoria);


        public List<xISExItemCategoria>[] DataISExItemCategoria = new List<xISExItemCategoria>[6];
        public record xISExItemCategoria(Guid ISExItemCategoriaID, String ISExCategoriaID, String vISExCategoriaID, Int16 pkvISExCategoriaID, Guid ISExItemID, Int16 SYSxEstadoID, String Categoria);
        public VacinaSAMVacinasTestCIT()
        {
            ID = gCID;
            Name = "VacinaSAMVacinasTest";
            ApplicationID = new Guid("2C81E1D1-D0C4-4550-B2D0-F7A45FE418F2");
            MenuItemID = new Guid("2C81E1D1-D0C4-4550-B2D0-F7A45FE418F2");
            AppModulesID = new [] { (Int16)19 };
            AppGroupsID = new [] { (Int16)2 };
            PlayCount = 6;
            Title = "Cadastro de Medicamentos";
            ServiceID = new Guid("5FDAAA33-ABF4-4403-8428-E0B48A507158");
            DataVacina[0] = new xVacina(Nome: @"Aftosa", Categoria: @"Vacina Bovina");
            DataVacina[1] = new xVacina(Nome: @"Brucelose", Categoria: @"Vacina Bovina");
            DataVacina[2] = new xVacina(Nome: @"Excel 10", Categoria: @"Medicamento para Bovino");
            DataVacina[3] = new xVacina(Nome: @"Máxima Pour-On", Categoria: @"Medicamento para Bovino");
            DataVacina[4] = new xVacina(Nome: @"Raiva", Categoria: @"Vacina Bovina");
            DataVacina[5] = new xVacina(Nome: @"Vermifugo - Ivomec Gold", Categoria: @"Medicamento para Bovino");
            DataISExItemCategoria[0] = new List<xISExItemCategoria>();
            DataISExItemCategoria[1] = new List<xISExItemCategoria>();
            DataISExItemCategoria[2] = new List<xISExItemCategoria>();
            DataISExItemCategoria[3] = new List<xISExItemCategoria>();
            DataISExItemCategoria[4] = new List<xISExItemCategoria>();
            DataISExItemCategoria[5] = new List<xISExItemCategoria>();
            DataISExItemCategoria[2].Add(new xISExItemCategoria(ISExItemCategoriaID: new Guid("33B553DF-F2F7-4DD0-9D37-D661DE5CA6E5"), ISExCategoriaID: "Medicamento para Bovino", vISExCategoriaID: "Medicamento para Bovino", pkvISExCategoriaID: (Int16)105, ISExItemID: new Guid("9654A971-5868-435E-A4AB-6390C36B7861"), SYSxEstadoID: (Int16)1, Categoria: @"Medicamento para Bovino"));
            DataISExItemCategoria[5].Add(new xISExItemCategoria(ISExItemCategoriaID: new Guid("95EB1474-AAC1-4A58-8016-35F24AE4B639"), ISExCategoriaID: "Medicamento para Bovino", vISExCategoriaID: "Medicamento para Bovino", pkvISExCategoriaID: (Int16)105, ISExItemID: new Guid("B25A45F2-EDAC-4706-A99C-6C8795FFF3DB"), SYSxEstadoID: (Int16)1, Categoria: @"Medicamento para Bovino"));
            DataISExItemCategoria[3].Add(new xISExItemCategoria(ISExItemCategoriaID: new Guid("91605445-AE14-4D48-A46A-EC1762593C2B"), ISExCategoriaID: "Medicamento para Bovino", vISExCategoriaID: "Medicamento para Bovino", pkvISExCategoriaID: (Int16)105, ISExItemID: new Guid("9408AEDE-D564-412A-88B7-7F0F856426C4"), SYSxEstadoID: (Int16)1, Categoria: @"Medicamento para Bovino"));
            DataISExItemCategoria[4].Add(new xISExItemCategoria(ISExItemCategoriaID: new Guid("F86D680C-ADE9-4009-8958-5144F18219BA"), ISExCategoriaID: "Vacina Bovina", vISExCategoriaID: "Vacina Bovina", pkvISExCategoriaID: (Int16)103, ISExItemID: new Guid("B85885A1-60F3-4C92-94AE-84A5E314185C"), SYSxEstadoID: (Int16)1, Categoria: @"Vacina Bovina"));
            DataISExItemCategoria[1].Add(new xISExItemCategoria(ISExItemCategoriaID: new Guid("6DA7DA9A-A404-4CF5-9924-072C4B70F609"), ISExCategoriaID: "Vacina Bovina", vISExCategoriaID: "Vacina Bovina", pkvISExCategoriaID: (Int16)103, ISExItemID: new Guid("EA426307-0591-4B22-B2FB-CDB7C930F4A2"), SYSxEstadoID: (Int16)1, Categoria: @"Vacina Bovina"));
            DataISExItemCategoria[0].Add(new xISExItemCategoria(ISExItemCategoriaID: new Guid("19BD336F-6F63-486C-ABF7-3CCB5C242C9E"), ISExCategoriaID: "Vacina Bovina", vISExCategoriaID: "Vacina Bovina", pkvISExCategoriaID: (Int16)103, ISExItemID: new Guid("0B00CDEE-3E6C-4328-BE68-27C64358146B"), SYSxEstadoID: (Int16)1, Categoria: @"Vacina Bovina"));
        }
    }
}