//<auto-generated/>
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using TFX.Core.Controllers;
using TFX.Core.Services;
using System;
using TFX.Core.Model;
using Microsoft.AspNetCore.Http;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using TFX.Core.Data;
using Tootega.Core.CEP.Localidade;
using Tootega.Core.CEP.Localidade.Rules;
using TFX.Core.Data.CEP;

namespace Tootega.Core.CEP.Localidade
{
    [Route("Localidade")]
    [ApiController]
    public class LocalidadeController : XController
    {
        public abstract class BaseINFLocalidadeControllerRule : XControllerINFRule<LocalidadeController>
        {
            public BaseINFLocalidadeControllerRule(LocalidadeController pController)
                :base(pController)
            {
            }
        }

        public LocalidadeController(ILocalidadeService pService)
        {
            Service = pService;
            _Rule = new INFLocalidadeControllerRule(this);
        }

        internal readonly ILocalidadeService Service;
        private readonly INFLocalidadeControllerRule _Rule;

        [HttpPost("Search")]
        [ProducesResponseType(typeof(LocalidadeDataSet), StatusCodes.Status200OK)]
        [ProducesResponseType(typeof(XEndPointMessage), StatusCodes.Status404NotFound)]
        public IActionResult Execute([FromBody] LocalidadeFilter pFilter)
        {
            try
            {
                var dst = Service.Execute(pFilter);
                return Ok(dst);
            }
            catch (Exception pEx)
            {
                return StatusCode(404, XEndPointMessage.Erro(pEx));
            }  
        }

        [HttpPost("Flush")]
        [ProducesResponseType(typeof(LocalidadeDataSet), StatusCodes.Status200OK)]
        [ProducesResponseType(typeof(XEndPointMessage), StatusCodes.Status404NotFound)]
        [XEndpointDescription(typeof(LocalidadeService.CEPxLocalidade))]
        public IActionResult Flush([FromBody] LocalidadeDataSet pDataSet)
        {
            try
            {
                var result = Service.Flush(pDataSet);
                Service.GracefullyClose();
                return Ok(result);
            }
            catch (Exception pEx)
            {
                return StatusCode(404, XEndPointMessage.Erro(pEx));
            }  
        }
    }
}