//<auto-generated/>
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using TFX.Core.Controllers;
using TFX.Core.Services;
using System;
using TFX.Core.Model;
using Microsoft.AspNetCore.Http;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using TFX.Core.Data;
using Tootega.Core.ERP.Empresa;
using Tootega.Core.ERP.Empresa.Rules;
using TFX.Core.Data.DB;
using Tootega.Core.ERP.DB;

namespace Tootega.Core.ERP.Empresa
{
    [Route("Empresa")]
    [ApiController]
    public class EmpresaController : XController
    {
        public abstract class BaseINFEmpresaControllerRule : XControllerINFRule<EmpresaController>
        {
            public BaseINFEmpresaControllerRule(EmpresaController pController)
                :base(pController)
            {
            }
        }

        public EmpresaController(IEmpresaService pService)
        {
            Service = pService;
            _Rule = new INFEmpresaControllerRule(this);
        }

        internal readonly IEmpresaService Service;
        private readonly INFEmpresaControllerRule _Rule;

        [HttpPost("Search")]
        [ProducesResponseType(typeof(EmpresaDataSet), StatusCodes.Status200OK)]
        [ProducesResponseType(typeof(XEndPointMessage), StatusCodes.Status404NotFound)]
        public IActionResult Execute([FromBody] EmpresaFilter pFilter)
        {
            try
            {
                var dst = Service.Execute(pFilter, true);
                return Ok(dst);
            }
            catch (Exception pEx)
            {
                return StatusCode(404, XEndPointMessage.Erro(pEx));
            }  
        }

        [HttpPost("Flush")]
        [ProducesResponseType(typeof(EmpresaDataSet), StatusCodes.Status200OK)]
        [ProducesResponseType(typeof(XEndPointMessage), StatusCodes.Status404NotFound)]
        [XEndpointDescription(typeof(EmpresaService.CORxPessoa), typeof(EmpresaService.ERPxPessoaJuridica))]
        public IActionResult Flush([FromBody] EmpresaDataSet pDataSet)
        {
            try
            {
                var result = Service.Flush(pDataSet);
                Service.GracefullyClose();
                return Ok(result);
            }
            catch (Exception pEx)
            {
                return StatusCode(404, XEndPointMessage.Erro(pEx));
            }  
        }

        [HttpPost("Get")]
        [ProducesResponseType(typeof(EmpresaDataSet), StatusCodes.Status200OK)]
        [ProducesResponseType(typeof(XEndPointMessage), StatusCodes.Status404NotFound)]
        public IActionResult Get([FromBody] EmpresaFilter pFilter)
        {
            try
            {
                var result = Service.InternalGet(pFilter, true);
                return Ok(result);
            }
            catch (Exception pEx)
            {
                return StatusCode(404, XEndPointMessage.Erro(pEx));
            }  
        }
    }
}