//<auto-generated/>
using System;
using System.Collections.Generic;
using TFX.Core;
using TFX.Core.Model.Cache;
using TFX.Core.Reflections;
using TFX.CIT.Core.Model;
using Projecao.Core.ERP.GerenciaEmpresa;

namespace Projecao.Core.ERP.Test.GerenciaEmpresa
{
    [XRegister(typeof(GerenciaEmpresaSAMTootegaTestCIT), sCID)]
    [XDASESource(@"D:\Tootega\Source\TFX20\Modules\Projecao.Core.ERP.Test\Projecao.Core.ERP.Test.csproj", @"D:\Tootega\Source\TFX20\Modules\Projecao.Core.ERP.Test\GerenciaEmpresa\GerenciaEmpresa.SAM.Tootega.Test.dscit")]
    public class GerenciaEmpresaSAMTootegaTestCIT : XCITInfo
    {
        public const String sCID = "553CE459-33FA-4DEA-803D-FDBE18A3C556";
        public static Guid gCID = new Guid(sCID);
        public class XRule : XCITRule<GerenciaEmpresaSAMTootegaTestCIT, GerenciaEmpresaSVC, GerenciaEmpresaSVC.XDataSet, GerenciaEmpresaSVC.XTuple>
        {
        }

        public GerenciaEmpresaSVC Tutor;
        public GerenciaEmpresaSVC.XDataSet DataSet;
        public GerenciaEmpresaSAMTootegaTestCIT()
        {
            ID = gCID;
            Name = "GerenciaEmpresaSAMTootegaTest";
            ApplicationID = new Guid("F8837660-1473-40FA-AF63-21BF08928E7B");
            MenuItemID = new Guid("F8837660-1473-40FA-AF63-21BF08928E7B");
            AppModulesID = new [] { (Int16)1 };
            AppGroupsID = new [] { (Int16)2 };
            PlayCount = 1;
            Title = "Parâmetros de Empresas";
            ServiceID = new Guid("7E08A924-BD1A-4283-ACFF-32A8D11D3E3D");
            Tutor = (GerenciaEmpresaSVC)XModelCache.Instance.GetSVC(ServiceID);
            DataSet = Tutor.DataSetType.CreateInstance<GerenciaEmpresaSVC.XDataSet>();
            DataSet.Prepare(Tutor);
            GerenciaEmpresaSVC.XTuple GerenciaEmpresaxTPL;
            GerenciaEmpresaxTPL = new GerenciaEmpresaSVC.XTuple(DataSet.Fields.Count);
            GerenciaEmpresaxTPL.PKValue = new Guid("2F55B304-8156-4A42-9F66-7382E5512A6E");
            DataSet.AddTuple(GerenciaEmpresaxTPL);
            GerenciaEmpresaxTPL.Nome = @"Tootega Pesquisa e Inovação";
            GerenciaEmpresaxTPL.Sigla = @"Tootega";
            GerenciaEmpresaxTPL.SYSxEmpresaID = new Guid("2F55B304-8156-4A42-9F66-7382E5512A6E");
            GerenciaEmpresaxTPL.Grupo = @"Tootega";
            GerenciaEmpresaxTPL.Configuracao = null;
            GerenciaEmpresaxTPL.Numero = @"22893446000125";
            GerenciaEmpresaxTPL.FormID = new Guid("B96F5A8E-E33A-4167-B5EB-B01D1D688288");
            GerenciaEmpresaxTPL.RazaoSocial = @"Tootega Pesquisa e Inovação";
            GerenciaEmpresaxTPL.UltimaChamada = new DateTime(553508640000000000);
            GerenciaEmpresaxTPL.IDEmpresa = @"2F55B304-8156-4A42-9F66-7382E5512A6E";
        }
    }
}