//<auto-generated/>
using System;
using System.Linq;
using TFX.Core.Model;
using Microsoft.Extensions.DependencyInjection;
using TFX.Core.Data.Servicos;

namespace TFX.Core.Data
{
    public class TFXCoreDataModule : XModule
    {
        public override void Initialize(IServiceCollection pServices)
        {
            pServices.AddTransient<IUsuarioService, UsuarioService>();
            pServices.AddDbContext<UsuarioService.DBContext>();
        }
    }
}