//<auto-generated/>
using System;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore.Infrastructure;
using TFX.Core;

namespace Projecao.Core.ERP.DB
{
    public  partial class ProjecaoCoreERPContext : XDBContext
    {
    }
}