//<auto-generated/>
using System;
using System.Linq;
using TFX.Core;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using TFX.Core.Lzma;

namespace TFX.ESC.Core.DB
{
    public class ESCxContabilistaEscritorio : XEntity
    {
        public Boolean IsPKEmpty => Object.Equals(ESCxContabilistaEscritorioID, typeof(Guid).GetDefault());
        [Display(Name = "Contabilistas por Escritório")]
        [Required()]
        public Guid? ESCxContabilistaEscritorioID {get; set;}

        [Display(Name = "Contabilista")]
        [Required()]
        public Guid ESCxContabilistaID {get; set;}

        [Display(Name = "Escritório")]
        [Required()]
        public Guid ESCxEscritorioID {get; set;}

        public ESCxEscritorio ESCxEscritorio {get; set;}
        public ESCxContabilista ESCxContabilista {get; set;}
    }
}
