//<auto-generated/>
using System;
using System.Drawing;
using TFX.Core.Data;
using TFX.Core.Model.DIC;
using TFX.Core.Model.DIC.APP;
using TFX.Core.Reflections;
using TFX.Core.Objects;
using TFX.Core.Model.DIC.FRM;
using TFX.Core.Model.DIC.RPT;
using TFX.Core.Model.DIC.Types;
using TFX.Core.Model.DIC.ORM;
using TFX.Core.Model.DIC.SVC;
using Newtonsoft.Json;

namespace Projecao.Core.PET.Animal
{
    [XRegister(typeof(AnimalSAM), sCID)]
    [XDASESource(@"D:\Tootega\Source\TFX20\Modules\Projecao.Core.PET\Projecao.Core.PET.csproj", @"D:\Tootega\Source\TFX20\Modules\Projecao.Core.PET\Animal\Animal.dssam")]
    public class AnimalSAM : XAPPModel
    {
        #region xAnimalACT

        [XRegister(typeof(xAnimalACT), sCID)]
        public class xAnimalACT : XAPPStep
        {
            public const String sCID = "E4E4F5CA-17E0-4363-9D65-CE339AA81E91";
            public static Guid gCID = new Guid(sCID);
            public xAnimalACT(Guid pID, String pName, String pTitle, Guid pFormID, Guid pDataSourceID)
              :base(pID, pName, pTitle, pFormID, pDataSourceID)
            {
            }
        }

        #endregion xAnimalACT

        #region AnimalFRM

        [XRegister(typeof(AnimalFRM), sCID, typeof(AnimalSAM))]
        public class AnimalFRM : XFRMModel
        {
            public const String sCID = "A675C8B1-80AD-4347-842B-7E7F95B345D8";
            public static new readonly Guid gCID = new Guid(sCID);
            static AnimalFRM()
            {
                gCID = new Guid(sCID);
            }
            public AnimalFRM()
            {
                ID = gCID;
                Name = "Animal";
                Title = "";
                MinRows = 29;
                ConfigCID = new Guid("00000000-0000-0000-0000-000000000000");
                ConfigPKFilter = false;
                ReferenceScripts = new String[] { "TFX.Core.Service.js", "Projecao.Core.CEP.js", "Projecao.Core.ERP.js", "Projecao.Core.IMC.js", "Projecao.Core.ISE.js", "Projecao.Core.PET.js" };
                Rect = new XRect(20, 20, 1018, 696);
                Style = XFRMStyle.Normal;
                ActionContext = XActionContext.All;
                AddItem(PETxTutorID);
                PETxTutorID.CanInsert = true;
                PETxTutorID.CanUpdate = true;
                PETxTutorID.RowCount = 2;
                PETxTutorID.ColCount = 19;
                PETxTutorID.RowCountSmall = 2;
                PETxTutorID.ColCountSmall = 19;
                PETxTutorID.IsHidden = false;
                PETxTutorID.IsHiddenSmall = false;
                PETxTutorID.AdditionalTitle = "";
                PETxTutorID.Icon = "";
                PETxTutorID.Location = 1;
                PETxTutorID.EditorCID = new Guid("66290387-F0AD-4746-A1F7-B0D8D4C5C2EE");
                PETxTutorID.Operator = XOperator.EqualTo;
                PETxTutorID.ShowSpin = false;
                PETxTutorID.HotkeyChar = "";
                PETxTutorID.JustifyHeight = false;
                PETxTutorID.AllowEmpty = true;
                PETxTutorID.FontColor = "#000000";
                PETxTutorID.FontStyle = XFontStyle.Normal;
                PETxTutorID.ShowFooter = false;
                PETxTutorID.ViewSAM = new Guid("00000000-0000-0000-0000-000000000000");
                PETxTutorID.Order = 1;
                PETxTutorID.Scale = -1;
                PETxTutorID.Length = -1;
                PETxTutorID.SearchAction = XSearchAction.Default;
                PETxTutorID.TypeID = XGuid.CID;
                PETxTutorID.AdditionalFieldsID = new Guid[] {  };
                PETxTutorID.AdditionalDataFieldsID = new Guid[] {  };
                PETxTutorID.TargetFilterFieldID = new Guid[] {  };
                PETxTutorID.SourceFilterFieldID = new Guid[] {  };
                PETxTutorID.TargetDisplayFieldID = new Guid[] { new Guid("1114D1A4-F1F6-4384-B62A-1AFEB82FD313") };
                PETxTutorID.SourceDisplayFieldID = new Guid[] { new Guid("C6CAFF78-D747-4805-A654-A05461EC1592") };
                PETxTutorID.DataSourceID = global::Projecao.Core.PET.Tutor.TutorSVC.gCID;
                PETxTutorID.AutoLoad = false;
                PETxTutorID.FilterInative = true;
                PETxTutorID.IsAnswer = false;
                PETxTutorID.AllowMultiSelect = false;
                AddItem(PETxAnimalImagemID);
                PETxAnimalImagemID.CanInsert = true;
                PETxAnimalImagemID.CanUpdate = true;
                PETxAnimalImagemID.RowCount = 15;
                PETxAnimalImagemID.ColCount = 13;
                PETxAnimalImagemID.RowCountSmall = 15;
                PETxAnimalImagemID.ColCountSmall = 13;
                PETxAnimalImagemID.IsHidden = false;
                PETxAnimalImagemID.IsHiddenSmall = false;
                PETxAnimalImagemID.AdditionalTitle = "";
                PETxAnimalImagemID.Icon = "";
                PETxAnimalImagemID.Location = 2;
                PETxAnimalImagemID.EditorCID = new Guid("2B717129-F9F5-48BD-9DE8-5CC0AF15B425");
                PETxAnimalImagemID.Operator = XOperator.EqualTo;
                PETxAnimalImagemID.ShowSpin = false;
                PETxAnimalImagemID.HotkeyChar = "";
                PETxAnimalImagemID.JustifyHeight = true;
                PETxAnimalImagemID.AllowEmpty = true;
                PETxAnimalImagemID.FontColor = "#000000";
                PETxAnimalImagemID.FontStyle = XFontStyle.Normal;
                PETxAnimalImagemID.ShowFooter = false;
                PETxAnimalImagemID.ViewSAM = new Guid("00000000-0000-0000-0000-000000000000");
                PETxAnimalImagemID.Order = 2;
                PETxAnimalImagemID.Scale = -1;
                PETxAnimalImagemID.Length = -1;
                PETxAnimalImagemID.SearchAction = XSearchAction.Default;
                PETxAnimalImagemID.TypeID = XGuid.CID;
                PETxAnimalImagemID.AdditionalFieldsID = new Guid[] {  };
                PETxAnimalImagemID.AdditionalDataFieldsID = new Guid[] { new Guid("44B734D3-397B-452D-B1FD-54A1A302C347") };
                PETxAnimalImagemID.TargetFilterFieldID = new Guid[] {  };
                PETxAnimalImagemID.SourceFilterFieldID = new Guid[] {  };
                PETxAnimalImagemID.TargetDisplayFieldID = new Guid[] {  };
                PETxAnimalImagemID.SourceDisplayFieldID = new Guid[] {  };
                PETxAnimalImagemID.DataSourceID = global::Projecao.Core.PET.Animal.AnimalImagemSVC.gCID;
                PETxAnimalImagemID.AutoLoad = false;
                PETxAnimalImagemID.FilterInative = true;
                PETxAnimalImagemID.IsAnswer = false;
                PETxAnimalImagemID.AllowMultiSelect = false;
                AddItem(Nome);
                Nome.CanInsert = true;
                Nome.CanUpdate = true;
                Nome.RowCount = 2;
                Nome.ColCount = 12;
                Nome.RowCountSmall = 2;
                Nome.ColCountSmall = 12;
                Nome.IsHidden = false;
                Nome.IsHiddenSmall = false;
                Nome.AdditionalTitle = "";
                Nome.Icon = "";
                Nome.Location = 3;
                Nome.EditorCID = new Guid("F5982E79-BA45-40FB-85E1-9F2C8B90B6EF");
                Nome.Operator = XOperator.EqualTo;
                Nome.ShowSpin = false;
                Nome.HotkeyChar = "";
                Nome.JustifyHeight = false;
                Nome.AllowEmpty = true;
                Nome.FontColor = "#000000";
                Nome.FontStyle = XFontStyle.Normal;
                Nome.ShowFooter = false;
                Nome.ViewSAM = new Guid("00000000-0000-0000-0000-000000000000");
                Nome.Order = 3;
                Nome.Scale = -1;
                Nome.Length = -1;
                Nome.SearchAction = XSearchAction.Default;
                Nome.TypeID = XString.CID;
                Nome.AdditionalFieldsID = new Guid[] {  };
                Nome.AdditionalDataFieldsID = new Guid[] {  };
                Nome.TargetFilterFieldID = new Guid[] {  };
                Nome.SourceFilterFieldID = new Guid[] {  };
                Nome.TargetDisplayFieldID = new Guid[] {  };
                Nome.SourceDisplayFieldID = new Guid[] {  };
                Nome.AutoLoad = false;
                Nome.FilterInative = true;
                Nome.IsAnswer = false;
                Nome.AllowMultiSelect = false;
                AddItem(ERPxSexoID);
                ERPxSexoID.CanInsert = true;
                ERPxSexoID.CanUpdate = true;
                ERPxSexoID.RowCount = 2;
                ERPxSexoID.ColCount = 7;
                ERPxSexoID.RowCountSmall = 2;
                ERPxSexoID.ColCountSmall = 7;
                ERPxSexoID.IsHidden = false;
                ERPxSexoID.IsHiddenSmall = false;
                ERPxSexoID.AdditionalTitle = "";
                ERPxSexoID.Icon = "";
                ERPxSexoID.DataSourceID = global::Projecao.Core.ERP.DB.ERPx.ERPxGenero.gCID;
                ERPxSexoID.Location = 4;
                ERPxSexoID.EditorCID = new Guid("AC111493-AD7B-4F74-A0E8-DF0E0BB6B74A");
                ERPxSexoID.Operator = XOperator.EqualTo;
                ERPxSexoID.ShowSpin = false;
                ERPxSexoID.HotkeyChar = "";
                ERPxSexoID.JustifyHeight = false;
                ERPxSexoID.AllowEmpty = true;
                ERPxSexoID.FontColor = "#000000";
                ERPxSexoID.FontStyle = XFontStyle.Normal;
                ERPxSexoID.ShowFooter = false;
                ERPxSexoID.ViewSAM = new Guid("00000000-0000-0000-0000-000000000000");
                ERPxSexoID.Order = 4;
                ERPxSexoID.Scale = -1;
                ERPxSexoID.Length = -1;
                ERPxSexoID.SearchAction = XSearchAction.Default;
                ERPxSexoID.TypeID = XInt16.CID;
                ERPxSexoID.AdditionalFieldsID = new Guid[] {  };
                ERPxSexoID.AdditionalDataFieldsID = new Guid[] {  };
                ERPxSexoID.TargetFilterFieldID = new Guid[] {  };
                ERPxSexoID.SourceFilterFieldID = new Guid[] {  };
                ERPxSexoID.TargetDisplayFieldID = new Guid[] { new Guid("2075E7EE-84FB-447A-A432-3B58365E7FAF") };
                ERPxSexoID.SourceDisplayFieldID = new Guid[] { new Guid("E1C95896-5736-4247-A911-DA6300C691F9") };
                ERPxSexoID.DataSourceID = global::Projecao.Core.ERP.DB.ERPx.ERPxGenero.gCID;
                ERPxSexoID.AutoLoad = false;
                ERPxSexoID.FilterInative = true;
                ERPxSexoID.IsAnswer = false;
                ERPxSexoID.AllowMultiSelect = false;
                AddItem(Cor);
                Cor.CanInsert = true;
                Cor.CanUpdate = true;
                Cor.RowCount = 2;
                Cor.ColCount = 6;
                Cor.RowCountSmall = 2;
                Cor.ColCountSmall = 6;
                Cor.IsHidden = false;
                Cor.IsHiddenSmall = false;
                Cor.AdditionalTitle = "";
                Cor.Icon = "";
                Cor.Location = 5;
                Cor.EditorCID = new Guid("F5982E79-BA45-40FB-85E1-9F2C8B90B6EF");
                Cor.Operator = XOperator.EqualTo;
                Cor.ShowSpin = false;
                Cor.HotkeyChar = "";
                Cor.JustifyHeight = false;
                Cor.AllowEmpty = true;
                Cor.FontColor = "#000000";
                Cor.FontStyle = XFontStyle.Normal;
                Cor.ShowFooter = false;
                Cor.ViewSAM = new Guid("00000000-0000-0000-0000-000000000000");
                Cor.Order = 5;
                Cor.Scale = -1;
                Cor.Length = -1;
                Cor.SearchAction = XSearchAction.Default;
                Cor.TypeID = XString.CID;
                Cor.AdditionalFieldsID = new Guid[] {  };
                Cor.AdditionalDataFieldsID = new Guid[] {  };
                Cor.TargetFilterFieldID = new Guid[] {  };
                Cor.SourceFilterFieldID = new Guid[] {  };
                Cor.TargetDisplayFieldID = new Guid[] {  };
                Cor.SourceDisplayFieldID = new Guid[] {  };
                Cor.AutoLoad = false;
                Cor.FilterInative = true;
                Cor.IsAnswer = false;
                Cor.AllowMultiSelect = false;
                AddItem(PETxPelagemID);
                PETxPelagemID.CanInsert = true;
                PETxPelagemID.CanUpdate = true;
                PETxPelagemID.RowCount = 2;
                PETxPelagemID.ColCount = 5;
                PETxPelagemID.RowCountSmall = 2;
                PETxPelagemID.ColCountSmall = 5;
                PETxPelagemID.IsHidden = false;
                PETxPelagemID.IsHiddenSmall = false;
                PETxPelagemID.AdditionalTitle = "";
                PETxPelagemID.Icon = "";
                PETxPelagemID.DataSourceID = global::Projecao.Core.PET.DB.PETx.PETxPelagem.gCID;
                PETxPelagemID.Location = 6;
                PETxPelagemID.EditorCID = new Guid("AC111493-AD7B-4F74-A0E8-DF0E0BB6B74A");
                PETxPelagemID.Operator = XOperator.EqualTo;
                PETxPelagemID.ShowSpin = false;
                PETxPelagemID.HotkeyChar = "";
                PETxPelagemID.JustifyHeight = false;
                PETxPelagemID.AllowEmpty = true;
                PETxPelagemID.FontColor = "#000000";
                PETxPelagemID.FontStyle = XFontStyle.Normal;
                PETxPelagemID.ShowFooter = false;
                PETxPelagemID.ViewSAM = new Guid("00000000-0000-0000-0000-000000000000");
                PETxPelagemID.Order = 6;
                PETxPelagemID.Scale = -1;
                PETxPelagemID.Length = -1;
                PETxPelagemID.SearchAction = XSearchAction.Default;
                PETxPelagemID.TypeID = XInt16.CID;
                PETxPelagemID.AdditionalFieldsID = new Guid[] {  };
                PETxPelagemID.AdditionalDataFieldsID = new Guid[] {  };
                PETxPelagemID.TargetFilterFieldID = new Guid[] {  };
                PETxPelagemID.SourceFilterFieldID = new Guid[] {  };
                PETxPelagemID.TargetDisplayFieldID = new Guid[] { new Guid("CAC71739-1DAA-415F-82CB-93141A6B6B62") };
                PETxPelagemID.SourceDisplayFieldID = new Guid[] { new Guid("DFDD3EBF-5A5B-49F9-AE45-90FA865524EF") };
                PETxPelagemID.DataSourceID = global::Projecao.Core.PET.DB.PETx.PETxPelagem.gCID;
                PETxPelagemID.AutoLoad = false;
                PETxPelagemID.FilterInative = true;
                PETxPelagemID.IsAnswer = false;
                PETxPelagemID.AllowMultiSelect = false;
                AddItem(PETxRacaID);
                PETxRacaID.CanInsert = true;
                PETxRacaID.CanUpdate = true;
                PETxRacaID.RowCount = 2;
                PETxRacaID.ColCount = 8;
                PETxRacaID.RowCountSmall = 2;
                PETxRacaID.ColCountSmall = 8;
                PETxRacaID.IsHidden = false;
                PETxRacaID.IsHiddenSmall = false;
                PETxRacaID.AdditionalTitle = "";
                PETxRacaID.Icon = "";
                PETxRacaID.Location = 7;
                PETxRacaID.EditorCID = new Guid("66290387-F0AD-4746-A1F7-B0D8D4C5C2EE");
                PETxRacaID.Operator = XOperator.EqualTo;
                PETxRacaID.ShowSpin = false;
                PETxRacaID.HotkeyChar = "";
                PETxRacaID.JustifyHeight = false;
                PETxRacaID.AllowEmpty = true;
                PETxRacaID.FontColor = "#000000";
                PETxRacaID.FontStyle = XFontStyle.Normal;
                PETxRacaID.ShowFooter = false;
                PETxRacaID.ViewSAM = new Guid("00000000-0000-0000-0000-000000000000");
                PETxRacaID.Order = 7;
                PETxRacaID.Scale = -1;
                PETxRacaID.Length = -1;
                PETxRacaID.SearchAction = XSearchAction.Default;
                PETxRacaID.TypeID = XInt16.CID;
                PETxRacaID.AdditionalFieldsID = new Guid[] {  };
                PETxRacaID.AdditionalDataFieldsID = new Guid[] {  };
                PETxRacaID.TargetFilterFieldID = new Guid[] {  };
                PETxRacaID.SourceFilterFieldID = new Guid[] {  };
                PETxRacaID.TargetDisplayFieldID = new Guid[] { new Guid("09E753A1-F46C-4EB2-9C19-298E91CACC8C"), new Guid("A895ED5B-83CD-4388-99A2-0E968CCE7D42") };
                PETxRacaID.SourceDisplayFieldID = new Guid[] { new Guid("DAEF8FD8-178B-4ABA-945A-87A90C701C8F"), new Guid("F6E69055-0B49-4045-B755-A17455868C93") };
                PETxRacaID.DataSourceID = global::Projecao.Core.PET.ReadOnly.RacaSVC.gCID;
                PETxRacaID.AutoLoad = false;
                PETxRacaID.FilterInative = true;
                PETxRacaID.IsAnswer = false;
                PETxRacaID.AllowMultiSelect = false;
                AddItem(Familia);
                Familia.IsReadOnly = true;
                Familia.CanInsert = true;
                Familia.CanUpdate = true;
                Familia.RowCount = 2;
                Familia.ColCount = 7;
                Familia.RowCountSmall = 2;
                Familia.ColCountSmall = 7;
                Familia.IsHidden = false;
                Familia.IsHiddenSmall = false;
                Familia.AdditionalTitle = "";
                Familia.Icon = "";
                Familia.Location = 8;
                Familia.EditorCID = new Guid("F5982E79-BA45-40FB-85E1-9F2C8B90B6EF");
                Familia.Operator = XOperator.EqualTo;
                Familia.ShowSpin = false;
                Familia.HotkeyChar = "";
                Familia.JustifyHeight = false;
                Familia.AllowEmpty = true;
                Familia.FontColor = "#000000";
                Familia.FontStyle = XFontStyle.Normal;
                Familia.ShowFooter = false;
                Familia.ViewSAM = new Guid("00000000-0000-0000-0000-000000000000");
                Familia.Order = 8;
                Familia.Scale = -1;
                Familia.Length = -1;
                Familia.SearchAction = XSearchAction.Default;
                Familia.TypeID = XString.CID;
                Familia.AdditionalFieldsID = new Guid[] {  };
                Familia.AdditionalDataFieldsID = new Guid[] {  };
                Familia.TargetFilterFieldID = new Guid[] {  };
                Familia.SourceFilterFieldID = new Guid[] {  };
                Familia.TargetDisplayFieldID = new Guid[] {  };
                Familia.SourceDisplayFieldID = new Guid[] {  };
                Familia.AutoLoad = false;
                Familia.FilterInative = true;
                Familia.IsAnswer = false;
                Familia.AllowMultiSelect = false;
                AddItem(PETxPorteID);
                PETxPorteID.CanInsert = true;
                PETxPorteID.CanUpdate = true;
                PETxPorteID.RowCount = 2;
                PETxPorteID.ColCount = 12;
                PETxPorteID.RowCountSmall = 2;
                PETxPorteID.ColCountSmall = 12;
                PETxPorteID.IsHidden = false;
                PETxPorteID.IsHiddenSmall = false;
                PETxPorteID.AdditionalTitle = "";
                PETxPorteID.Icon = "";
                PETxPorteID.DataSourceID = global::Projecao.Core.PET.DB.PETx.PETxPorte.gCID;
                PETxPorteID.Location = 9;
                PETxPorteID.EditorCID = new Guid("AC111493-AD7B-4F74-A0E8-DF0E0BB6B74A");
                PETxPorteID.Operator = XOperator.EqualTo;
                PETxPorteID.ShowSpin = false;
                PETxPorteID.HotkeyChar = "";
                PETxPorteID.JustifyHeight = false;
                PETxPorteID.AllowEmpty = true;
                PETxPorteID.FontColor = "#000000";
                PETxPorteID.FontStyle = XFontStyle.Normal;
                PETxPorteID.ShowFooter = false;
                PETxPorteID.ViewSAM = new Guid("00000000-0000-0000-0000-000000000000");
                PETxPorteID.Order = 9;
                PETxPorteID.Scale = -1;
                PETxPorteID.Length = -1;
                PETxPorteID.SearchAction = XSearchAction.Default;
                PETxPorteID.TypeID = XInt16.CID;
                PETxPorteID.AdditionalFieldsID = new Guid[] {  };
                PETxPorteID.AdditionalDataFieldsID = new Guid[] {  };
                PETxPorteID.TargetFilterFieldID = new Guid[] {  };
                PETxPorteID.SourceFilterFieldID = new Guid[] {  };
                PETxPorteID.TargetDisplayFieldID = new Guid[] { new Guid("920C704F-BA35-4C2D-89CC-4E1A8E184D30") };
                PETxPorteID.SourceDisplayFieldID = new Guid[] { new Guid("427B4996-0AA1-4AA1-837E-06B25893C0F6") };
                PETxPorteID.DataSourceID = global::Projecao.Core.PET.DB.PETx.PETxPorte.gCID;
                PETxPorteID.AutoLoad = false;
                PETxPorteID.FilterInative = true;
                PETxPorteID.IsAnswer = false;
                PETxPorteID.AllowMultiSelect = false;
                AddItem(NewTabControl);
                NewTabControl.CanInsert = true;
                NewTabControl.CanUpdate = true;
                NewTabControl.RowCount = 8;
                NewTabControl.ColCount = 19;
                NewTabControl.RowCountSmall = 8;
                NewTabControl.ColCountSmall = 19;
                NewTabControl.IsHidden = false;
                NewTabControl.IsHiddenSmall = false;
                NewTabControl.AdditionalTitle = "";
                NewTabControl.Icon = "";
                NewTabControl.TabForms = new Guid[] { new Guid("7793168C-3ED9-4332-B300-0BDE70E20DD3"), new Guid("CBE3DC6D-54B7-487D-B738-3A29A6100B6C") };
                NewTabControl.Location = 10;
                NewTabControl.EditorCID = new Guid("59A28B08-01BF-4EAF-81CA-F317B3907B19");
                NewTabControl.Operator = XOperator.EqualTo;
                NewTabControl.ShowSpin = false;
                NewTabControl.HotkeyChar = "";
                NewTabControl.JustifyHeight = true;
                NewTabControl.AllowEmpty = true;
                NewTabControl.FontColor = "#000000";
                NewTabControl.FontStyle = XFontStyle.Normal;
                NewTabControl.ShowFooter = false;
                NewTabControl.ViewSAM = new Guid("00000000-0000-0000-0000-000000000000");
                NewTabControl.Order = 10;
                NewTabControl.Scale = -1;
                NewTabControl.Length = -1;
                NewTabControl.SearchAction = XSearchAction.Default;
                NewTabControl.TypeID = XString.CID;
                NewTabControl.AdditionalFieldsID = new Guid[] {  };
                NewTabControl.AdditionalDataFieldsID = new Guid[] {  };
                NewTabControl.GridFormCID = new Guid("7793168C-3ED9-4332-B300-0BDE70E20DD3");
                NewTabControl.TargetFilterFieldID = new Guid[] {  };
                NewTabControl.SourceFilterFieldID = new Guid[] {  };
                NewTabControl.TargetDisplayFieldID = new Guid[] {  };
                NewTabControl.SourceDisplayFieldID = new Guid[] {  };
                NewTabControl.AutoLoad = false;
                NewTabControl.FilterInative = true;
                NewTabControl.IsAnswer = false;
                NewTabControl.AllowMultiSelect = false;
            }
            public XFRMField PETxTutorID = new XFRMField(new Guid("9916100F-3927-48C9-8C56-6703C2001CB9"), "PETxTutorID", "Nome do Tutor", XGuid.CID, 2, 19, false, gCID, null, new Guid("4228449B-D3CE-4344-8D10-F605D60362B9")); // Guid;
            public XFRMField PETxAnimalImagemID = new XFRMField(new Guid("1C5BBCCA-AD39-4CC6-9141-93356175BAD7"), "PETxAnimalImagemID", "Fotos", XGuid.CID, 15, 13, false, gCID, null, new Guid("DAB65D14-EC01-47DF-BD48-C78CA4C3D147")); // Guid;
            public XFRMField Nome = new XFRMField(new Guid("A13344AD-99BD-43BC-921C-7E89443558E1"), "Nome", "Nome do PET", XString.CID, 2, 12, false, gCID, null, new Guid("BD127097-959A-4347-9918-4A4DD4138990")); // String;
            public XFRMField ERPxSexoID = new XFRMField(new Guid("C692C20B-91EB-4D72-89DC-B2430B20639C"), "ERPxSexoID", "Gênero", XInt16.CID, 2, 7, false, gCID, null, new Guid("AE5C89DC-11BC-4D68-974D-5444F4328D5A")); // Int16;
            public XFRMField Cor = new XFRMField(new Guid("FB400415-09EE-4146-9C0B-47CCC8BCA0A8"), "Cor", "Cor", XString.CID, 2, 6, false, gCID, null, new Guid("BB778083-3EFE-4B57-94E4-0F73EF309B68")); // String;
            public XFRMField PETxPelagemID = new XFRMField(new Guid("39D490D9-1B77-4A0E-83FF-57D8E62E2A2A"), "PETxPelagemID", "Pelagem", XInt16.CID, 2, 5, false, gCID, null, new Guid("F277A1F5-D726-4AE8-B107-2138AC9E3C9B")); // Int16;
            public XFRMField PETxRacaID = new XFRMField(new Guid("A59368DE-8870-4139-BDEE-7A2550A35DDD"), "PETxRacaID", "Raça", XInt16.CID, 2, 8, false, gCID, null, new Guid("86F716A9-E267-41A7-AF48-AFEA483AEC20")); // Int16;
            public XFRMField Familia = new XFRMField(new Guid("284DD889-1097-4D39-B4B1-394360C72728"), "Familia", "Família", XString.CID, 2, 7, false, gCID, null, new Guid("A895ED5B-83CD-4388-99A2-0E968CCE7D42")); // String;
            public XFRMField PETxPorteID = new XFRMField(new Guid("1CBF474A-1CE0-479D-ADFA-1A6BBDC09130"), "PETxPorteID", "Porte", XInt16.CID, 2, 12, false, gCID, null, new Guid("909C976E-7CD9-4114-9F39-270CBEA62096")); // Int16;
            public XFRMField NewTabControl = new XFRMField(new Guid("7C3D54DF-446B-43A5-8E2B-0C861AA5F9CF"), "NewTabControl", "New Tab Control ", XString.CID, 8, 19, false, gCID, null, new Guid("00000000-0000-0000-0000-000000000000")); // String;
            public static class Fields
            {
                public static XFieldInfo PETxTutorID = new XFieldInfo(new Guid("9916100F-3927-48C9-8C56-6703C2001CB9"), "PETxTutorID", "Nome do Tutor", typeof(Guid), false, "");
                public static XFieldInfo PETxAnimalImagemID = new XFieldInfo(new Guid("1C5BBCCA-AD39-4CC6-9141-93356175BAD7"), "PETxAnimalImagemID", "Fotos", typeof(Guid), false, "");
                public static XFieldInfo Nome = new XFieldInfo(new Guid("A13344AD-99BD-43BC-921C-7E89443558E1"), "Nome", "Nome do PET", typeof(String), false, "");
                public static XFieldInfo ERPxSexoID = new XFieldInfo(new Guid("C692C20B-91EB-4D72-89DC-B2430B20639C"), "ERPxSexoID", "Gênero", typeof(Int16), false, "");
                public static XFieldInfo Cor = new XFieldInfo(new Guid("FB400415-09EE-4146-9C0B-47CCC8BCA0A8"), "Cor", "Cor", typeof(String), false, "");
                public static XFieldInfo PETxPelagemID = new XFieldInfo(new Guid("39D490D9-1B77-4A0E-83FF-57D8E62E2A2A"), "PETxPelagemID", "Pelagem", typeof(Int16), false, "");
                public static XFieldInfo PETxRacaID = new XFieldInfo(new Guid("A59368DE-8870-4139-BDEE-7A2550A35DDD"), "PETxRacaID", "Raça", typeof(Int16), false, "");
                public static XFieldInfo Familia = new XFieldInfo(new Guid("284DD889-1097-4D39-B4B1-394360C72728"), "Familia", "Família", typeof(String), false, "");
                public static XFieldInfo PETxPorteID = new XFieldInfo(new Guid("1CBF474A-1CE0-479D-ADFA-1A6BBDC09130"), "PETxPorteID", "Porte", typeof(Int16), false, "");
                public static XFieldInfo NewTabControl = new XFieldInfo(new Guid("7C3D54DF-446B-43A5-8E2B-0C861AA5F9CF"), "NewTabControl", "New Tab Control ", typeof(String), false, "");
            }
        }

        #endregion AnimalFRM

        #region TabFormTutoresFRM

        [XRegister(typeof(TabFormTutoresFRM), sCID, typeof(AnimalSAM))]
        public class TabFormTutoresFRM : XFRMModel
        {
            public const String sCID = "7793168C-3ED9-4332-B300-0BDE70E20DD3";
            public static new readonly Guid gCID = new Guid(sCID);
            static TabFormTutoresFRM()
            {
                gCID = new Guid(sCID);
            }
            public TabFormTutoresFRM()
            {
                ID = gCID;
                Name = "TabFormTutores";
                Title = "Tutores";
                MinRows = 6;
                ConfigCID = new Guid("00000000-0000-0000-0000-000000000000");
                ConfigPKFilter = false;
                ReferenceScripts = new String[] { "TFX.Core.Service.js", "Projecao.Core.CEP.js", "Projecao.Core.ERP.js", "Projecao.Core.IMC.js", "Projecao.Core.ISE.js", "Projecao.Core.PET.js" };
                Rect = new XRect(0, 0, 1, 10);
                Style = XFRMStyle.Normal;
                ActionContext = XActionContext.All;
                AddItem(PETxAnimalID);
                PETxAnimalID.CanInsert = true;
                PETxAnimalID.CanUpdate = true;
                PETxAnimalID.RowCount = 6;
                PETxAnimalID.ColCount = 32;
                PETxAnimalID.RowCountSmall = 6;
                PETxAnimalID.ColCountSmall = 32;
                PETxAnimalID.IsHidden = false;
                PETxAnimalID.IsHiddenSmall = false;
                PETxAnimalID.AdditionalTitle = "";
                PETxAnimalID.Icon = "";
                PETxAnimalID.Location = 1;
                PETxAnimalID.EditorCID = new Guid("083C4AC6-6C57-4BE4-8EFB-11B6B442FA4C");
                PETxAnimalID.Operator = XOperator.EqualTo;
                PETxAnimalID.ShowSpin = false;
                PETxAnimalID.HotkeyChar = "";
                PETxAnimalID.JustifyHeight = true;
                PETxAnimalID.AllowEmpty = true;
                PETxAnimalID.FontColor = "#000000";
                PETxAnimalID.FontStyle = XFontStyle.Normal;
                PETxAnimalID.ShowFooter = false;
                PETxAnimalID.ViewSAM = new Guid("00000000-0000-0000-0000-000000000000");
                PETxAnimalID.Order = 1;
                PETxAnimalID.Scale = -1;
                PETxAnimalID.Length = -1;
                PETxAnimalID.SearchAction = XSearchAction.Default;
                PETxAnimalID.TypeID = XInt32.CID;
                PETxAnimalID.AdditionalFieldsID = new Guid[] {  };
                PETxAnimalID.AdditionalDataFieldsID = new Guid[] {  };
                PETxAnimalID.GridFormCID = new Guid("E93E86DA-5BBD-47D9-84F7-9A6FB3BA950C");
                PETxAnimalID.TargetFilterFieldID = new Guid[] {  };
                PETxAnimalID.SourceFilterFieldID = new Guid[] {  };
                PETxAnimalID.TargetDisplayFieldID = new Guid[] {  };
                PETxAnimalID.SourceDisplayFieldID = new Guid[] {  };
                PETxAnimalID.DataSourceID = global::Projecao.Core.PET.Animal.AnimalTutorSVC.gCID;
                PETxAnimalID.AutoLoad = false;
                PETxAnimalID.FilterInative = true;
                PETxAnimalID.IsAnswer = false;
                PETxAnimalID.AllowMultiSelect = false;
            }
            public XFRMField PETxAnimalID = new XFRMField(new Guid("D885B042-0C1A-414F-8337-410E9D1583C4"), "PETxAnimalID", "Tutores deste PET", XInt32.CID, 6, 32, false, gCID, null, new Guid("DAB65D14-EC01-47DF-BD48-C78CA4C3D147")); // Int32;
            public static class Fields
            {
                public static XFieldInfo PETxAnimalID = new XFieldInfo(new Guid("D885B042-0C1A-414F-8337-410E9D1583C4"), "PETxAnimalID", "Tutores deste PET", typeof(Int32), false, "");
            }
        }

        #endregion TabFormTutoresFRM

        #region PETxAnimalIDFRM

        [XRegister(typeof(PETxAnimalIDFRM), sCID, typeof(AnimalSAM))]
        public class PETxAnimalIDFRM : XFRMModel
        {
            public const String sCID = "E93E86DA-5BBD-47D9-84F7-9A6FB3BA950C";
            public static new readonly Guid gCID = new Guid(sCID);
            static PETxAnimalIDFRM()
            {
                gCID = new Guid(sCID);
            }
            public PETxAnimalIDFRM()
            {
                ID = gCID;
                Name = "PETxAnimalID";
                Title = "Tutores deste PET";
                MinRows = 2;
                ConfigCID = new Guid("00000000-0000-0000-0000-000000000000");
                ConfigPKFilter = false;
                ReferenceScripts = new String[] { "TFX.Core.Service.js", "Projecao.Core.CEP.js", "Projecao.Core.ERP.js", "Projecao.Core.IMC.js", "Projecao.Core.ISE.js", "Projecao.Core.PET.js" };
                Rect = new XRect(11, 87, 129, 56);
                Style = XFRMStyle.Normal;
                ActionContext = XActionContext.All;
                AddItem(PETxTutorID);
                PETxTutorID.CanInsert = true;
                PETxTutorID.CanUpdate = true;
                PETxTutorID.RowCount = 2;
                PETxTutorID.ColCount = 22;
                PETxTutorID.RowCountSmall = 2;
                PETxTutorID.ColCountSmall = 22;
                PETxTutorID.IsHidden = false;
                PETxTutorID.IsHiddenSmall = false;
                PETxTutorID.AdditionalTitle = "";
                PETxTutorID.Icon = "";
                PETxTutorID.Location = 1;
                PETxTutorID.EditorCID = new Guid("66290387-F0AD-4746-A1F7-B0D8D4C5C2EE");
                PETxTutorID.Operator = XOperator.EqualTo;
                PETxTutorID.ShowSpin = false;
                PETxTutorID.HotkeyChar = "";
                PETxTutorID.JustifyHeight = false;
                PETxTutorID.AllowEmpty = true;
                PETxTutorID.FontColor = "#000000";
                PETxTutorID.FontStyle = XFontStyle.Normal;
                PETxTutorID.ShowFooter = false;
                PETxTutorID.ViewSAM = new Guid("00000000-0000-0000-0000-000000000000");
                PETxTutorID.Order = 1;
                PETxTutorID.Scale = -1;
                PETxTutorID.Length = -1;
                PETxTutorID.SearchAction = XSearchAction.Default;
                PETxTutorID.TypeID = XGuid.CID;
                PETxTutorID.AdditionalFieldsID = new Guid[] {  };
                PETxTutorID.AdditionalDataFieldsID = new Guid[] {  };
                PETxTutorID.TargetFilterFieldID = new Guid[] {  };
                PETxTutorID.SourceFilterFieldID = new Guid[] {  };
                PETxTutorID.TargetDisplayFieldID = new Guid[] { new Guid("74860929-152B-477A-A67D-FCDB0058AFDA"), new Guid("DD9D9831-AC67-420E-8753-799BA0A83785") };
                PETxTutorID.SourceDisplayFieldID = new Guid[] { new Guid("C6CAFF78-D747-4805-A654-A05461EC1592"), new Guid("B5FB98DA-7886-4B1A-8A37-B2C6E0B0E777") };
                PETxTutorID.DataSourceID = global::Projecao.Core.PET.Tutor.TutorSVC.gCID;
                PETxTutorID.AutoLoad = false;
                PETxTutorID.ApplicationID = new Guid("4D0080BB-3F8F-4DA2-8C24-F3F0B5E1051D");
                PETxTutorID.FilterInative = true;
                PETxTutorID.IsAnswer = false;
                PETxTutorID.AllowMultiSelect = false;
                AddItem(Numero);
                Numero.IsReadOnly = true;
                Numero.CanInsert = true;
                Numero.CanUpdate = true;
                Numero.RowCount = 2;
                Numero.ColCount = 10;
                Numero.RowCountSmall = 2;
                Numero.ColCountSmall = 10;
                Numero.IsHidden = false;
                Numero.IsHiddenSmall = false;
                Numero.AdditionalTitle = "";
                Numero.Icon = "";
                Numero.Location = 2;
                Numero.EditorCID = new Guid("F5982E79-BA45-40FB-85E1-9F2C8B90B6EF");
                Numero.Operator = XOperator.EqualTo;
                Numero.ShowSpin = false;
                Numero.HotkeyChar = "";
                Numero.JustifyHeight = false;
                Numero.AllowEmpty = true;
                Numero.FontColor = "#000000";
                Numero.FontStyle = XFontStyle.Normal;
                Numero.ShowFooter = false;
                Numero.ViewSAM = new Guid("00000000-0000-0000-0000-000000000000");
                Numero.Order = 2;
                Numero.Scale = -1;
                Numero.Length = -1;
                Numero.SearchAction = XSearchAction.Default;
                Numero.TypeID = XString.CID;
                Numero.AdditionalFieldsID = new Guid[] {  };
                Numero.AdditionalDataFieldsID = new Guid[] {  };
                Numero.TargetFilterFieldID = new Guid[] {  };
                Numero.SourceFilterFieldID = new Guid[] {  };
                Numero.TargetDisplayFieldID = new Guid[] {  };
                Numero.SourceDisplayFieldID = new Guid[] {  };
                Numero.AutoLoad = false;
                Numero.FilterInative = true;
                Numero.IsAnswer = false;
                Numero.AllowMultiSelect = false;
            }
            public XFRMField PETxTutorID = new XFRMField(new Guid("5697D814-B7B2-4C1F-B6D1-1FFDE548585F"), "PETxTutorID", "Tutor", XGuid.CID, 2, 22, false, gCID, null, new Guid("C4C122AD-EB32-4FF2-8ECC-95FDC81E30E6")); // Guid;
            public XFRMField Numero = new XFRMField(new Guid("3FA20829-0F01-45FF-B2EE-6D49131C8D3B"), "Numero", "CPF", XString.CID, 2, 10, false, gCID, null, new Guid("DD9D9831-AC67-420E-8753-799BA0A83785")); // String;
            public static class Fields
            {
                public static XFieldInfo PETxTutorID = new XFieldInfo(new Guid("5697D814-B7B2-4C1F-B6D1-1FFDE548585F"), "PETxTutorID", "Tutor", typeof(Guid), false, "");
                public static XFieldInfo Numero = new XFieldInfo(new Guid("3FA20829-0F01-45FF-B2EE-6D49131C8D3B"), "Numero", "CPF", typeof(String), false, "");
            }
        }

        #endregion PETxAnimalIDFRM

        #region TabFormVacinaFRM

        [XRegister(typeof(TabFormVacinaFRM), sCID, typeof(AnimalSAM))]
        public class TabFormVacinaFRM : XFRMModel
        {
            public const String sCID = "CBE3DC6D-54B7-487D-B738-3A29A6100B6C";
            public static new readonly Guid gCID = new Guid(sCID);
            static TabFormVacinaFRM()
            {
                gCID = new Guid(sCID);
            }
            public TabFormVacinaFRM()
            {
                ID = gCID;
                Name = "TabFormVacina";
                Title = "Vacinas";
                MinRows = 6;
                ConfigCID = new Guid("00000000-0000-0000-0000-000000000000");
                ConfigPKFilter = false;
                ReferenceScripts = new String[] { "TFX.Core.Service.js", "Projecao.Core.CEP.js", "Projecao.Core.ERP.js", "Projecao.Core.IMC.js", "Projecao.Core.ISE.js", "Projecao.Core.PET.js" };
                Rect = new XRect(0, 0, 1, 10);
                Style = XFRMStyle.Normal;
                ActionContext = XActionContext.All;
                AddItem(PETxAnimalVacina);
                PETxAnimalVacina.CanInsert = true;
                PETxAnimalVacina.CanUpdate = true;
                PETxAnimalVacina.RowCount = 6;
                PETxAnimalVacina.ColCount = 32;
                PETxAnimalVacina.RowCountSmall = 6;
                PETxAnimalVacina.ColCountSmall = 32;
                PETxAnimalVacina.IsHidden = false;
                PETxAnimalVacina.IsHiddenSmall = false;
                PETxAnimalVacina.AdditionalTitle = "";
                PETxAnimalVacina.Icon = "";
                PETxAnimalVacina.Location = 1;
                PETxAnimalVacina.EditorCID = new Guid("083C4AC6-6C57-4BE4-8EFB-11B6B442FA4C");
                PETxAnimalVacina.Operator = XOperator.EqualTo;
                PETxAnimalVacina.ShowSpin = false;
                PETxAnimalVacina.HotkeyChar = "";
                PETxAnimalVacina.JustifyHeight = true;
                PETxAnimalVacina.AllowEmpty = true;
                PETxAnimalVacina.FontColor = "#000000";
                PETxAnimalVacina.FontStyle = XFontStyle.Normal;
                PETxAnimalVacina.ShowFooter = false;
                PETxAnimalVacina.ViewSAM = new Guid("00000000-0000-0000-0000-000000000000");
                PETxAnimalVacina.Order = 1;
                PETxAnimalVacina.Scale = -1;
                PETxAnimalVacina.Length = -1;
                PETxAnimalVacina.SearchAction = XSearchAction.Default;
                PETxAnimalVacina.TypeID = XGuid.CID;
                PETxAnimalVacina.AdditionalFieldsID = new Guid[] {  };
                PETxAnimalVacina.AdditionalDataFieldsID = new Guid[] {  };
                PETxAnimalVacina.GridFormCID = new Guid("3F8B1B6D-8063-4440-AD6A-805C76E60DBB");
                PETxAnimalVacina.EditGridFormCID = new Guid("57F4E6A7-9080-49EA-B4CC-2D814A0F1543");
                PETxAnimalVacina.TargetFilterFieldID = new Guid[] {  };
                PETxAnimalVacina.SourceFilterFieldID = new Guid[] {  };
                PETxAnimalVacina.TargetDisplayFieldID = new Guid[] {  };
                PETxAnimalVacina.SourceDisplayFieldID = new Guid[] {  };
                PETxAnimalVacina.DataSourceID = global::Projecao.Core.PET.Animal.VacinasSVC.gCID;
                PETxAnimalVacina.AutoLoad = false;
                PETxAnimalVacina.FilterInative = true;
                PETxAnimalVacina.IsAnswer = false;
                PETxAnimalVacina.AllowMultiSelect = false;
            }
            public XFRMField PETxAnimalVacina = new XFRMField(new Guid("57229F9A-E878-4FB6-A6AD-46C1E1AA3671"), "PETxAnimalVacina", "PET", XGuid.CID, 6, 32, false, gCID, null, new Guid("DAB65D14-EC01-47DF-BD48-C78CA4C3D147")); // Guid;
            public static class Fields
            {
                public static XFieldInfo PETxAnimalVacina = new XFieldInfo(new Guid("57229F9A-E878-4FB6-A6AD-46C1E1AA3671"), "PETxAnimalVacina", "PET", typeof(Guid), false, "");
            }
        }

        #endregion TabFormVacinaFRM

        #region PETxAnimalVacinaFRM

        [XRegister(typeof(PETxAnimalVacinaFRM), sCID, typeof(AnimalSAM))]
        public class PETxAnimalVacinaFRM : XFRMModel
        {
            public const String sCID = "3F8B1B6D-8063-4440-AD6A-805C76E60DBB";
            public static new readonly Guid gCID = new Guid(sCID);
            static PETxAnimalVacinaFRM()
            {
                gCID = new Guid(sCID);
            }
            public PETxAnimalVacinaFRM()
            {
                ID = gCID;
                Name = "PETxAnimalVacina";
                Title = "PET";
                MinRows = 2;
                ConfigCID = new Guid("00000000-0000-0000-0000-000000000000");
                ConfigPKFilter = false;
                ReferenceScripts = new String[] { "TFX.Core.Service.js", "Projecao.Core.CEP.js", "Projecao.Core.ERP.js", "Projecao.Core.IMC.js", "Projecao.Core.ISE.js", "Projecao.Core.PET.js" };
                Rect = new XRect(-10, 44, 229, 144);
                Style = XFRMStyle.Normal;
                ActionContext = XActionContext.All;
                AddItem(ISExVacinaID);
                ISExVacinaID.CanInsert = true;
                ISExVacinaID.CanUpdate = true;
                ISExVacinaID.RowCount = 2;
                ISExVacinaID.ColCount = 14;
                ISExVacinaID.RowCountSmall = 2;
                ISExVacinaID.ColCountSmall = 14;
                ISExVacinaID.IsHidden = false;
                ISExVacinaID.IsHiddenSmall = false;
                ISExVacinaID.AdditionalTitle = "";
                ISExVacinaID.Icon = "";
                ISExVacinaID.Location = 1;
                ISExVacinaID.EditorCID = new Guid("66290387-F0AD-4746-A1F7-B0D8D4C5C2EE");
                ISExVacinaID.Operator = XOperator.EqualTo;
                ISExVacinaID.ShowSpin = false;
                ISExVacinaID.HotkeyChar = "";
                ISExVacinaID.JustifyHeight = false;
                ISExVacinaID.AllowEmpty = true;
                ISExVacinaID.FontColor = "#000000";
                ISExVacinaID.FontStyle = XFontStyle.Normal;
                ISExVacinaID.ShowFooter = false;
                ISExVacinaID.ViewSAM = new Guid("00000000-0000-0000-0000-000000000000");
                ISExVacinaID.Order = 1;
                ISExVacinaID.Scale = -1;
                ISExVacinaID.Length = -1;
                ISExVacinaID.SearchAction = XSearchAction.Default;
                ISExVacinaID.TypeID = XGuid.CID;
                ISExVacinaID.AdditionalFieldsID = new Guid[] {  };
                ISExVacinaID.AdditionalDataFieldsID = new Guid[] {  };
                ISExVacinaID.TargetFilterFieldID = new Guid[] {  };
                ISExVacinaID.SourceFilterFieldID = new Guid[] {  };
                ISExVacinaID.TargetDisplayFieldID = new Guid[] { new Guid("02F93D68-8BCC-405D-B89A-93FEEADDE23B") };
                ISExVacinaID.SourceDisplayFieldID = new Guid[] { new Guid("CAF9CBF5-82DF-4924-89AE-EB62E6F1E5F8") };
                ISExVacinaID.DataSourceID = global::Projecao.Core.PET.ReadOnly.VacinaSVC.gCID;
                ISExVacinaID.AutoLoad = false;
                ISExVacinaID.FilterInative = true;
                ISExVacinaID.IsAnswer = false;
                ISExVacinaID.AllowMultiSelect = false;
                AddItem(DataRealizar);
                DataRealizar.CanInsert = true;
                DataRealizar.CanUpdate = true;
                DataRealizar.RowCount = 2;
                DataRealizar.ColCount = 7;
                DataRealizar.RowCountSmall = 2;
                DataRealizar.ColCountSmall = 7;
                DataRealizar.IsHidden = false;
                DataRealizar.IsHiddenSmall = false;
                DataRealizar.AdditionalTitle = "";
                DataRealizar.Icon = "";
                DataRealizar.Location = 2;
                DataRealizar.EditorCID = new Guid("00292032-E4A9-4A74-8B31-BF42D90A137A");
                DataRealizar.Operator = XOperator.EqualTo;
                DataRealizar.ShowSpin = false;
                DataRealizar.HotkeyChar = "";
                DataRealizar.JustifyHeight = false;
                DataRealizar.AllowEmpty = true;
                DataRealizar.FontColor = "#000000";
                DataRealizar.FontStyle = XFontStyle.Normal;
                DataRealizar.ShowFooter = false;
                DataRealizar.ViewSAM = new Guid("00000000-0000-0000-0000-000000000000");
                DataRealizar.Order = 2;
                DataRealizar.Scale = -1;
                DataRealizar.Length = -1;
                DataRealizar.SearchAction = XSearchAction.Default;
                DataRealizar.TypeID = XDate.CID;
                DataRealizar.AdditionalFieldsID = new Guid[] {  };
                DataRealizar.AdditionalDataFieldsID = new Guid[] {  };
                DataRealizar.TargetFilterFieldID = new Guid[] {  };
                DataRealizar.SourceFilterFieldID = new Guid[] {  };
                DataRealizar.TargetDisplayFieldID = new Guid[] {  };
                DataRealizar.SourceDisplayFieldID = new Guid[] {  };
                DataRealizar.AutoLoad = false;
                DataRealizar.FilterInative = true;
                DataRealizar.IsAnswer = false;
                DataRealizar.AllowMultiSelect = false;
                AddItem(Doses);
                Doses.CanInsert = true;
                Doses.CanUpdate = true;
                Doses.RowCount = 2;
                Doses.ColCount = 6;
                Doses.RowCountSmall = 2;
                Doses.ColCountSmall = 6;
                Doses.IsHidden = false;
                Doses.IsHiddenSmall = false;
                Doses.AdditionalTitle = "";
                Doses.Icon = "";
                Doses.Location = 3;
                Doses.EditorCID = new Guid("6FD76216-1D13-4438-B568-72556767B3DF");
                Doses.Operator = XOperator.EqualTo;
                Doses.ShowSpin = false;
                Doses.HotkeyChar = "";
                Doses.JustifyHeight = false;
                Doses.AllowEmpty = true;
                Doses.FontColor = "#000000";
                Doses.FontStyle = XFontStyle.Normal;
                Doses.ShowFooter = false;
                Doses.ViewSAM = new Guid("00000000-0000-0000-0000-000000000000");
                Doses.Order = 3;
                Doses.Scale = 0;
                Doses.Length = 0;
                Doses.SearchAction = XSearchAction.Default;
                Doses.TypeID = XInt32.CID;
                Doses.AdditionalFieldsID = new Guid[] {  };
                Doses.AdditionalDataFieldsID = new Guid[] {  };
                Doses.TargetFilterFieldID = new Guid[] {  };
                Doses.SourceFilterFieldID = new Guid[] {  };
                Doses.TargetDisplayFieldID = new Guid[] {  };
                Doses.SourceDisplayFieldID = new Guid[] {  };
                Doses.AutoLoad = false;
                Doses.FilterInative = true;
                Doses.IsAnswer = false;
                Doses.AllowMultiSelect = false;
                AddItem(Intervalo);
                Intervalo.CanInsert = true;
                Intervalo.CanUpdate = true;
                Intervalo.RowCount = 2;
                Intervalo.ColCount = 5;
                Intervalo.RowCountSmall = 2;
                Intervalo.ColCountSmall = 5;
                Intervalo.IsHidden = false;
                Intervalo.IsHiddenSmall = false;
                Intervalo.AdditionalTitle = "";
                Intervalo.Icon = "";
                Intervalo.Location = 4;
                Intervalo.EditorCID = new Guid("6FD76216-1D13-4438-B568-72556767B3DF");
                Intervalo.Operator = XOperator.EqualTo;
                Intervalo.ShowSpin = false;
                Intervalo.HotkeyChar = "";
                Intervalo.JustifyHeight = false;
                Intervalo.AllowEmpty = true;
                Intervalo.FontColor = "#000000";
                Intervalo.FontStyle = XFontStyle.Normal;
                Intervalo.ShowFooter = false;
                Intervalo.ViewSAM = new Guid("00000000-0000-0000-0000-000000000000");
                Intervalo.Order = 4;
                Intervalo.Scale = 0;
                Intervalo.Length = 0;
                Intervalo.SearchAction = XSearchAction.Default;
                Intervalo.TypeID = XInt32.CID;
                Intervalo.AdditionalFieldsID = new Guid[] {  };
                Intervalo.AdditionalDataFieldsID = new Guid[] {  };
                Intervalo.TargetFilterFieldID = new Guid[] {  };
                Intervalo.SourceFilterFieldID = new Guid[] {  };
                Intervalo.TargetDisplayFieldID = new Guid[] {  };
                Intervalo.SourceDisplayFieldID = new Guid[] {  };
                Intervalo.AutoLoad = false;
                Intervalo.FilterInative = true;
                Intervalo.IsAnswer = false;
                Intervalo.AllowMultiSelect = false;
            }
            public XFRMField ISExVacinaID = new XFRMField(new Guid("D061BF27-E3ED-4120-A7BF-19D4E4310B2A"), "ISExVacinaID", "Vacina", XGuid.CID, 2, 14, false, gCID, null, new Guid("E36B1DCF-4356-43D1-B4E8-5167BBE72F8B")); // Guid;
            public XFRMField DataRealizar = new XFRMField(new Guid("BEF1E81A-E780-4559-BDE8-5CE9BBD64C46"), "DataRealizar", "Primeira Dose", XDateTime.CID, 2, 7, false, gCID, null, new Guid("61C972DD-F0DA-48EA-BF34-119B19E0D8A6")); // DateTime;
            public XFRMField Doses = new XFRMField(new Guid("43321034-EDB2-45BE-9A62-2DE74D7E6525"), "Doses", "Quantidade de Doses", XInt32.CID, 2, 6, false, gCID, null, new Guid("81FCFF7C-A47E-4723-A1D6-1BBC3D66907B")); // Int32;
            public XFRMField Intervalo = new XFRMField(new Guid("33BC4AFD-10C2-471A-8D13-0EFF9E5A013A"), "Intervalo", "Intervalo (dias)", XInt32.CID, 2, 5, false, gCID, null, new Guid("BF55B20A-C72C-4CC4-AE7B-6370A49EB6C2")); // Int32;
            public static class Fields
            {
                public static XFieldInfo ISExVacinaID = new XFieldInfo(new Guid("D061BF27-E3ED-4120-A7BF-19D4E4310B2A"), "ISExVacinaID", "Vacina", typeof(Guid), false, "");
                public static XFieldInfo DataRealizar = new XFieldInfo(new Guid("BEF1E81A-E780-4559-BDE8-5CE9BBD64C46"), "DataRealizar", "Primeira Dose", typeof(DateTime), false, "dd/MM/yyyy");
                public static XFieldInfo Doses = new XFieldInfo(new Guid("43321034-EDB2-45BE-9A62-2DE74D7E6525"), "Doses", "Quantidade de Doses", typeof(Int32), false, "");
                public static XFieldInfo Intervalo = new XFieldInfo(new Guid("33BC4AFD-10C2-471A-8D13-0EFF9E5A013A"), "Intervalo", "Intervalo (dias)", typeof(Int32), false, "");
            }
        }

        #endregion PETxAnimalVacinaFRM

        #region FRM

        [XRegister(typeof(FRM), sCID, typeof(AnimalSAM))]
        public class FRM : XFRMModel
        {
            public const String sCID = "57F4E6A7-9080-49EA-B4CC-2D814A0F1543";
            public static new readonly Guid gCID = new Guid(sCID);
            static FRM()
            {
                gCID = new Guid(sCID);
            }
            public FRM()
            {
                ID = gCID;
                Name = "";
                Title = "";
                MinRows = 2;
                ConfigCID = new Guid("00000000-0000-0000-0000-000000000000");
                ConfigPKFilter = false;
                ReferenceScripts = new String[] { "TFX.Core.Service.js", "Projecao.Core.CEP.js", "Projecao.Core.ERP.js", "Projecao.Core.IMC.js", "Projecao.Core.ISE.js", "Projecao.Core.PET.js" };
                Rect = new XRect(5, 78, 176, 84);
                Style = XFRMStyle.Normal;
                ActionContext = XActionContext.All;
                AddItem(ISExVacinaID);
                ISExVacinaID.CanInsert = true;
                ISExVacinaID.CanUpdate = true;
                ISExVacinaID.RowCount = 2;
                ISExVacinaID.ColCount = 21;
                ISExVacinaID.RowCountSmall = 2;
                ISExVacinaID.ColCountSmall = 21;
                ISExVacinaID.IsHidden = false;
                ISExVacinaID.IsHiddenSmall = false;
                ISExVacinaID.AdditionalTitle = "";
                ISExVacinaID.Icon = "";
                ISExVacinaID.Location = 1;
                ISExVacinaID.EditorCID = new Guid("66290387-F0AD-4746-A1F7-B0D8D4C5C2EE");
                ISExVacinaID.Operator = XOperator.EqualTo;
                ISExVacinaID.ShowSpin = false;
                ISExVacinaID.HotkeyChar = "";
                ISExVacinaID.JustifyHeight = false;
                ISExVacinaID.AllowEmpty = true;
                ISExVacinaID.FontColor = "#000000";
                ISExVacinaID.FontStyle = XFontStyle.Normal;
                ISExVacinaID.ShowFooter = false;
                ISExVacinaID.ViewSAM = new Guid("00000000-0000-0000-0000-000000000000");
                ISExVacinaID.Order = 1;
                ISExVacinaID.Scale = -1;
                ISExVacinaID.Length = -1;
                ISExVacinaID.SearchAction = XSearchAction.Default;
                ISExVacinaID.TypeID = XGuid.CID;
                ISExVacinaID.AdditionalFieldsID = new Guid[] {  };
                ISExVacinaID.AdditionalDataFieldsID = new Guid[] {  };
                ISExVacinaID.TargetFilterFieldID = new Guid[] {  };
                ISExVacinaID.SourceFilterFieldID = new Guid[] {  };
                ISExVacinaID.TargetDisplayFieldID = new Guid[] { new Guid("02F93D68-8BCC-405D-B89A-93FEEADDE23B") };
                ISExVacinaID.SourceDisplayFieldID = new Guid[] { new Guid("CAF9CBF5-82DF-4924-89AE-EB62E6F1E5F8") };
                ISExVacinaID.DataSourceID = global::Projecao.Core.PET.ReadOnly.VacinaSVC.gCID;
                ISExVacinaID.AutoLoad = false;
                ISExVacinaID.FilterInative = true;
                ISExVacinaID.IsAnswer = false;
                ISExVacinaID.AllowMultiSelect = false;
                AddItem(DataRealizar);
                DataRealizar.CanInsert = true;
                DataRealizar.CanUpdate = true;
                DataRealizar.RowCount = 2;
                DataRealizar.ColCount = 11;
                DataRealizar.RowCountSmall = 2;
                DataRealizar.ColCountSmall = 11;
                DataRealizar.IsHidden = false;
                DataRealizar.IsHiddenSmall = false;
                DataRealizar.AdditionalTitle = "";
                DataRealizar.Icon = "";
                DataRealizar.Location = 2;
                DataRealizar.EditorCID = new Guid("00292032-E4A9-4A74-8B31-BF42D90A137A");
                DataRealizar.Operator = XOperator.EqualTo;
                DataRealizar.ShowSpin = false;
                DataRealizar.HotkeyChar = "";
                DataRealizar.JustifyHeight = false;
                DataRealizar.AllowEmpty = true;
                DataRealizar.FontColor = "#000000";
                DataRealizar.FontStyle = XFontStyle.Normal;
                DataRealizar.ShowFooter = false;
                DataRealizar.ViewSAM = new Guid("00000000-0000-0000-0000-000000000000");
                DataRealizar.Order = 2;
                DataRealizar.Scale = -1;
                DataRealizar.Length = -1;
                DataRealizar.SearchAction = XSearchAction.Default;
                DataRealizar.TypeID = XDate.CID;
                DataRealizar.AdditionalFieldsID = new Guid[] {  };
                DataRealizar.AdditionalDataFieldsID = new Guid[] {  };
                DataRealizar.TargetFilterFieldID = new Guid[] {  };
                DataRealizar.SourceFilterFieldID = new Guid[] {  };
                DataRealizar.TargetDisplayFieldID = new Guid[] {  };
                DataRealizar.SourceDisplayFieldID = new Guid[] {  };
                DataRealizar.AutoLoad = false;
                DataRealizar.FilterInative = true;
                DataRealizar.IsAnswer = false;
                DataRealizar.AllowMultiSelect = false;
            }
            public XFRMField ISExVacinaID = new XFRMField(new Guid("F7505C3A-E722-4622-AC51-712B4C563265"), "ISExVacinaID", "Vacina", XGuid.CID, 2, 21, false, gCID, null, new Guid("E36B1DCF-4356-43D1-B4E8-5167BBE72F8B")); // Guid;
            public XFRMField DataRealizar = new XFRMField(new Guid("D5B175D1-8035-48B9-AC78-7C7D050761F6"), "DataRealizar", "Data para Realizar", XDateTime.CID, 2, 11, false, gCID, null, new Guid("61C972DD-F0DA-48EA-BF34-119B19E0D8A6")); // DateTime;
            public static class Fields
            {
                public static XFieldInfo ISExVacinaID = new XFieldInfo(new Guid("F7505C3A-E722-4622-AC51-712B4C563265"), "ISExVacinaID", "Vacina", typeof(Guid), false, "");
                public static XFieldInfo DataRealizar = new XFieldInfo(new Guid("D5B175D1-8035-48B9-AC78-7C7D050761F6"), "DataRealizar", "Data para Realizar", typeof(DateTime), false, "dd/MM/yyyy");
            }
        }

        #endregion FRM

        public const String sCID = "40A48D39-D7A5-477D-9D7E-D65525757414";
        public static Guid gCID = new Guid(sCID);
        public static readonly xAnimalACT AnimalACT;

        static AnimalSAM()
        {
            AnimalACT = new xAnimalACT(new Guid("E4E4F5CA-17E0-4363-9D65-CE339AA81E91"), "AnimalACT", "PET", new Guid("A675C8B1-80AD-4347-842B-7E7F95B345D8"), new Guid("00000000-0000-0000-0000-000000000000"));
        }

        public AnimalSAM()
        {
            ID = new Guid("40A48D39-D7A5-477D-9D7E-D65525757414");
            Name = "Animal";
            Title = "PETs";
            AppTypeID = XAppType.SAM;
            Userlevel = global::TFX.Core.Service.Apps.CTLx.CTLxGrupoTipo.XDefault.Usuarios;
            UseTypeID = new Int16[] { 2 };
            Rights = new Int16[] { 3, 6, 4, 1, 5, 2 }; 
            IsDisabled = false;
            StartAction = XStartAction.DataGrid;
            ReferenceScripts = new String[] { "TFX.Core.Service.js", "Projecao.Core.CEP.js", "Projecao.Core.ERP.js", "Projecao.Core.IMC.js", "Projecao.Core.ISE.js", "Projecao.Core.PET.js" };
            Size = new Size(345, 150);
            DataSourceID = global::Projecao.Core.PET.Animal.AnimalSVC.gCID;
            AppModulesID = new [] { (Int16)14 };
            AppGroupsID = new [] { (Int16)2 };
            AnimalACT.FormID = new Guid("A675C8B1-80AD-4347-842B-7E7F95B345D8"); 
            AnimalACT.Type = XActivityType.UserActivity;
            AddItem(AnimalACT);
        }
    }
}