//<auto-generated/>
using System;
using System.Linq;
using Newtonsoft.Json;
using TFX.Core.Objects;
using TFX.Core.Model.Data;
using TFX.Core.Model.Cache;
using TFX.Core.Reflections;
using TFX.Core.Service.Job;
using TFX.Core.Service.SVC;
using Projecao.Core.CRD.DB;
using TFX.Core.Service.Apps;
using TFX.Core.Model.DIC.SVC;
using TFX.Core.Model.DIC.ORM;
using TFX.Core.Model.DIC.FRM;
using TFX.Core.Model.DIC.APP;
using TFX.Core.Model.DIC.RPT;
using TFX.Core.Model.Services;
using TFX.Core.Model.DIC.Types;
using TFX.Core.Model.Interfaces;
using System.Collections.Generic;
using System.Runtime.InteropServices;

namespace Projecao.Core.CRD.Relatorios.AutorizacoesSitentico
{
    [XRegister(typeof(AutorizacoesSinteticoSVC), sCID)]
    [XDASESource(@"D:\Tootega\Source\TFX20\Modules\Projecao.Core.CRD\Projecao.Core.CRD.csproj", @"D:\Tootega\Source\TFX20\Modules\Projecao.Core.CRD\Relatorios\AutorizacoesSitentico\AutorizacoesSintetico.dssvc")]
    public class AutorizacoesSinteticoSVC : XSVCModel
    {
        #region AutorizacoesSinteticoFilterFRM

        [XRegister(typeof(AutorizacoesSinteticoFilterFRM), sCID)]
        public class AutorizacoesSinteticoFilterFRM : XFRMModel
        {
            public const String sCID = "C66F687E-569A-42C1-8365-173CB2014338";
            static AutorizacoesSinteticoFilterFRM()
            {
                gCID = new Guid(sCID);
            }
            public AutorizacoesSinteticoFilterFRM()
            {
                ID = gCID;
                Name = "AutorizacoesSinteticoFilter";
                Title = "";
                MinRows = 0;
                ConfigCID = new Guid("00000000-0000-0000-0000-000000000000");
                ConfigPKFilter = false;
                Rect = new XRect(0, 0, 964, 92);
                Style = XFRMStyle.Normal;
                ActionContext = XActionContext.All;
            }
            public static class Fields
            {
            }
        }

        #endregion AutorizacoesSinteticoFilterFRM

        public const String sCID = "6DD101EF-E3A9-4530-9A0A-5F5265B96617";
        public static Guid gCID = new Guid(sCID);
        public static XSVCReference CRDxCartaoLog_CRDxCartaoLogID_CRDxCartaoVenda_CRDxCartaoVendaID; // CRDxCartaoLog.CRDxCartaoLogID --> CRDxCartaoVenda.CRDxCartaoVendaID
        public static XSVCReference CRDxPontoVenda_CRDxPontoVendaID_SYSxPessoa_SYSxPessoaID; // CRDxPontoVenda.CRDxPontoVendaID --> SYSxPessoa.SYSxPessoaID
        public static XSVCReference CRDxCartaoLog_CRDxPontoVendaID_CRDxPontoVenda_CRDxPontoVendaID; // CRDxCartaoLog.CRDxPontoVendaID --> CRDxPontoVenda.CRDxPontoVendaID

        #region xSYSxPessoa 
        public class xSYSxPessoa : XSVCTable
        {

            public static Guid gCID => new Guid("51F26479-E5B9-4E0B-9EE6-0FE21EE06B13");

            public xSYSxPessoa()
            {
                Name = "SYSxPessoa";
                Alias = "SYSxPessoa";
                ID = gCID;
                ParentID =  global::TFX.Core.Service.Apps.SYSx.SYSxPessoa.gCID;

                Items.Add(Nome, Nome.ID);
                Nome.Owner = this;
                Nome.OwnerID = ID;
                Nome.TableName = Name;
                Nome.Alias = "Nome";
                Items.Add(SYSxPessoaID, SYSxPessoaID.ID);
                SYSxPessoaID.Owner = this;
                SYSxPessoaID.OwnerID = ID;
                SYSxPessoaID.TableName = Name;
            }

            public static XORMFaceField Nome = new XORMFaceField(global::TFX.Core.Service.Apps.SYSx.SYSxPessoa.Nome, new Guid("0915597A-7EDC-48E5-85CE-6DB6FDC4EE53"), "Nome", "Nome do Franqueado");
            public static XORMPKField SYSxPessoaID = new XORMPKField(global::TFX.Core.Service.Apps.SYSx.SYSxPessoa.SYSxPessoaID, new Guid("E004ACD6-D716-4AA5-B068-1237A0974C7B"), "SYSxPessoaID", "Pessoas");
        }
        #endregion xSYSxPessoa 


        #region xCRDxCartaoVenda 
        public class xCRDxCartaoVenda : XSVCTable
        {

            public static Guid gCID => new Guid("611A9428-2181-4BC4-B87B-25D929F4DE4F");

            public xCRDxCartaoVenda()
            {
                Name = "CRDxCartaoVenda";
                Alias = "CRDxCartaoVenda";
                ID = gCID;
                ParentID =  global::Projecao.Core.CRD.DB.CRDx.CRDxCartaoVenda.gCID;

                Items.Add(CRDxCartaoVendaID, CRDxCartaoVendaID.ID);
                CRDxCartaoVendaID.Owner = this;
                CRDxCartaoVendaID.OwnerID = ID;
                CRDxCartaoVendaID.TableName = Name;
                Items.Add(CRDxCartaoID, CRDxCartaoID.ID);
                CRDxCartaoID.Owner = this;
                CRDxCartaoID.OwnerID = ID;
                CRDxCartaoID.TableName = Name;
                Items.Add(DadosVenda, DadosVenda.ID);
                DadosVenda.Owner = this;
                DadosVenda.OwnerID = ID;
                DadosVenda.TableName = Name;
                Items.Add(SYSxEstadoID, SYSxEstadoID.ID);
                SYSxEstadoID.Owner = this;
                SYSxEstadoID.OwnerID = ID;
                SYSxEstadoID.TableName = Name;
                Items.Add(FaturadoFranqueado, FaturadoFranqueado.ID);
                FaturadoFranqueado.Owner = this;
                FaturadoFranqueado.OwnerID = ID;
                FaturadoFranqueado.TableName = Name;
                Items.Add(FaturadoCartao, FaturadoCartao.ID);
                FaturadoCartao.Owner = this;
                FaturadoCartao.OwnerID = ID;
                FaturadoCartao.TableName = Name;
            }

            public static XORMPKField CRDxCartaoVendaID = new XORMPKField(global::Projecao.Core.CRD.DB.CRDx.CRDxCartaoVenda.CRDxCartaoVendaID, new Guid("CDF45349-1F7C-4C4D-818F-85C3EAE5E060"), "CRDxCartaoVendaID", "Venda por cartão");
            public static XORMFKField CRDxCartaoID = new XORMFKField(global::Projecao.Core.CRD.DB.CRDx.CRDxCartaoVenda.CRDxCartaoID, new Guid("EF3FC578-400E-4C5F-B321-0C864D72A771"), "CRDxCartaoID", "Cartão");
            public static XORMField DadosVenda = new XORMField(global::Projecao.Core.CRD.DB.CRDx.CRDxCartaoVenda.DadosVenda, new Guid("882109A0-369F-47DE-85DB-EAFA908C8D1B"), "DadosVenda", "Dado da venda");
            public static XORMStateField SYSxEstadoID = new XORMStateField(global::Projecao.Core.CRD.DB.CRDx.CRDxCartaoVenda.SYSxEstadoID, new Guid("0E884C4C-0C99-428C-84B6-C0F6A7BC4A1B"), "SYSxEstadoID", "Estado");
            public static XORMField FaturadoFranqueado = new XORMField(global::Projecao.Core.CRD.DB.CRDx.CRDxCartaoVenda.FaturadoFranqueado, new Guid("2E0B7B86-B494-4CD6-8914-D47F94347F84"), "FaturadoFranqueado", "Faturado para Franqueado");
            public static XORMField FaturadoCartao = new XORMField(global::Projecao.Core.CRD.DB.CRDx.CRDxCartaoVenda.FaturadoCartao, new Guid("251E6257-BD2C-4013-AA80-B3EEFC58379E"), "FaturadoCartao", "Faturado para Cartão");
        }
        #endregion xCRDxCartaoVenda 


        #region xCRDxCartaoLog 
        public class xCRDxCartaoLog : XSVCTable
        {

            public static Guid gCID => new Guid("B9485236-7C7B-4E03-93CF-15742CAE9B1B");

            public xCRDxCartaoLog()
            {
                Name = "CRDxCartaoLog";
                Alias = "CRDxCartaoLog";
                ID = gCID;
                ParentID =  global::Projecao.Core.CRD.DB.CRDx.CRDxCartaoLog.gCID;

                Items.Add(CRDxCartaoID, CRDxCartaoID.ID);
                CRDxCartaoID.Owner = this;
                CRDxCartaoID.OwnerID = ID;
                CRDxCartaoID.TableName = Name;
                Items.Add(CRDxCartaoLogID, CRDxCartaoLogID.ID);
                CRDxCartaoLogID.Owner = this;
                CRDxCartaoLogID.OwnerID = ID;
                CRDxCartaoLogID.TableName = Name;
                Items.Add(CRDxPontoVendaID, CRDxPontoVendaID.ID);
                CRDxPontoVendaID.Owner = this;
                CRDxPontoVendaID.OwnerID = ID;
                CRDxPontoVendaID.TableName = Name;
                CRDxPontoVendaID.Alias = "CRDxPontoVendaID";
                Items.Add(Mensagem, Mensagem.ID);
                Mensagem.Owner = this;
                Mensagem.OwnerID = ID;
                Mensagem.TableName = Name;
                Items.Add(Data, Data.ID);
                Data.Owner = this;
                Data.OwnerID = ID;
                Data.TableName = Name;
                Items.Add(Valor, Valor.ID);
                Valor.Owner = this;
                Valor.OwnerID = ID;
                Valor.TableName = Name;
                Valor.Alias = "Valor";
                Items.Add(CRDxCartaoLogTipoID, CRDxCartaoLogTipoID.ID);
                CRDxCartaoLogTipoID.Owner = this;
                CRDxCartaoLogTipoID.OwnerID = ID;
                CRDxCartaoLogTipoID.TableName = Name;
                Items.Add(NumeroVenda, NumeroVenda.ID);
                NumeroVenda.Owner = this;
                NumeroVenda.OwnerID = ID;
                NumeroVenda.TableName = Name;
                Items.Add(CRDxCartaoLogOrigemID, CRDxCartaoLogOrigemID.ID);
                CRDxCartaoLogOrigemID.Owner = this;
                CRDxCartaoLogOrigemID.OwnerID = ID;
                CRDxCartaoLogOrigemID.TableName = Name;
                Items.Add(Origem, Origem.ID);
                Origem.Owner = this;
                Origem.OwnerID = ID;
                Origem.TableName = Name;
                Items.Add(Desconto, Desconto.ID);
                Desconto.Owner = this;
                Desconto.OwnerID = ID;
                Desconto.TableName = Name;
            }

            public static XORMFKField CRDxCartaoID = new XORMFKField(global::Projecao.Core.CRD.DB.CRDx.CRDxCartaoLog.CRDxCartaoID, new Guid("064B9629-6EEA-430C-8248-170D4AE81C5C"), "CRDxCartaoID", "Cartão");
            public static XORMFaceField CRDxCartaoLogID = new XORMFaceField(global::Projecao.Core.CRD.DB.CRDx.CRDxCartaoLog.CRDxCartaoLogID, new Guid("9ECBA948-C92C-453F-A233-2339F7C8656C"), "CRDxCartaoLogID", "Log de Atividades");
            public static XORMFKField CRDxPontoVendaID = new XORMFKField(global::Projecao.Core.CRD.DB.CRDx.CRDxCartaoLog.CRDxPontoVendaID, new Guid("C7F374C1-5DCE-45D4-A4B5-FF17E2FA5698"), "CRDxPontoVendaID", "Ponto de Venda");
            public static XORMField Mensagem = new XORMField(global::Projecao.Core.CRD.DB.CRDx.CRDxCartaoLog.Mensagem, new Guid("6E859CF6-91A5-42A7-9650-D846CECEC63E"), "Mensagem", "Mensagem");
            public static XORMDateTimeField Data = new XORMDateTimeField(global::Projecao.Core.CRD.DB.CRDx.CRDxCartaoLog.Data, new Guid("98652AA5-CB82-46DE-B822-A1377DFD1395"), "Data", "Data Ocorrência");
            public static XORMDecimalField Valor = new XORMDecimalField(global::Projecao.Core.CRD.DB.CRDx.CRDxCartaoLog.Valor, new Guid("84862BEC-DA80-439B-A1B6-2A411B7C1934"), "Valor", "Valor");
            public static XORMFKField CRDxCartaoLogTipoID = new XORMFKField(global::Projecao.Core.CRD.DB.CRDx.CRDxCartaoLog.CRDxCartaoLogTipoID, new Guid("E0C159D4-10B7-4709-88D5-DE04B98ED53F"), "CRDxCartaoLogTipoID", "Tipo de Log de Cartão");
            public static XORMField NumeroVenda = new XORMField(global::Projecao.Core.CRD.DB.CRDx.CRDxCartaoLog.NumeroVenda, new Guid("9609A1CC-B716-4AF6-946F-2A9F807DF7AF"), "NumeroVenda", "Número da Venda");
            public static XORMFKField CRDxCartaoLogOrigemID = new XORMFKField(global::Projecao.Core.CRD.DB.CRDx.CRDxCartaoLog.CRDxCartaoLogOrigemID, new Guid("AFE17D1E-D0C0-4E36-B453-94AD74924BAE"), "CRDxCartaoLogOrigemID", "Log de Atividades");
            public static XORMField Origem = new XORMField(global::Projecao.Core.CRD.DB.CRDx.CRDxCartaoLog.Origem, new Guid("6765B186-6FCD-4D45-A8E1-666A8D37142E"), "Origem", "Origem");
            public static XORMDecimalField Desconto = new XORMDecimalField(global::Projecao.Core.CRD.DB.CRDx.CRDxCartaoLog.Desconto, new Guid("6D015A58-9898-4EF6-9685-BAF3B2DE13FF"), "Desconto", "Desconto");
        }
        #endregion xCRDxCartaoLog 


        #region xCRDxPontoVenda 
        public class xCRDxPontoVenda : XSVCTable
        {

            public static Guid gCID => new Guid("E207BFED-EA60-4A26-87BA-323A5831A2AE");

            public xCRDxPontoVenda()
            {
                Name = "CRDxPontoVenda";
                Alias = "CRDxPontoVenda";
                ID = gCID;
                ParentID =  global::Projecao.Core.CRD.DB.CRDx.CRDxPontoVenda.gCID;

                Items.Add(CRDxPontoVendaID, CRDxPontoVendaID.ID);
                CRDxPontoVendaID.Owner = this;
                CRDxPontoVendaID.OwnerID = ID;
                CRDxPontoVendaID.TableName = Name;
                Items.Add(Fechamento, Fechamento.ID);
                Fechamento.Owner = this;
                Fechamento.OwnerID = ID;
                Fechamento.TableName = Name;
                Items.Add(Pagamento, Pagamento.ID);
                Pagamento.Owner = this;
                Pagamento.OwnerID = ID;
                Pagamento.TableName = Name;
                Items.Add(TaxaAdministracao, TaxaAdministracao.ID);
                TaxaAdministracao.Owner = this;
                TaxaAdministracao.OwnerID = ID;
                TaxaAdministracao.TableName = Name;
                TaxaAdministracao.Alias = "TaxaAdministracao";
                Items.Add(SYSxEstadoID, SYSxEstadoID.ID);
                SYSxEstadoID.Owner = this;
                SYSxEstadoID.OwnerID = ID;
                SYSxEstadoID.TableName = Name;
                Items.Add(Inclusao, Inclusao.ID);
                Inclusao.Owner = this;
                Inclusao.OwnerID = ID;
                Inclusao.TableName = Name;
                Items.Add(SYSxFranqueadorID, SYSxFranqueadorID.ID);
                SYSxFranqueadorID.Owner = this;
                SYSxFranqueadorID.OwnerID = ID;
                SYSxFranqueadorID.TableName = Name;
                Items.Add(DataChave, DataChave.ID);
                DataChave.Owner = this;
                DataChave.OwnerID = ID;
                DataChave.TableName = Name;
                Items.Add(ChaveSeguranca, ChaveSeguranca.ID);
                ChaveSeguranca.Owner = this;
                ChaveSeguranca.OwnerID = ID;
                ChaveSeguranca.TableName = Name;
                Items.Add(Sigla, Sigla.ID);
                Sigla.Owner = this;
                Sigla.OwnerID = ID;
                Sigla.TableName = Name;
            }

            public static XORMFaceField CRDxPontoVendaID = new XORMFaceField(global::Projecao.Core.CRD.DB.CRDx.CRDxPontoVenda.CRDxPontoVendaID, new Guid("79E1DDFA-05AE-4DE6-9A80-205D281B9CA6"), "CRDxPontoVendaID", "Ponto de Venda");
            public static XORMField Fechamento = new XORMField(global::Projecao.Core.CRD.DB.CRDx.CRDxPontoVenda.Fechamento, new Guid("1E8797E4-6CEF-4ABC-982F-5E44006679E9"), "Fechamento", "Dia de Fechamento");
            public static XORMField Pagamento = new XORMField(global::Projecao.Core.CRD.DB.CRDx.CRDxPontoVenda.Pagamento, new Guid("3467EB67-5F19-421F-A3CB-B4B5D6DB5E69"), "Pagamento", "Dia de Pagamento");
            public static XORMDecimalField TaxaAdministracao = new XORMDecimalField(global::Projecao.Core.CRD.DB.CRDx.CRDxPontoVenda.TaxaAdministracao, new Guid("B81C23D0-F0CB-4187-BCF7-3DA5D509C75C"), "TaxaAdministracao", "Taxa");
            public static XORMStateField SYSxEstadoID = new XORMStateField(global::Projecao.Core.CRD.DB.CRDx.CRDxPontoVenda.SYSxEstadoID, new Guid("5644E9C2-D718-4952-A834-C377E3AA385C"), "SYSxEstadoID", "Estado");
            public static XORMDateTimeField Inclusao = new XORMDateTimeField(global::Projecao.Core.CRD.DB.CRDx.CRDxPontoVenda.Inclusao, new Guid("BA74CE42-0620-4115-8DC3-E17AC52B3AEE"), "Inclusao", "Inclusão");
            public static XORMFKField SYSxFranqueadorID = new XORMFKField(global::Projecao.Core.CRD.DB.CRDx.CRDxPontoVenda.SYSxFranqueadorID, new Guid("20FF160E-97E2-420B-99F1-2EE863FB3321"), "SYSxFranqueadorID", "Franqueador");
            public static XORMDateTimeField DataChave = new XORMDateTimeField(global::Projecao.Core.CRD.DB.CRDx.CRDxPontoVenda.DataChave, new Guid("99FD36A0-6844-4E71-93BE-7A224783F770"), "DataChave", "Data da Chave");
            public static XORMField ChaveSeguranca = new XORMField(global::Projecao.Core.CRD.DB.CRDx.CRDxPontoVenda.ChaveSeguranca, new Guid("36C0823B-674D-4AB4-8CE1-5D69F8729CCF"), "ChaveSeguranca", "Change de Segurança");
            public static XORMField Sigla = new XORMField(global::Projecao.Core.CRD.DB.CRDx.CRDxPontoVenda.Sigla, new Guid("7BEC6039-0777-4AEB-B9C3-0543A4F7F1B9"), "Sigla", "Sigla");
        }
        #endregion xCRDxPontoVenda 


        public xCRDxCartaoLog CRDxCartaoLog;
        public xCRDxCartaoVenda CRDxCartaoVenda;
        public xCRDxPontoVenda CRDxPontoVenda;
        public xSYSxPessoa SYSxPessoa;

        public AutorizacoesSinteticoSVC()
        {
            TupleType = typeof(AutorizacoesSinteticoSVC.XTuple);
            DataSetType = typeof(AutorizacoesSinteticoSVC.XDataSet);
            ServiceRuleCID = new Guid("6250104F-9C47-4F66-AC06-BAE3F747379C");
            OnlyActives = false;
            Actions = XSVCAction.All;
            Type = XServiceType.Default;
            ID = new Guid("6DD101EF-E3A9-4530-9A0A-5F5265B96617");
            Name = "AutorizacoesSintetico";
            Title = "Autorizações Sintético";
            IsCacheable = false;
            CompanyControl = false;
            IsJob = false;
            AutoLoad = true;
            FreeForUsers = false;
            ServerSideNewRecord = false;
            UseDistinct = false;
            JobType = XJobType.Default;
            CanExport = false;
            ModuleID = new Guid("EBB5930C-9A21-4AB6-993E-B86F40039784");
            Rights = new Int16[] { 1 }; 
            IsReadOnly = true;
            ClientScript = "Projecao.Core.CRD.js";
            OrderByFields = new Guid[] { xSYSxPessoa.Nome.ID };
            DataSetFields = new Guid[] { xCRDxCartaoLog.CRDxPontoVendaID.ID, xCRDxPontoVenda.TaxaAdministracao.ID, xSYSxPessoa.Nome.ID, xCRDxCartaoLog.Valor.ID };
            PKField = xCRDxCartaoLog.CRDxPontoVendaID.ID;
            ConfigTableID = new Guid("F49233DE-4561-4573-895B-9C2421492A52");
            MasterRuleCID = new Guid("6250104F-9C47-4F66-AC06-BAE3F747379C");
            CRDxCartaoLog = new xCRDxCartaoLog();
            CRDxCartaoLog.IsReadOnly = true;
            AddTable(CRDxCartaoLog);
            CRDxCartaoVenda = new xCRDxCartaoVenda();
            CRDxCartaoVenda.IsReadOnly = true;
            AddTable(CRDxCartaoVenda);
            CRDxPontoVenda = new xCRDxPontoVenda();
            CRDxPontoVenda.IsReadOnly = true;
            AddTable(CRDxPontoVenda);
            SYSxPessoa = new xSYSxPessoa();
            SYSxPessoa.IsReadOnly = true;
            AddTable(SYSxPessoa);
            MasterTableID = CRDxCartaoVenda.ID;
            CRDxCartaoLog_CRDxCartaoLogID_CRDxCartaoVenda_CRDxCartaoVendaID = AddReference(new XSVCReference(new Guid("3E3C355F-9010-4992-B034-5D32B355C45E"), "FK_3E3C355F90104992B0345D32B355C45E", AutorizacoesSinteticoSVC.xCRDxCartaoLog.gCID, xCRDxCartaoLog.CRDxCartaoLogID.ID, AutorizacoesSinteticoSVC.xCRDxCartaoVenda.gCID, xCRDxCartaoVenda.CRDxCartaoVendaID.ID, XJoinType.Inner)); // CRDxCartaoLog.CRDxCartaoLogID --> CRDxCartaoVenda.CRDxCartaoVendaID
            CRDxPontoVenda_CRDxPontoVendaID_SYSxPessoa_SYSxPessoaID = AddReference(new XSVCReference(new Guid("DB4FCEBB-1441-4511-ACA7-AB18F0B224CC"), "FK_DB4FCEBB14414511ACA7AB18F0B224CC", AutorizacoesSinteticoSVC.xCRDxPontoVenda.gCID, xCRDxPontoVenda.CRDxPontoVendaID.ID, AutorizacoesSinteticoSVC.xSYSxPessoa.gCID, xSYSxPessoa.SYSxPessoaID.ID, XJoinType.Inner)); // CRDxPontoVenda.CRDxPontoVendaID --> SYSxPessoa.SYSxPessoaID
            CRDxCartaoLog_CRDxPontoVendaID_CRDxPontoVenda_CRDxPontoVendaID = AddReference(new XSVCReference(new Guid("E6500E83-3600-4762-9EB2-C1A7BC303C40"), "FK_E6500E83360047629EB2C1A7BC303C40", AutorizacoesSinteticoSVC.xCRDxCartaoLog.gCID, xCRDxCartaoLog.CRDxPontoVendaID.ID, AutorizacoesSinteticoSVC.xCRDxPontoVenda.gCID, xCRDxPontoVenda.CRDxPontoVendaID.ID, XJoinType.Inner)); // CRDxCartaoLog.CRDxPontoVendaID --> CRDxPontoVenda.CRDxPontoVendaID
            xCRDxCartaoLog.CRDxPontoVendaID.IsReadOnly = true;
            xCRDxCartaoLog.CRDxPontoVendaID.IsDataField = true;
            xCRDxCartaoLog.CRDxPontoVendaID.AllowEmpty = true;
            xSYSxPessoa.Nome.IsReadOnly = true;
            xSYSxPessoa.Nome.OrderType = XOrderType.Asc;
            xSYSxPessoa.Nome.Length = 256;
            xSYSxPessoa.Nome.IsDataField = true;
            xSYSxPessoa.Nome.AllowEmpty = true;
            xCRDxPontoVenda.TaxaAdministracao.IsReadOnly = true;
            xCRDxPontoVenda.TaxaAdministracao.Length = 25;
            xCRDxPontoVenda.TaxaAdministracao.Scale = 2;
            xCRDxPontoVenda.TaxaAdministracao.IsDataField = true;
            xCRDxPontoVenda.TaxaAdministracao.AllowEmpty = true;
            xCRDxCartaoLog.Valor.IsReadOnly = true;
            xCRDxCartaoLog.Valor.Length = 20;
            xCRDxCartaoLog.Valor.Scale = 2;
            xCRDxCartaoLog.Valor.IsDataField = true;
            xCRDxCartaoLog.Valor.AllowEmpty = true;
        }

        #region XFields

        public class XFields
        {
        public XORMField CRDxPontoVendaID => xCRDxCartaoLog.CRDxPontoVendaID;
        public XORMField Nome => xSYSxPessoa.Nome;
        public XORMField TaxaAdministracao => xCRDxPontoVenda.TaxaAdministracao;
        public XORMField Valor => xCRDxCartaoLog.Valor;
        }
        #endregion XFields
        #region AutorizacoesSinteticoSVC.XTuple

        public  class XTuple : XDataTuple
        {

            public XTuple()
            {
            }

            public XTuple(Object[] pSource)
                : base(pSource)
            {
            }

            public XTuple(Int32 pColCount)
               : this(new Object[pColCount])
            {
            }

            public readonly XFields Fields = new XFields();

            #nullable enable

        public Guid CRDxPontoVendaID
        {
            get
            {
                return (Guid)Value[AutorizacoesSinteticoSVC.xCRDxCartaoLog.CRDxPontoVendaID.ID];
            }
            set
            {
                Value[AutorizacoesSinteticoSVC.xCRDxCartaoLog.CRDxPontoVendaID.ID] = value;
            }
        }
        public Guid? oCRDxPontoVendaID
        {
            get
            {
                GetOldValue(AutorizacoesSinteticoSVC.xCRDxCartaoLog.CRDxPontoVendaID, out Object ovlr);
                return (Guid?)ovlr;
            }
        }

        public String Nome
        {
            get
            {
                return (String)Value[AutorizacoesSinteticoSVC.xSYSxPessoa.Nome.ID];
            }
            set
            {
                Value[AutorizacoesSinteticoSVC.xSYSxPessoa.Nome.ID] = value;
            }
        }
        public String? oNome
        {
            get
            {
                GetOldValue(AutorizacoesSinteticoSVC.xSYSxPessoa.Nome, out Object ovlr);
                return (String?)ovlr;
            }
        }

        public Decimal TaxaAdministracao
        {
            get
            {
                return (Decimal)Value[AutorizacoesSinteticoSVC.xCRDxPontoVenda.TaxaAdministracao.ID];
            }
            set
            {
                Value[AutorizacoesSinteticoSVC.xCRDxPontoVenda.TaxaAdministracao.ID] = value;
            }
        }
        public Decimal? oTaxaAdministracao
        {
            get
            {
                GetOldValue(AutorizacoesSinteticoSVC.xCRDxPontoVenda.TaxaAdministracao, out Object ovlr);
                return (Decimal?)ovlr;
            }
        }

        public Decimal Valor
        {
            get
            {
                return (Decimal)Value[AutorizacoesSinteticoSVC.xCRDxCartaoLog.Valor.ID];
            }
            set
            {
                Value[AutorizacoesSinteticoSVC.xCRDxCartaoLog.Valor.ID] = value;
            }
        }
        public Decimal? oValor
        {
            get
            {
                GetOldValue(AutorizacoesSinteticoSVC.xCRDxCartaoLog.Valor, out Object ovlr);
                return (Decimal?)ovlr;
            }
        }

            #nullable disable
        }
        #endregion AutorizacoesSinteticoSVC.XTuple

        #region AutorizacoesSinteticoSVC.XRule
        public abstract class XRule : XServiceRule<AutorizacoesSinteticoSVC.XDataSet, AutorizacoesSinteticoSVC, AutorizacoesSinteticoSVC.XTuple>
        {
        }
        #endregion AutorizacoesSinteticoSVC.XRule

        #region AutorizacoesSinteticoSVC.XDataSet

        public class XDataSet : XDataSet<AutorizacoesSinteticoSVC.XTuple>
        {
            public XDataSet()
            {
                DataSetType = typeof(AutorizacoesSinteticoSVC.XDataSet);
            }
        }

        public class XDataSet<T> : XServiceDataSet<AutorizacoesSinteticoSVC.XTuple> where T : XDataTuple
        {

            public Guid CRDxPontoVendaID => AutorizacoesSinteticoSVC.xCRDxCartaoLog.CRDxPontoVendaID.ID;
            public Guid Nome => AutorizacoesSinteticoSVC.xSYSxPessoa.Nome.ID;
            public Guid TaxaAdministracao => AutorizacoesSinteticoSVC.xCRDxPontoVenda.TaxaAdministracao.ID;
            public Guid Valor => AutorizacoesSinteticoSVC.xCRDxCartaoLog.Valor.ID;

            public XDataSet()
            {
                DataSetType = typeof(AutorizacoesSinteticoSVC.XDataSet);
            }

        }
        #endregion AutorizacoesSinteticoSVC.XDataSet

        [Guid(AutorizacoesSinteticoSVC.sCID)]
        public  interface XService : XIBaseService
        {
            new XDataSet DataSet
            {
                get;
            }
            new XTuple NewTuple(Object pPKValue = null);
             IEnumerable<XTuple> Tuples
            {
                get;
            }
             XTuple Current
            {
                get;
            }
            new XDataSet Get(XServiceData pData);
             XDataSet Get(params Object[] pWhere);
        }
        [XRegister(typeof(_Service), _Service.sCID, typeof(AutorizacoesSinteticoSVC))]
        protected class _Service : Service<AutorizacoesSinteticoSVC, XDataSet, XTuple>
        {
            public const String sCID = "A840E9BD-41F9-4B41-AEFB-D41182FB2CE4";
            public Guid gCID = new Guid(sCID);
        }

        public class Service<TModel, TDataSet, TTuple> : XBaseService<AutorizacoesSinteticoSVC, XDataSet, XTuple>, XService
             where TModel : AutorizacoesSinteticoSVC, new()
             where TDataSet : XDataSet, new()
             where TTuple : XTuple
        {
            XDataSet XService.DataSet => (XDataSet)DataSet;
            XTuple XService.NewTuple(Object pPKValue)
            {
                return (XTuple)NewTuple(pPKValue);
            }
            public new XDataTuple NewTuple(Object pPKValue = null)
            {
                return (XTuple)base.NewTuple(pPKValue);
            }
            IEnumerable<XTuple> XService.Tuples => (IEnumerable<XTuple>)Tuples;
            XTuple XService.Current => (XTuple )Current;
            XDataSet XService.Get(XServiceData pData)
            {
                return (XDataSet)Get(pData);
            }
            XDataSet XService.Get(params Object[] pWhere)
            {
                return (XDataSet)Get(pWhere);
            }
            public Service()
            {
                ID = gCID;
            }
        }
    }

}